[클린코드 3기] 원동휘 로또 미션 STEP 1
next-step/js-racingcar pull request #106
Opened 2022-07-29 13:53 UTC by wondonghwi

윤호님 안녕하세요! 잘부탁드립니다.!
미션진행이 너무 늦어진 관계로 먼저 기능부터 작업했고, 리뷰받으면서 바로 테스트 코드를 작업하려고합니다 💪💪💪

일단 미션 1,2,3 단계가 서로 연관성이 높다고 생각되어서 분리하는데에서 어려움을 겪었는데
미션1을 하면서 그과정에 미션3단계의 일부분인 setInerval 구현도 함께 진행했습니다.

**< 어려움을 겪은 부분 >**
자동차이름을 입력하고, 중간 횟수를 입력하는 부분까지는 어렵지 않게 작업했는데,
매초마다 어떻게 ⬇️, Spinner를 그려주어야할지 감을 못잡았습니다. 그 과정에서 이현정님과 PP를 진행했고,
```
insertAdjacentHTML
```
라는 메서드등 어떻게 화면에 조건에따라 특정 element를 추가할지 PP 진행에서 많은 인사이트를 얻었습니다! 😄

**< 작업 관심사 >**
전체적으로 어떻게 폴더구조를 나눌지, 현재 A라는 이름의 파일에 B,C라는 변수, 함수, 메소드가 들어가는게 맞는건지 고민입니다.
Class에서 view와, service로 폴더를 구분해서 역할을 분리시키는걸 목표로 했는데 어떻게 하면 더 폴더구조를 잘 나눌수 있을지 고민됩니다.

가장 큰 관심사는 **변수명, 함수명, 메소드명**입니다.
- 정확하게 의미에 맞게 표현했는지, 더좋은 변수명, 함수명, 메소드명이 있다면 그부분도 많은 리뷰 부탁드드립니다! ☺️☺️☺️

2022-07-30 08:38 UTC, yujo11 requested changes
안녕하세요 동휘님 자동차경주 미션 리뷰를 맡게 된 조윤호입니다.

페어프로그래밍 요청 주셨을 때 시간이 안 되서 같이 페어프로그래밍 진행을 못 했는데요. 

현정님과 같이 페어를 진행 하면서 인사이트를 얻으셨다니 다행이네요!

리뷰어들 외에 같이 과정을 진행중이신 분들과도 페어 프로그래밍을 진행하시다 보면 더 많은 인사이트를 얻을 수 있으실거라고 생각해서 앞으로도 적극적으로 페어 프로그래밍을 활용해보셨으면 좋겠다는 생각이 드네요!

> - 정확하게 의미에 맞게 표현했는지, 더좋은 변수명, 함수명, 메소드명이 있다면 그부분도 많은 리뷰 부탁드드립니다! 

변수명, 함수명, 메소드명을 신경쓰면서 봐서 지엽적인 리뷰가 많아졌는데요. 제 의견을 말씀드렸을 뿐 절대 "정답"은 아니니 읽어보시고 납득이 가는 부분들에 대해서 적용해보시면 좋을거 같습니다!

> - setInterval되는것 관련 테스트 코드는 다른 미션때 작성해볼예정입니다.! 검색해서 찾은 키워드는 clock인데 이부분도 clock을 이용하는게 맞는건지 궁금합니다!

clock을 사용하셔도 되고 wait를 사용하셔도 되고 동휘님이 맞다고 생각하시는 방법으로 우선 작성해보시면 좋을거 같네요!

step1 미션 진행하느라 고생 많으셨습니다 동휘님! 👍 👍 👍

2022-07-30 08:38 UTC, yujo11 commented on src/js/index.js
> +    racing.startRacingGame(coin);
`renderRacingSection`이라는 이름을 보면 RacingSection을 render할거 같은데 레이싱 경주도 여기서 트리거가 되어 시작되어 이름과 맞지 않는 역할까지 수행하고 있는것처럼 느껴지네요

2022-07-30 08:38 UTC, yujo11 commented on src/js/constants.js
> +const DELAY = 1000;
`DELAY`라는 이름은 너무 범용적인데 조금 더 상세하게 이름을 지어보시면 어떨까요?

2022-07-30 08:38 UTC, yujo11 commented on src/js/constants.js
> +};
이것도 "무엇"의 MIN, MAX 인지 네이밍으로 명확하게 표현해주시면 좋을거 같네용

2022-07-30 08:38 UTC, yujo11 commented on src/js/constants.js
> +};
여기도 `NOT_VALIDATE_NAME`, `NO_VALUE_ENTERED`라는 이름으로는 어떤 값을 가지고 있을지 유추하기가 힘드네용

2022-07-30 08:38 UTC, yujo11 commented on src/js/service/Calculate.js
> +export default Calculate;
이 클래스에서 가지고 있는 메서드들은 `util`의 성격이 강한데 `static`으로 사용하셔도 좋을거 같아요.

그리고 그 전에 왜 `Class`를 사용하신건지 궁금하네용

보통의 `Class`는 Object를 생성하기 위한 Template의 역할을 수행하는데요. 이 `Class`가 존재해야 하는 이유를 잘 모르겠네요

2022-07-30 08:38 UTC, yujo11 commented on src/js/service/CreateRacingcarTemplate.js
> +}
이 폴더에 있는 다른 함수들은 `template`이라는 suffix를 가지고 있는데 여기에만 `template` suffix가 없는 이유가 있을까요?

2022-07-30 08:38 UTC, yujo11 commented on src/js/service/CreateRacingcarTemplate.js
> +}
단순히 template을 반환하는 함수라면 역할을 더 단순하게 만들어서 요청받은 값을 넣어서 반환해주는 정도의 역할만 수행하면 더 좋을거 같네용

2022-07-30 08:38 UTC, yujo11 commented on src/js/index.js
> +const racing = new RacingService(createTemplate, calculate);
현재는 파싱해오는 값들은 전역에 존재하고, 해당 값들을 Class에 주입하고 있는데  DOM으로부터 파싱해오는 값들도 Class가 갖고 있도록 하면 어떨까요?

2022-07-30 08:38 UTC, yujo11 commented on src/js/timer.js
> +export { getIntervalTimer };
파일의 네이밍, 함수의 네이밍 모두 잘 납득이 가지 않는데요.

1. `timer`라는 이름은 util성을 가지고 있을거 같다는 느낌을 받는데요. 현재는 특정 도메인에서만 사용할 수 있네요. 실제로 받고 있는 파라미터들의 이름도 `cars`, `carPlayers`처럼 특정 도메인을 위해서만 사용되는거 같고요.
2. `getIntervalTimer`라는 이름은 어떤 return값을 통해 `IntervalTimer`를 반환해줄거 같은 느낌을 받지만, 실제로는 아무것도 반환하지 않고 있네요.

2022-07-30 08:38 UTC, yujo11 commented on src/js/timer.js
> +export { getIntervalTimer };
함수는 인자를 많이 받을수록 사용하기가 어려워지는데요.

이 인자들을 모두 전달받아야할 필요가 있을까요? 자바스크립트의 함수는 일급  객체이기 때문에 callback함수를 전달하는 식으로도 대체가 가능할거 같네용

2022-07-30 08:38 UTC, yujo11 commented on src/js/timer.js
> +const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
```suggestion
const getIntervalTimer = ({ createTemplate, calculate, cars, carPlayers, coin }) => {
```

그리고 함수의 인자가 많아지는 경우에는 객체로 묶어서 받아주시는게 어떨까요?

2022-07-30 08:38 UTC, yujo11 commented on src/js/utils.js
> +};
이건 `util`함수가 아닌거 같네요

2022-07-30 08:38 UTC, yujo11 commented on src/js/validate/index.js
> +};
`validate`의 경우에도 보통은 util성을 가진 `validate`함수들을 모아두는 용도로 많이 사용하는데요? 현재 여기에 존재하는 함수들은 도메인과 강하게 결합이 되어 있는 느낌이네용

2022-07-30 08:38 UTC, yujo11 commented on src/js/validate/index.js
> +  return splitInputValue.forEach((item) => {
여기서 반환하는 값을 사용하시나요? 어떤 값을 반환하고 계신건가요?

2022-07-30 08:38 UTC, yujo11 commented on src/js/validate/index.js
> +};
그리고 `is` prefix는 보통 boolean 값을 반환하는 용도로 많이 사용하는데요. 

이 함수는 입력받은 인자의 옳고 그름을 판단하는 역할을 넘어서 그 결과에 따라 Error를 throw하고 있습니다.

한 가지 역할만 수행하도록 변경해보시는건 어떨까요

2022-07-30 09:51 UTC, wondonghwi commented on src/js/index.js
> +  const coin = parseInt(carTryInputValue, 10);
Number(), parseInt() 모두 문자열을 숫자로 변환하는데 자주 사용되지만 

parseInt는 숫자가 아닌 첫 번째 문자까지 구문 분석, Number는 전체 문자열을 변환하려고 시도하기때문에 parseInt가 더 안전하다고 생각해서 사용하기때문에 Number를 사용해 문자열을 숫자로 바꾸는것보다 paseInt로 명시적으로 10진수를 줘서 바꾸는게 더 좋은 습관으로 알고 실천하고 있습니다.

혹시 윤호님께서 parseInt를 쓰신다면 윤호님은 어떤이유로 parseInt를 사용하시는지도 궁금합니다!

아래는 예시를 적어보았습니다!
```javascript
parseInt('32px'); // 32
Number('32px'); // NaN
```

2022-07-30 10:05 UTC, wondonghwi commented on src/js/index.js
> +  const splitInputValue = carNameField.getSplitInputValue();
> split이 실행된 채로 값을 가져오는거라면 splited로 사용해보시는건 어떨까요?
이부분이 고민을 많이한 부분인데요! 나눠진이라는 의미로 과거형으로 사용하려했더니 split의 과거형이 split이라고 IDE에서 오타라고 밑줄 쫙 하더라구요 그래서 고민하다가 ** 나눠진이라는 의미여도 split으로 그냥사용했는데 확실히 혼란을 야기할 수 있어보이네요!!** 

검색한 결과로, 아래 링크들에서 확인해보면 splitted가 **정확한 철자?**는 아닌것같지만 많이 사용한다고 생각되어서 splitted로 바꿔보았습니다!!

https://textranch.com/250843/splitted/or/splited/
https://whichiscorrect.com/split-or-splited/

2022-07-30 10:24 UTC, wondonghwi commented on src/js/constants.js
> +const DELAY = 1000;
DELAY_TIME_MS -> Milisecond는 MS로 축약해서 변수명 변경해보았습니다!

2022-07-30 10:24 UTC, wondonghwi commented on src/js/index.js
> +    displayTemplate($racingCarPlayer, templateCarPlayer);
작성할때는 index.js파일에서 분리하기 위한 용도로 분리하는게 좋다고 생각했는데 리뷰주신내용을 곱씹어보면서 다시생각해보니까


나눌 필요없는부분까지 따로 함수로분리하는건 분리하는 의미가없다고 생각이되어서 

displayTemplate은 삭제했습니다.!  대신 아래코드처럼 더 명확하게 한눈에 파악할 수 있도록 index.js 파일에 위치하도록 했습니다!


```javascript 

$racingCarPlayer.innerHTML = createTemplate.createRacingTemplate(splitted);

```

2022-07-30 10:28 UTC, wondonghwi commented on src/js/index.js
> +    racing.startRacingGame(coin);
그렇네요!! 짚어주셔서 감사합니다! 역할분리를 위해 renderRacingSection는 함수로 따로 호출해주는식으로 분리시켜보았는데 이부분은 더 좋게 나눌수 있는방법이 있을것같은데, 제가 변경한 내용이 윤호님 리뷰주신내용의 의도에 맞는건지 궁금합니다!

```javascript
const renderRacingSection = (coin) => {
  racing.startRacingGame(coin);
};
```

2022-07-30 10:49 UTC, wondonghwi commented on src/js/constants.js
> +};
이부분은 좀 바꾸기가 어렵네요.!

NOT_VALIDATE_NAME_LENGTH,
NOT_VALIDATE_VALUE_LENGTH

이렇게 바꿔봤는데 별로 이전과 달라진게 없네요 혹시 추천해주실 상수명이 있으실까요?

의도는 유효하지않은 이름길이 조건, 유효하지않은 Value 길이 조건입니다.!

2022-07-30 10:59 UTC, wondonghwi commented on src/js/service/Calculate.js
> +export default Calculate;
**수정했습니다!**

사실 util과 고민을 많이했는데 Class에 대해 알아본결과 그룹화하는데도 의미가있다생각되어서 getRandomCount를 private으로 하고, isForwardCondition를 public으로 해서 사용하는걸의도했습니다. 그런데 getRandomCount메소드를 private을 안해놨었네요 😢

리뷰주신 static은 따로 한번도 사용해보지않아서 검색해보았더니
> 클래스 함수 자체에 메서드를 설정할 수도 있습니다. 이런 메서드를 정적(static) 메서드라고 부릅니다.
> 정적 메서드는 아래와 같이 클래스 안에서 static 키워드를 붙여 만들 수 있습니다.

라고 하네요 **constructor를 사용하지 않는경우는 Class의 메소드로 사용하면 static을 붙여주는게 더 좋을까요??!**

사실 Class를 사용안하다가 이번 넥스트스텝때 새로 배워가자, 얻어가자라는 느낌으로 사용하고 있는데요 그래서 Class사용의 미숙함이 여실히 들어나네요 ㅠㅠ

2022-07-30 11:01 UTC, wondonghwi commented on src/js/service/CreateRacingcarTemplate.js
> +}
놓쳤습니다 ㅠ! 짚어주셔서감사합니다 수정했습니다! ☺️

2022-07-30 11:13 UTC, wondonghwi commented on src/js/index.js
> +const racing = new RacingService(createTemplate, calculate);
> DOM으로부터 파싱해오는 값 === querySelector로 선택한 선택자가 맞을까요? 정확히 이해했는지 확인하고싶은 의도입니다.


FieldsetView라는 Class에서 윤호님 리뷰주신 내용을 적용하려고 보니까 Class내부에서 선택자를 특정하면 
하나의 Class를 두개이상의 Fieldset의 내용을 재사용 할 수 없을거라 판단되어서 수정하지 못했습니다.


FieldsetView라는 Class를 아래처럼 재사용해서 이용하고있는데 이부분도 윤호님이 리뷰주신 내용 적용이 가능한지 여쭤보고싶습니다.
```javascript
const $carNameFieldset = $carNameForm.querySelector('#car-name');
const $carTryNumberFieldset = $carTryNumberForm.querySelector('#car-try-number');

const carNameField = new FieldsetView($carNameFieldset);
const carTryNumberField = new FieldsetView($carTryNumberFieldset);
```

2022-07-30 11:17 UTC, wondonghwi commented on src/js/timer.js
> +const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
이부분은 잘 이해하지 못했습니다 ㅠ

2022-07-30 11:26 UTC, wondonghwi commented on src/js/utils.js
> +};
넵 새로운 Service Class를 만들어 수정해보았습니다!

2022-07-30 11:30 UTC, wondonghwi commented on src/js/validate/index.js
> +  return splitInputValue.forEach((item) => {
아무값도 반환하지 않고있습니다!

의도는 반환값은 없고, 오류일때만 체크하는것이라서, 함수를 실행했을때 if문 조건에 걸려서 
throw new Error(ALERT_MESSAGE.NOT_VALIDATE_NAME_LENGTH);
와 같은 Error 생성을 시켜주는것이고(catch문에 잡히도록) 
**아무것도 반환하지는 않습니다**

2022-07-30 11:58 UTC, wondonghwi commented on src/js/validate/index.js
> +};
넵! 리뷰남겨주신대로 최대한 한가지 역할만 수행하도록 함수를 변경해보았습니다!!!

윤호님 리뷰남겨주신내용의 의도에 정확히 맞게 변경했다고는 자신할 수 없는것같지만 한가지의 역할만 하도록 변경, 변수명에 맞게 변경은 성공적으로 변경한것같습니다!! 확인부탁드려요!~

변경된내용 validate/index.jks 파일에서 확인하실 수 있습니다.

2022-07-30 12:06 UTC, wondonghwi commented on src/js/timer.js
> +export { getIntervalTimer };
다시 코드를 보니 startRacingGame을 하면 결국 하는 역할이 getIntervalTimer 호출밖에 없고, 그렇게 함으로써 말씀해주신대로 getIntervalTimer 함수의 매개변수가 너무 많아져서 오히려 읽고, 사용하기 복잡해지는것같습니다.

또한 timer도 너무 명확하지않은느낌이라 
파일이름, 변수명이 더 혼란을 초래할 수 있다고 생각되어 startRacingGame메소드안에 합쳐놓았습니다.

이렇게 작업하면 startRacingGame메소드의 크기가 커지긴하지만 의도에맞지않은 파일명과, 변수명, 오히려 불편하게 많은 인자를 추가해야하는상황에서는 함수를 분리하는게 꼭 좋지만은 않다는생각이 들어서 이렇게 수정하였습니다!

> 함수는 인자를 많이 받을수록 사용하기가 어려워지는데요. 
이부분 적극 공감합니다!..!

2022-07-30 12:08 UTC, wondonghwi commented on src/js/service/CreateRacingcarTemplate.js
> +}
이부분은 잘 이해를 못했습니다! 현재도 요청값을 받아 map으로 반환해주고 있다고 판단되는데 어떤부분에서 리뷰주신건지 의도파악이 안됐습니다 ㅠㅠ 추가설명 부탁드려도될까요?

2022-07-30 12:11 UTC, wondonghwi commented
@yujo11 윤호님 수정사항이 너무너무 많았네요! 완전 정성스럽게 리뷰많이남겨주셔서 정말감사합니다!
수정할 수 있는부분은 전부 수정완료해서 다시리뷰부탁드립니다~!

2022-07-31 10:40 UTC, yujo11 commented on src/js/index.js
> +  const coin = parseInt(carTryInputValue, 10);
저는 `pasreInt`보다 `Number()`를 많이 쓰는 편입니다. 

`parseInt`의 경우 말씀해주신대로 구문을 분석하는데요. 저는 `32px`과 같은 값이 들어오면 `NaN`으로 처리되고 핸들링 하는걸 선호하기 때문입니다.

또한 소소하게 pasre"Int"이기 때문에 소수를 전달받았을 때 정수로 변환하는 점도 있구요

2022-07-31 10:52 UTC, yujo11 commented on src/js/index.js
> +    racing.startRacingGame(coin);
넵 그러한 의도도 있었는데요. 

현재 함수는 `render`라는 prefix를 가지고 있는데 함수 안에서는 `racingGame`을 start하고 있어서 이름과 함수 내부 내용에 일치하지 않는다는 느낌이 드네용

2022-07-31 10:53 UTC, yujo11 commented on src/js/constants.js
> +};
네이밍은 사실 정답이 없는 부분이긴한데 저라면 `INVALID_CAR_NAME_LENGTH`, `INVALID_RACING_COUNT` 같은 이름을 사용할거 같네용

2022-07-31 10:57 UTC, yujo11 commented on src/js/service/Calculate.js
> +export default Calculate;
`static`으로 메서드를 선언하게 되면 아래처럼 생성자를 통해 객체를 생성하지 않고 해당 메서드를 사용할 수 있는데요.

```js
class Calculate {
  static getRandomCount() {
    return Math.floor(Math.random() * 10);
  }

 static isForwardCondition() {
    return this.getRandomCount() > 4;
  }
}

Calculate.getRandomCount()
```

말씀해주신 그룹화의 의도였다면 매번 객체를 생성해서 사용하지 않도록 static으로 선언하시는건 어떨까하는 생각에 드렸던 리뷰입니다!

2022-07-31 11:01 UTC, yujo11 commented on src/js/service/CreateRacingcarTemplate.js
> +}
현재는 carNames가 배열의 형태일 때만 해당 메서드를 사용가능한데요.

조금 더 역할을 단순화 시켜서 다른 template함수들처럼 string값만 넣은 채로 template을 반환하게 하면 어떨까 하는 리뷰였습니다!

현재는 carNames를 배열로 관리하고 계시지만 만약 carNames가 배열이 아닌 객체가 되는 등 정책상의 이유로 변경이 된다면 이 함수 역시 함께 변경이 되야 하는데요.

배열이 아닌 string만 받아서 템플릿을 생성하고 반환하게 한다면 더 범용적으로 사용이 가능할거 같네용

2022-07-31 11:05 UTC, yujo11 commented on src/js/timer.js
> +export { getIntervalTimer };
```js
// 선언
const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
...
}

// 사용
getIntervalTimer(createTemplate, calculate, cars, carPlayers, coin) // O
getIntervalTimer(createTemplate, calculate, coin, cars, carPlayers) // X
```

현재 위와 같은 형식으로 코드가 선언되어 있다면 5개의 인자를 넘길 때 항상 순서를 맞춰서 넣어줘야 하는데요. 이는 개발자가 parameter의 순서를 모두 알고, 기억해야 된다는 의미이기도 합니다.

하지만 아래와 같이 객체를 통해 인자를 받게 된다면 parameter의 순서와 관계없이 값을 받아서 사용할 수 있어서 해당 함수를 사용할 때의 실수를 줄여줄 수 있을거 같네용

```js
// 선언
const getIntervalTimer = ({ createTemplate, calculate, cars, carPlayers, coin }) => {
...
}

// 사용
getIntervalTimer({ createTemplate, calculate, cars, carPlayers, coin }) // O
getIntervalTimer({ createTemplate, calculate, coin, cars, carPlayers}) // O

2022-07-31 11:05 UTC, yujo11 commented on src/js/timer.js
> +const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
```js
// 선언
const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
...
}

// 사용
getIntervalTimer(createTemplate, calculate, cars, carPlayers, coin) // O
getIntervalTimer(createTemplate, calculate, coin, cars, carPlayers) // X
```

현재 위와 같은 형식으로 코드가 선언되어 있다면 5개의 인자를 넘길 때 항상 순서를 맞춰서 넣어줘야 하는데요. 이는 개발자가 parameter의 순서를 모두 알고, 기억해야 된다는 의미이기도 합니다.

하지만 아래와 같이 객체를 통해 인자를 받게 된다면 parameter의 순서와 관계없이 값을 받아서 사용할 수 있어서 해당 함수를 사용할 때의 실수를 줄여줄 수 있을거 같네용

```js
// 선언
const getIntervalTimer = ({ createTemplate, calculate, cars, carPlayers, coin }) => {
...
}

// 사용
getIntervalTimer({ createTemplate, calculate, cars, carPlayers, coin }) // O
getIntervalTimer({ createTemplate, calculate, coin, cars, carPlayers }) // O

2022-07-31 11:10 UTC, yujo11 commented on src/js/index.js
> +const racing = new RacingService(createTemplate, calculate);
`FiledSet`의 내용을 바꾸거나 새롭게 Class를 정의해서 사용하셔야 될거 같은 부분이긴 하네용

2022-07-31 11:17 UTC, yujo11 approved these changes
안녕하세요 동휘님! 코멘트를 많이 남겼었는데 빠르게 확인하고 수정해주셨군요!

추가적으로 남겨주신 질문들에는 코멘트 달아놨으니 확인해주시면 좋을거 같습니다!

이번 step1은 이만 머지하고 다음 step으로 넘어가셔도 좋을거 같네요!!

그리고 이건 코드와는 관련없는 부분이지만 커밋을 조금 더 작은 단위로 나눠서 자주 하시면 어떨까 하는 생각이 드네요!

고생 많으셨습니다 동휘님!! 👍 👍 👍

2022-07-31 11:17 UTC, yujo11 commented on src/js/service/RacingService.js
> +      }
이 부분은 eslint disabled를 하신 이유가 있을까요? 린트 룰에 따라 수정을 했어도 될거 같아서용

2022-07-31 11:17 UTC, merged

2022-07-31 15:15 UTC, wondonghwi commented on src/js/service/RacingService.js
> +      }
이부분은 eslint를 아무리 찾아봐도 해결하지 못해서 결국 인라인으로 eslint disabled를 했습니다. 

count++을 -> count = count + 1 
등등 여러가지 방법으로변경해보았는데 안돼서 결국 린트룰을 수정했습니다!

2022-07-31 15:17 UTC, wondonghwi commented on src/js/timer.js
> +const getIntervalTimer = (createTemplate, calculate, cars, carPlayers, coin) => {
우와 이런게 있었군요!! 좋은정보 얻어갑니다 감사합니다!! 
> 객체를 통해 인자를 받게 된다면 parameter의 순서와 관계없이 값을 받아서 사용할 수 있어서 해당 함수를 사용할수 있다.

모르던정보였네요 감사합니다~!