[클린코드 3기 임대호] 자동차 경주 미션 STEP 1 & STEP 2
next-step/js-racingcar pull request #113
Opened 2022-08-06 08:19 UTC by ingdaeho

준일님 안녕하세요! 미션 제출 기간이 많이 늦었지만 뒤늦게라도 PR 올립니다😭

[데모링크](https://ingdaeho.github.io/js-racingcar/)

MVC패턴에 맞춰서 코드를 작성하다보니 패턴에 맞게 로직이나 관심사를 분리하는데는 좋은점이 있는것 같은데,
어떤 상호작용이 일어나면 model -> controller -> view 이렇게 흐름이 진행되는면서 controller의 render에서 
각각의 view의 show라는 메서드에 값을 전달해서 view를 그려주고 있는데, 
여기서 너무 여러가지의 일들을 하고 있는것 같아서 어떻게 개선할 수 있을지 도움을 청하고 싶습니다..!

2022-08-07 13:29 UTC, JunilHwang requested changes
안녕하세요 대호님! 자동차 미션을 함께하게 된 리뷰어 황준일입니다🙇‍♂️ 
한 번에 2단계 미션까지 진행해주셨네요!
설계도 무척 잘 해주신 것 같아요 👏👏
다만 지금 대호님께서 이야기해주신 것 처럼 controller에서 너무 많은 일을 해주는 것 같습니다 ㅎㅎ
제가 리뷰에도 달아놓은 것 처럼 Controller가 타입 변환 / 데이터 검증 까지 해줄 필요가 있을까요? Controller의 역할이 정확히 어떤 범위까지인지 고민해보시면 좋을 것 같아요!

이 외에도 자잘한 리뷰 남겼으니 확인 부탁드립니다 😁

2022-08-07 13:29 UTC, JunilHwang commented on cypress/e2e/racing-car.cy.js
> +  });
시도 횟수가 0이거나 음수인 경우, 자연수가 아닌 경우도 있지 않을까요?

2022-08-07 13:29 UTC, JunilHwang commented on index.html
> +                min="1"
여기서 min을 지정해줬었네요! 그렇다면 음수인 경우는 포함되지 않아도 소수인 경우에 대한 테스트도 필요할 것 같아요!

2022-08-07 13:29 UTC, JunilHwang commented on cypress/e2e/racing-car.cy.js
> +  });
지금은 랜덤으로 자동차의 전진 조건이 정해지는데,
그렇다면 이런 상황에서 input에 대한 output을 정확하게 예측할 수 있도록 테스트하기 위해선 어떤 장치가 필요할까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/index.js
> +}
현재 이 파일의 이름이 index.js로 되어 있는데,
index.js는 보통 export 하는 용도로 많이 사용해서요!

그래서 일단 App이라는 파일도 하나 만들어주고
App을 실행시켜주는건 main이라는 js 파일에서 해줄 수 있도록 하면 어떨까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Model.js
> +export default class RacingCar {
파일 이름과 export default로 내보내주는 class이름을 일치시켜주면 더 좋지 않을까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Model.js
> +  }
이렇게 멤버변수로 사용되는 것들은 미리 class field에 정의해주면 다른 사람이 이 class에 어떤 멤버변수들이 존재하는지 파악하기가 쉽답니다!

```js
cars;
tryCount;

constructor(cars = [], tryCount = 0) {
    this.cars = cars;
    this.tryCount = tryCount;
  }
```

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Model.js
> +    this.tryCount = null;
이름이 `tryCount` 라고 숫자형으로 표기되어 있는데, 실제로 할당되는 값은 null 이네요! null로 할당할 필요가 있을까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/View.js
> +    return this;
`return this`는 불필요해보여요!

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Controller.js
> +import { CAR_NAME_RULE, TRY_COUNT_LIMIT } from './constants.js';
이런 상수들은 잘 생각해보면 Controller와 연관이 없을 것 같아요!
그렇다면 Controller가 현재 수행하고 있는 역할이 뭔가 이상한게 아닐까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Controller.js
> +      this.model.storeCars(cars);
```javascript
      this.model.storeCars(carNames);
```
검증 로직도 Model에서, 변환도 Model에서 수행해줘야 하지 않을까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Controller.js
> +  }
```javascript
  render() {
    const { cars, tryCount } = this.model;
    this.carNameFormView.show(cars);
    this.raceCountFormView.show(cars, tryCount);
    this.racingProgressView.show(cars, tryCount);
    this.racingResultView.show(cars, tryCount);
  }
```
이렇게 표현할 수 있겠네요!

2022-08-07 13:29 UTC, JunilHwang commented on src/js/Controller.js
> +    this.racingResultView = racingResultView;
너무 많은 멤버변수가 있어요!
view는 하나의 object로 묶어주면 어떨까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +  }
지금 대부분의 View가 bindEvents를 생성 시점에 실행하네요.
차라리 bindEvents는 `View`를 생성하는 시점에 실행해주도록 하면 어떨까요?

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +    this.buttonElement = $('#submit-car-name');
```javascript
  get $inputElement() {
    this.element.querySelector('#input-car-name');
  }

  get $inputElement() {
    this.element.querySelector('#submit-car-name');
  }
```
멤버변수에 할당하는 대신에
이렇게 표현해줄 수도 있답니다!

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +  }
앞선 리뷰를 종합한다면 이 생성자 자체가 없어도 되겠네요!

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +  }
다른 View에 대한 내용들도 위의 리뷰를 참고해주세요!

2022-08-07 13:29 UTC, JunilHwang commented on src/js/views/RacingResultView.js
> +  }
배열 메소드를 무척 잘 사용하시는 것 같아요!! 👏👏👏

2022-08-07 13:29 UTC, JunilHwang commented on src/js/utils.js
> +export const $ = (selector) => document.querySelector(selector);
```javascript
export const $ = (selector, parent = document) => parent.querySelector(selector);
```
이렇게 정의해주면 더 다채롭게 사용할 수 있겠네요 ㅎㅎ

2022-08-11 09:28 UTC, ingdaeho commented on cypress/e2e/racing-car.cy.js
> +    cy.enterCarNames('bread,candy,bread');
```
const cars = carNames.split(',').map((name) => name.trim());
```
입력으로 들어오는 자동차 이름들에 대해서 전부 trim을 해주고 있어서 여백을 없애고 있습니다!
아니면 테스트 케이스가 있어야 한다는 뜻일까요..?

2022-08-11 09:29 UTC, ingdaeho commented on index.html
> +                min="1"
소수인 경우도 있군요!
min attribute도 그렇고 답은 요구사항에 따라 달라질순 있겠지만, 
직집 소수를 검증하는 로직을 추가하는 방법과 input의 step attribute를 사용해서 소수값을 막는 방법 중에 어떤 방법이 좋을까요?

혹시 모를 브라우저 호환성을 생각한다면 전자의 방법이 더 좋지 않을까 생각이 드는데, 그냥 두 방법 다 하는게 제일 안전한것 같기도 하고..
준일님의 생각은 어떠신가요??

2022-08-11 10:17 UTC, ingdaeho commented on src/js/views/CarNameFormView.js
> +    this.buttonElement = $('#submit-car-name');
접근자로 만들게 되면 이에 대한 로직도 Controller나 Model로 옮겨야 하는것 같은데, 제 생각이 맞을까요?
그리고 이렇게 하는 이유는 ["똑똑한/느긋한 접근자"](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/get#%EB%98%91%EB%98%91%ED%95%9C_%EB%8A%90%EA%B8%8B%ED%95%9C_%EC%A0%91%EA%B7%BC%EC%9E%90) 이러한 이유일까요?

2022-08-11 10:23 UTC, ingdaeho commented on src/js/views/CarNameFormView.js
> +  }
View를 생성하는 시점은 인스턴스를 생성하는 시점을 말씀하시는건가요..?

2022-08-11 10:28 UTC, ingdaeho commented on src/js/Controller.js
> +import { CAR_NAME_RULE, TRY_COUNT_LIMIT } from './constants.js';
그렇네요.. MVC 각각의 계층에 대해서 다시 잘 생각해봐야겠네요 😂

2022-08-11 10:29 UTC, ingdaeho commented on src/js/Controller.js
> +      this.model.storeCars(cars);
넵! Model에서 수행하도록 수정해보겠습니다 👍

2022-08-11 10:48 UTC, ingdaeho commented on src/js/Model.js
> +    this.tryCount = null;
준일님 말씀처럼 변수명에 맞게 값도 할당하는게 맞는거 같습니다
그리고 null보다는 차라리 0을 할당하는게 변수의 타입을 줄일 수 있다는점에서 더 좋을거 같네요!

2022-08-11 10:51 UTC, ingdaeho commented on src/js/utils.js
> +export const $ = (selector) => document.querySelector(selector);
좋은 팁 감사합니다 😄

2022-08-11 11:08 UTC, ingdaeho commented
준일님 안녕하세요! 리뷰 감사합니다!!
리뷰해주신 내용 부분적으로 수정해보았습니다!

코멘트 남겨놓았지만 View쪽 관련된 부분은 제가 아직 이해를 잘 못해서 남겨두었는데요..
조금 힌트를 더 주시면 다시 수정해보겠습니다..😂
감사합니다~

2022-08-12 07:39 UTC, JunilHwang commented on cypress/e2e/racing-car.cy.js
> +    cy.enterCarNames('bread,candy,bread');
테스트 케이스가 있어야 한다는 이야기였습니다!

2022-08-12 07:41 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +  }
생성자가 실행되는 시점 입니다!
CarNameFormView가 View를 상속받아서 사용하는데,
View 자체에 bindEvents를 만들어주고
View의 constructor 내부에서 bindEvents를 실행해도 되지 않을까? 하는 이야기였습니다 ㅎㅎ
이렇게 라이프 사이클에 대한 부분을 View에게 위임하는거죠!

2022-08-14 04:52 UTC, JunilHwang approved these changes
안녕하세요 대호님! 리뷰가 많이 늦어졌네요 ㅠㅠ 죄송합니다 🙏
질문해주신 부분에 대해서 답변 달아놓았고,
이번 스텝은 여기서 마무리 하도록 하겠습니다!
이어서 다음 스텝 진행하면서 이번에 남긴 피드백 참고해주시면 될 것 같습니다!
감사합니다 🙇‍♂️

2022-08-14 04:52 UTC, JunilHwang commented on src/js/views/View.js
> +  }
제가 위에 코멘트에 달아놓은 것 처럼 View에서 라이프사이클을 만들어놓으면 어떨까요? (bindEvents를 생성자에서 실행해주는 등의 작업을 의미합니다!)

2022-08-14 04:52 UTC, JunilHwang commented on src/js/Controller.js
> +    this.views = views;
```suggestion
  model; views;
  constructor(model, views) {
    this.model = model;
    this.views = views;
```
이렇게 미리 멤버변수를 클래스 필드 영역에 정의해주면 어떨까요?
그래야 다른 사람들이 이 클래스에서 사용되는 멤버변수를 파악할때 편할 것 같아요!

```suggestion
  #model; #views;
  constructor(model, views) {
    this.#model = model;
    this.#views = views;
```
그리고 이렇게 `#`을 이용해서 private 으로 멤버변수를 선언할 수 있답니다!

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      if (this.#isCarNameDuplicated(cars)) throw new Error('자동차 이름은 중복될 수 없습니다.');
지금은 registerCars 내에서 throw를 발생시키면서 동시에 try/catch를 하고 있어요.

그보다는 이렇게
```suggestion
      this.#validateCarNameLength(cars);
      this.#validateDuplicatedCarName(cars);
```
각각의 메소드에서 throw를 해주면 어떨까요?

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      if (tryCount > TRY_COUNT_LIMIT) throw new Error('최대 시도 횟수는 30회 입니다.');
앞선 내용과 동일합니다!

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +    }
그리고 또 잘 생각해보면, RacingCar는 DOM과 무관한 코드(도메인 로직, 서비스 로직, 비지니스 로직)입니다.
그런데 catch에서 alert를 발생시키고 있으니 무척 부자연스럽네요!
이런 부분은 controller에서 처리해주면 어떨까요?

- domain에서 error 발생
- controller에서 catch 후 처리

이렇게 해주면 자연스러울 것 같아요!

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      this.tryCount = tryCount;
tryCount가 여기서 할당되지만, 다른 부분에서 사용 되고 있지 않습니다.
멤버변수로 선언할 필요가 있을까요?

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      }
```suggestion
      Array(tryCount).fill(0).forEach(() => this.#moveForwardOnce());
```
이렇게 표현할 수 있겠네요!

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +  }
만약에 차랑의 전진조건이 바뀐다거나 여러 개의 전진조건이 필요하다면
이 부분에서 병목이 생기지 않을까요?
그렇다면 이 부분을 어떤 방식으로 작성해야 앞서 언급한 변화에 대응할 수 있을까요?

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      const isMoved = Math.floor(Math.random() * 10) >= CAR_PROGRESS_THRESHOLD;
여기서 10도 상수로 표현할 수 있을 것 같습니다.

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +  }
```suggestion
  #isCarNameLengthValid(cars) {
    return cars.every((name) => name.length >= RacingCar.MIN_LENGTH && name.length <= RacingCar.MAX_LENGTH);
  }
```
이렇게 아예 RacingCar 라는 class 내에 상수를 선언해줄 수 있지 않을까요?

2022-08-14 04:52 UTC, JunilHwang commented on src/js/RacingCar.js
> +      const isMoved = Math.floor(Math.random() * 10) >= CAR_PROGRESS_THRESHOLD;
앞선 내용 처럼 
```suggestion
      const isMoved = Math.floor(Math.random() * 10) >= RacingCar.THRESHOLD;
```
이렇게 표현해줄 수 있게 RacingCar에 상수를 선언해주면 어떨까요?

2022-08-14 04:52 UTC, JunilHwang commented on src/js/views/CarNameFormView.js
> +    this.buttonElement = $('#submit-car-name');
접근자로 만든다고 해서 옮길 이유는 없다고 생각합니다!
이 부분은 접근자라서가 아니라 DOM을 다루고 있기 때문에 Model로 옮길 필요는 더더욱 없을 것 같습니다.
그렇다고 Controller에 포함되기도 애매한 역할인 것 같아요!
제가 get으로 표현할 수 있다고 한 이유는, 굳이 생성자에서 멤버변수로 할당할 필요가 없다고 생각했기 때문입니다 ㅎㅎ

2022-08-15 05:00 UTC, merged