[클린코드 4기 방현경] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #130
Opened 2022-12-04 15:49 UTC by hyeonbang

에고.. .gitignore 파일을 커밋 전에 진작에 반영했어야 하는데 리뷰 하시는 데에 불편 끼쳐드려 죄송합니다..ㅠ!
----

안녕하세요 리뷰어님
자동차 경주 미션에 참가하게 된 방현경입니다.
잘부탁드립니다!

구조

한 StateService와 View를 각각의 Component 가 공유할 수 있는 MVC 패턴을 적용하였습니다.

StateService와 View를 Component에서 조작하고 있는 형태 입니다.
Custom Error를 구성하여 Validator.js에서 처리하고 있습니다.

개발에 필요한 공통 기능 사항(util.js)이나 상수 관리(const.js)는 Common 폴더에 묶어 관리하고 있습니다.

테스트 코드는 faker를 사용하여 랜덤 숫자와 랜덤 이름을 얻어 각 기능 테스트케이스에 적용하였습니다.

Component
NameComponent :: 자동차 이름을 등록하는 컴퍼넌트
RoundComponent :: 경주 횟수를 등록하는 컴퍼넌트
RaceComponent :: 자동차 경주를 운영하는 컴퍼넌트
컴퍼넌트는 추상화된 Component를 상속받아 각 기능별로 세가지로 구분하였습니다.

Service
StateService :: 각 컴퍼넌트 간의 간섭을 최대한 줄이기 위해 Proxy를 활용하여 공통된 데이터와 이벤트 공유를 할 수 있도록 구성했습니다.

Model
CarMdoel :: 자동차 경주에 개별적으로 쓰일 자동차를 클래스 모델로 구성하여 각 자동차의 루트를 얻고자 했습니다.

View
view는 최대한 추상적으로 작성하여 하나의 view를 사용할 수 있도록 했습니다.

질문사항

RaceComponent 의 경우 작성하고 보니 View를 조작하는 부분이 꽤 많아서 Controller의 역할에 대비하여 View의 비중이
많다고 느껴집니다. RaceView를 따로 작성하려 하는데 좋은 방안일까요?
새롭게 추가하려는 Dom요소를 selector.js에서 관리하고 있는데 ($car) 이렇게 추가되는 DOM에 값을 적용시켜주거나 변화를 줄 때 html로 파싱하는 과정이 꽤 번거롭다고 느껴졌는데, 혹시 더 스마트한 방법이 있을까요?

2022-12-06 16:43 UTC, jho2301 requested changes
안녕하세요 현경님
리뷰하게 된 전환오라고합니다 :bow:

코드를 보니 많은 시도를 해주신 것으로 보이네요
그럼에도 전반적으로 코드의 의도가 코드에 드러났던 것 같아요 👍 
리뷰 바탕으로 좀 더 개선해보신다면 더욱 합당한 코드가 나올 것 같은 기대가 있습니다

> RaceComponent 의 경우 작성하고 보니 View를 조작하는 부분이 꽤 많아서 Controller의 역할에 대비하여 View의 비중이 많다고 느껴집니다. RaceView를 따로 작성하려 하는데 좋은 방안일까요?

요 부분 코멘트에 남겨봤는데요. 자동차게임에서도 세부적인 도메인을 분리해보시면 더욱 깨끗한 코드를 작성하시는데 도움이 될 거에요. 자동차게임의 요구사항이 계속해서 늘어간다면, View와 Validator가 계속해서 커질테고 그렇게 된다면 지금 구조는 유지가 계속해서 어려워지지 않을까요?

> 새롭게 추가하려는 Dom요소를 selector.js에서 관리하고 있는데 ($car) 이렇게 추가되는 DOM에 값을 적용시켜주거나 변화를 줄 때 html로 파싱하는 과정이 꽤 번거롭다고 느껴졌는데, 혹시 더 스마트한 방법이 있을까요?

아마도? jsx에 익숙하셔서 html을 파싱해야한다고 생각하셨을 수도 있을 것 같습니다.
 js에서 html을 파싱의 대상으로 본다면 많이 힘든게 맞을 거에요. 
대신 dom api를 적극적으로 활용해보시면 어떨까요?
적절하게 요소를 선택하고, 속성을 조정해보는 연습을 통해 vanilla js 에 익숙해져보는 것도 이번 과정에서 얻어가실 수 있는 부분이라고 생각합니다.

2022-12-06 16:43 UTC, jho2301 commented on src/js/app.js
> +        const race = new RaceComponent(this.container);
컴포넌트로 view, validator, state를 전달하고 있네요.
이렇게 함으로써 어떤 부분에서 이득을 얻을 수 있다고 생각하셨나요?

저는 view와 validator는 조합을 통해 각자 컴포넌트 클래스가 사용해도 될 것 같다는 생각이 들었어요.
1. 각 컴포넌트 클래스에서 필요한 특정 view와 validator 메서드가 있을 것인데, 이를 App이 알아야하는 이유가 있을지
2. 앱의 복잡도가 높아지고 규모가 커져감에 따라, View와 Validator 클래스가 쉽게 비대해지진 않을지

요정도 생각해보시면 어떨까 합니다

2022-12-06 16:43 UTC, jho2301 commented on src/js/common/error.js
> +}
```suggestion
export class InputOutOfRangeError extends CustomError {
    constructor(message) {
        super(message, 'InputOutOfRangeError');
    }
    
    static isInputOutOfRangeError(error) {
      return error?.name === 'InputOutOfRangeError'
     } 
}
```

인스턴스가 해당 커스텀에러인지 검증하는 스태틱 메서드가 있어도 좋을 것 같아요

2022-12-06 16:43 UTC, jho2301 commented on src/js/common/error.js
> +}
에러타입이 한 개씩 늘때마다 클래스가 계속 늘어날 것 같은데, CustomError를 모든 에러케이스에 활용해보면 어떨까요?

2022-12-06 16:43 UTC, jho2301 commented on src/js/common/error.js
> +    InputMinInsufficient: `레이싱 횟수는 ${MIN_ROUND}이상이어야 합니다.`
상수를 적절하게 활용해주셨네요

2022-12-06 16:43 UTC, jho2301 commented on src/js/common/util.js
> +export const deepCopy = (item) => JSON.parse(JSON.stringify(item));
View클래스와 해당 유틸 모듈의 역할적 차이가 있을까요? 
사실 View도 함수들을 모아놓은 모듈으로 사용해볼 수 있지 않을까요

2022-12-06 16:43 UTC, jho2301 commented on src/js/common/validator.js
> +    }
constructor는 별도로 동작을 정의하지 않는다면 생략해도 됩니다

2022-12-06 16:43 UTC, jho2301 commented on src/js/components/component.js
> +    _submit() {}
이렇게 특정 컴포넌트에서 사용되는 메서드는 일반적으로 사용되는 Component의 추상메서드로는 적합하지 않아보여요

2022-12-06 16:43 UTC, jho2301 commented on src/js/components/nameComponent.js
> +    }
부모컴포넌트에 constructor에서 _init을 호출해도 자식컴포넌트에서 오버라이드한 메서드가 호출될거에요. 
다만 this가 부모컴포넌트를 가리키기때문에 this 사용이 좀 까다로워지긴 합니다

2022-12-06 16:43 UTC, jho2301 commented on src/js/components/nameComponent.js
> +    }
요런 경우는 굳이 선언해줄 필요가 없어보여요

2022-12-06 16:43 UTC, jho2301 commented on src/js/models/car.model.js
> +        return random > 3 ? RACETYPE.FORWARD : RACETYPE.STOP;
0, 9 ,3 도 상수화를 해서 이름에 의미를 부여해줘도 좋을 것 같아요

2022-12-06 16:58 UTC, jho2301 commented on src/js/app.js
> +        const race = new RaceComponent(this.container);
전역상태 역시 싱글턴패턴을 적용해보셔도 좋을 것 같네요.

2022-12-08 05:15 UTC, hyeonbang commented on src/js/app.js
> +            stateService: stateService()
상태관리서비스에 대해서는 각 클래스 간의 데이터를 공유하고 상태를 관리해주는 것으로 재사용이 목적이 아니라고 판단하여 함수로 구현하였는데 구조의 일관성으로 볼 때는 조금 맞지 않을 수도 있을 것 같네요..!

2022-12-08 10:32 UTC, hyeonbang commented on src/js/common/util.js
> +export const deepCopy = (item) => JSON.parse(JSON.stringify(item));
view를 제어하는 부분으로서 View 클래스를 만들었는데, 사실상 의미가 모호해지는 것 같네요.. 함수 모듈로 변경을 해보겠습니다!

2022-12-08 11:35 UTC, hyeonbang commented on src/js/app.js
> +        const race = new RaceComponent(this.container);
View는 유틸모듈로 합치고 Validator는 각 Component에서 작업해주는 형태로 변경하고 싱글턴패턴.. ! 한번 시도해보도록 하겠습니다

2022-12-08 11:44 UTC, hyeonbang commented on src/js/common/error.js
> +}
에러 클래스를 생성할 때 customError를 extends하여 생성하고 있는데 이 방식말고 또 다르게 활용할 수 있는 방법이 있는걸까요? ㅠㅜ 제가 질문을 이해를 못한 것 같습니다ㅠ

2022-12-11 18:10 UTC, jho2301 commented on src/js/common/error.js
> +}
constructor로 에러타입이나 name을 전달해줄 수도 있을 것 같아요

2022-12-11 18:12 UTC, jho2301 commented on src/js/common/util.js
>  export const getRandom = (min, max) => Math.floor((Math.random() * (max - min + 1)) + min);
와 되게 상세히 적어주셨네요 🔥 🔥 🔥

2022-12-11 18:15 UTC, jho2301 commented on src/js/components/nameComponent.js
> +    }
제한적으로 사용되고있어서 큰 문제는 없어보이지만
validation을 분리하게된다거나 에러핸들링이 컨트롤러내에서도 달라진다면 try catch를 validation 메서드 바깥으로 분리해볼 수 있을거에요

2022-12-11 18:16 UTC, jho2301 commented on src/js/components/roundComponent.js
> +            }
불필요한 else는 되도록 제거하는게 깔끔한 코드작성에 도움이됩니다
```js
       if (!e instanceof CustomError) {
             throw e;
            } 
            
               alert(e.message);
            ```

2022-12-11 18:18 UTC, jho2301 approved these changes
고쳐주신부분 잘 확인했습니다 현경님! 
다음 스텝도 화이팅입니다!

2022-12-11 23:52 UTC, merged