[클린코드 4기 이근휘] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #134
Opened 2022-12-06 15:53 UTC by Geuni620

안녕하세요 리뷰어님!
자동차 경주 Step1 미션을 진행하게 된 이근휘라고 합니다 🙇‍♂️

구현하게 된 미션이 저에겐 너무 어렵게 느껴져서 이전 기수분들의 코드를 많이 참고했습니다.
구현을 완료하고나서도, 이해가 잘 가지않고 에러가 많이 나서 싹 지우고 처음부터 다시 구현하느라 조금,,, 늦었습니다 🥲
늦게나마 리뷰요청을 드립니다.

기능구현을 하면서 중점적으로 생각했던 건 이전 리뷰 때 받았던 최대한 N회 렌더링을 없애려고 했고, MVC 패턴을 따라해보려고 했습니다.
부족한 부분이 많습니다. 아낌없는 지적과 조언 부탁드립니다 🙏
감사합니다! 

### 궁금한 점
다음과 같은 랜덤값을 테스트할 수 있는 방법이 있을까요? 키워드라도 알려주시면 찾아보겠습니다!

ex) 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.

2022-12-07 20:26 UTC, EungyuCho requested changes
안녕하세요 근휘님~

MVC패턴으로 구현해주셨네요..! 네이밍의 문제도 있고 각 역할에 맞지 않게 배치된 함수들도 있어서 한번 쭉 리팩터링을 해보면 좋을 것 같아요. 그런데 확인해보니 Step1 요구사항만 포함되어 있을 줄 알았는데 다음 스텝도 섞여서 구현이 되어있네요 😢 
다음 미션에서는 Step별로 요구사항을 지켜가며 구현해보는걸 권장드려요!

질문사항
> 다음과 같은 랜덤값을 테스트할 수 있는 방법이 있을까요? 키워드라도 알려주시면 찾아보겠습니다!

cypress가 sinon을 기반으로 spy와 stub이 동작하는걸로 알고있어서 이 [페이지](https://stackoverflow.com/questions/17011765/stubbing-date-now-and-math-random)대로 하면 가능할수도 있어보여요 👀 (저도 하도 예전에 시도를 해봤어서 성공했었는진 가물가물하네요 🤔 ) 

Step1 첫 리뷰 요청까지 작업하시느라 고생하셨고 한번 깔끔하게 개선해봅시다 :)
구현하시느라 정말 고생많으셨어요 👏

2022-12-07 20:26 UTC, EungyuCho commented on src/js/view.js
> +};
요것은 view 파일에 있을만한 로직이 아닌 것 같습니다

2022-12-10 09:22 UTC, Geuni620 commented
안녕하세요 은규님!
정성스런 리뷰 정말 감사합니다!

스탭 범위를 넘게 구현한 줄은 몰랐어요,,, 다음 스탭 미션내용을 확인하고 알았답니다 🥲
다음 미션 내용도 확인하면서 구현하도록 할게요 감사해요 🙏

수정하면서 궁금한 사항은 다시 댓글을 남겨놓았습니다!
이번에도  아낌없는 지적과 조언 부탁드립니다 :)

2022-12-10 09:24 UTC, Geuni620 commented on cypress/e2e/racing.cy.js
> +      // when
when을 어떻게 작성해야할지 몰라서 비워두었습니다.
고민해보고 다시 작성해볼게요!

2022-12-10 15:51 UTC, EungyuCho commented on src/js/utils/index.js
> +export const $$ = (selector) => document.querySelectorAll(selector);
맞습니다 ㅎㅎ
이해하기 쉽게 객체형식으로 받는게 좋아보여요
selector은 필수로 element는 optional 하게 하고 document로 해두는게 좋아보입니다 :)

2022-12-10 15:52 UTC, EungyuCho commented on src/js/controller.js
> +    handleCarViewAndRace(
사실 저도 막상 코딩을 할 때 뒤돌아보면 이상했던 네이밍이 많더라구요
주기적인 리팩터링이나 코드리뷰가 그래서 꼭 필요한 것 같아요 😄

2022-12-10 15:57 UTC, EungyuCho commented on src/js/view.js
> +};
view에서는 화면을 어떻게 변경할지만 정의해두고 controller에서 상태를 보고 view에 ~ 방식으로 화면을 변경해달라고 요청하는게 깔끔하다고 생각해요.

view에서 전진 조건을 확인하고 racingCar의 forward를 하는 등의 역할도 view가 하고있는게 애매한 것 같다고 느꼈어요.

service에서 조건과 전진시키는 역할을 동작시키고 controller에 전진한 차의 index를 가지고 있으면 view가 온전히 화면을 조작하는것에만 집중할 수 있다고 봅니다 👀

2022-12-10 16:22 UTC, EungyuCho approved these changes
근휘님 안녕하세요 ㅎㅎ

피드백 모두 잘 반영해주셨네요! 추가로 질문주신 부분과 추가적으로 소소한 코멘트를 남겨봤어요.
나중에 확인해주시고 다음 스텝에서 반영해주시면 되겠습니다 ^.^

추가로 어려운 부분이 또 있으시면 코멘트나 4기 리뷰어채널, DM 모두 좋으니 남겨주세요!
그리고 Step2의 미션 범위가 너무 적어 한 PR에 올리기 애매하다면 PR을 제출해주실 때 Step2 & Step3으로 제출해주셔도 됩니다~

Step1 마무리하시느라 고생하셨어요~

2022-12-10 16:22 UTC, EungyuCho commented on src/js/model/validation.js
> +    .filter((name) => name.trim().length >= CAR.NAME_MAX_LENGTH).length;
(마이너) 보통 프로젝트 단위가 커지면 이런 조건을 체크하는 함수들의 컨벤션도 통일하고 싶은 니즈가 있는데 저는 이렇게 사용해요!
```suggestion
    .filter((name) => Validator.isLengthOver(name, NAME_MAX_LENGTH).length
```

2022-12-10 16:22 UTC, EungyuCho commented on src/js/model/validation.js
> +    .filter((name) => name.trim().length >= CAR.NAME_MAX_LENGTH).length;
nameErrors로 배열로 받는것보다 에러가 1개라도 있는지 검사하는게 목적이니 이렇게 작성해보면 어떨까요?
```suggestion
  const isCarValidationValid = namesArr
    .split(",")
    .filter((name) => name.trim().length >= CAR.NAME_MAX_LENGTH).length === 0;
  
  return isCarValidationValid;
```

2022-12-10 16:22 UTC, merged