[클린코드 4기 윤다솜] 자동차 경주 미션 STEP 2
next-step/js-racingcar pull request #135
Opened 2022-12-07 08:54 UTC by datoybi

[배포 링크](https://datoybi.github.io/js-racingcar/)

준일님 안녕하세요!
추천해주신 영상 보면서 역할과 책임의 중요성과 추상화 기법, 
도메인과 관련없는 객체들을 왜 분리해야 하는지 알 수 있었습니다. 감사합니다
(그런데 직접 구현할 때 역할과 책임을 잘 분리하는 건 정말 정말 어려운 것 같습니다,,🥲)
 
그리고 step1에서 남겨주신 피드백을 곰곰히 생각해보았는데요.
> 전진 조건이 5개가 있으며, 게임이 시작될 때 전진조건이 랜덤으로 정해진다" 라는 요구사항이 있다면 어떻게 해야 좋을까요?
> 만약에 전진 조건 자체를 사용자가 조합해서 제공한다고 하면 또 어떻게 될까요?

이런 요구사항이 있다면 여러가지 전진 조건 함수들을 담아놓을 메서드를 만든다?
사용자가 조합 한 전진 조건 함수들을 담아 둘 함수를 만들고 전진 조건들을 담은 뒤 그 함수를 실행시킨다?? 
밖에 안떠오릅니다.. 말씀하신게 이런 방향이 맞을까요? 계속 붙잡고 있는다고 답이 나오지 않을것 같아 PR 합니다.

부족하지만, 건설적인 피드백 부탁드립니다

감사합니다.
 
---
## 🎯 Step 2
- [x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.
- [x] 우승자가 여러명일 경우 ,를 이용하여 구분한다.
- [x] 다시 시작 하기 버튼을 누르면 다시 시작한다.

2022-12-07 14:58 UTC, JunilHwang requested changes
안녕하세요 다솜님!
Step2 잘 진행해주셨네요 👏👏👏

> 전진 조건이 5개가 있으며, 게임이 시작될 때 전진조건이 랜덤으로 정해진다" 라는 요구사항이 있다면 어떻게 해야 좋을까요? 만약에 전진 조건 자체를 사용자가 조합해서 제공한다고 하면 또 어떻게 될까요?

전진 조건에 대한 interface를 정의하고, 자동차가 움직여야 할 때 (예시: goCondition) 해당 interface에 대한 구현체를 만들어서 건내주면 어떨까요?
(이런 것을 전략패턴이라고 이야기 한답니다!)

보통 게임에 이와 유사한 패턴이 많이 사용된답니다.
가령, 메이플 스토리의 장비창을 떠올려보세요! 장비창을 내가 만든다고 한다면 어떻게 해야 좋을까요?

그리고 지금 `racingCar` 라는 파일이 `racingManager`를 `export default`로 내보내고 있습니다. 이럴 때는 파일 이름과 일치시켜주는게 좋지 않을까요? 다솜님은 코드 작성자니까 헷갈리지 않을 수 있으나, 다른 사람이 `racingManager`라는 코드를 탐색할 때 힘들 수 있어요!

이 외에도 자잘한 피드백 남겼으니 확인 부탁드립니다 😁
궁금한점 있으면 코멘트로 남겨주셔도 좋고, 혹은 슬랙 채널에 올려주시면 더 좋아요!

2022-12-07 14:58 UTC, JunilHwang commented on cypress/e2e/racingcar.cy.js
> +    });
지금은 BMW만 있어서 가능한 테스트 같아요!
만약 여러 개의 자동차가 있을 때 우승자를 예측할 수 있도록 하려면 어떻게 해야 좋을까요!?

2022-12-07 14:58 UTC, JunilHwang commented on index.js
> +};
jsdoc으로 문제를 해결하셨네요!
jsdoc을 사용하지 않고 해결할 수 있는 방법은 없을까요?

2022-12-07 14:58 UTC, JunilHwang commented on index.js
> +};
근데 여기에 선언된 racingManager는 다른 곳에서는 사용되고 있지 않고 있어요!
타입 때문에 정의한거라면, jsdoc을 실제 코드가 선언된 곳으로 옮겨도 무방하지 않을까요?

2022-12-07 14:58 UTC, JunilHwang commented on src/js/model/racingcar.js
>    gameResult: [],
만약 racingManager가 여러 개라면 어떨까요?

가령 5개의 게임 규칙이 있고
한 번에 5개의 게임을 실행한다고 생각해보면 좋을 것 같아요!

2022-12-07 14:58 UTC, JunilHwang commented on src/js/model/racingcar.js
> +  },
상수는 일부로 제거하신걸까요?
이건 제가 드린 피드백이 제대로 전달되지 않은 것 같네요 ㅠㅠ
상수를 사용하되, 상수의 선언을 이 파일 내에 해놓으면 어떨까 하는 이야기였습니다!
어차피 이 파일 내에서만 사용되니까요 ㅎㅎ

2022-12-07 14:58 UTC, JunilHwang commented on src/js/model/racingcar.js
>  export default racingManager;
지금 racingManager가 너무 많은 일을 하고 있는 것 같아요!
역할별로 나눠보면 어떨까요?

- 자동차 이름
- 자동차
- 자동차 경주
- 경주 규칙

지금 추출할 수 있는 역할(도메인)은 이정도인 것 같네요!

2022-12-07 14:58 UTC, JunilHwang commented on src/js/validate/validate.js
> +export const getType = target => Object.prototype.toString.call(target).slice(8, -1);
여기서 쓰이는 8과 -1은 어떤 의미인걸까요?

2022-12-07 14:58 UTC, JunilHwang commented on src/js/validate/validate.js
> +export const getType = target => Object.prototype.toString.call(target).slice(8, -1);
그리고 `target.toString().slice(8, -1)` 처럼 사용해도 똑같지 않을까요? prototype을 가져와서 사용하는 이유가 있나요?

2022-12-07 14:58 UTC, JunilHwang commented on src/js/view/main.js
> +};
이 코드는 view라고 보기 힘들 것 같아요!
다른 것들은 ui를 표현하는데 이건 경고차를 띄우는거라서,
이게 view가 되려면 alert 대신에 alert 역할을 하는 ui 같은게 있어야 하지 않을까요?

그래서 이 코드는 아예 별도의 파일로 분리해서 관리하는게 좋을 것 같아요!

2022-12-07 14:58 UTC, JunilHwang commented on src/js/model/racingcar.js
> +import { catchMessage, getType } from '../validate/validate.js';
지금 catchMessage는 결국 alertIfError를 그대로 호출하고 있고, catchMessage가 model에서 쓰이고 있습니다.

만약에 이 model이 nodejs 환경에서 실행된다고 치면 오류가 발생하지 않을까요?
자동차 경주 게임을 브라우저가 아닌 nodejs의 커맨드라인으로 구현한다고 생각했을 때,
지금 작성된 모델을 활용한다고 가정한다면, 이 모델이 정상적으로 동작할까요?

혹은 React Native로 구현한다고 가정한다면?

2022-12-07 14:58 UTC, JunilHwang commented on src/js/model/racingcar.js
>    },
```suggestion
  goCondition(gameStrategy) {
    return gameStrategy();
  },
```

이렇게 자동차의 전진 조건을 아예 주입 받는다고 가정해보면 어떨까요?

이럴 경우 racingManager는 gameStrategy의 interface만 알고 있다면 테스트하기 쉬운 코드가 되지 않을까요?

2022-12-14 08:48 UTC, datoybi commented on cypress/e2e/racingcar.cy.js
> +    });
가장 많이 움직인 값을 가져와서, max로 움직인 차 이름과 우승자 란에 표출되는 이름을 비교하는 방식으로 바꿨습니다.! https://github.com/next-step/js-racingcar/pull/135/commits/2e4d6ef89325026110b5d71c895f55252b609f9a

2022-12-14 08:52 UTC, datoybi commented on src/js/model/racingcar.js
>    gameResult: [],
재사용성을 고려하여 class로 바꿨습니다. https://github.com/next-step/js-racingcar/pull/135/commits/de949c71bc109c928284983ab2f6aa2c44a8adff

2022-12-14 08:54 UTC, datoybi commented on src/js/model/racingcar.js
> +  },
앗..! 제가 잘못 읽었나봅니다..ㅎㅎㅎ수정했습니다 https://github.com/next-step/js-racingcar/pull/135/commits/f4ae87bcc4cc282b6f2961801c0dc5cf88698689

2022-12-14 08:56 UTC, datoybi commented on src/js/validate/validate.js
> +export const getType = target => Object.prototype.toString.call(target).slice(8, -1);
아래에서 타입 체크를 하는 걸 참고했습니다
https://poiemaweb.com/js-type-check

```
console.log(Object.prototype.toString()); // "[object Object]"
console.log(Object.toString()); // "function Object() { [native code] }"
```
결과값이 이러해서 prototype을 사용하였고.. 8, -1은 <b>[object</b> 와 <b>]</b>를 자르기 위해 사용했습니다

2022-12-14 09:08 UTC, datoybi commented on src/js/model/racingcar.js
> +import { catchMessage, getType } from '../validate/validate.js';
alertIfError를 그대로 호출하면 window.alert() 때문에 nodejs의 커멘드 라인으로 구현할때나 React native로 구현한다고 가정했을 때 에러가 난다는 말일까요..!?
그렇다면.. catchMessage에서 type이라는 인자를 넘겨주어 window면 alert을 하고, nodejs면 console.log로 찍고.. 이런식으로 구현 하는걸로 바꿔보았습니다.🤔 https://github.com/next-step/js-racingcar/pull/135/commits/2f6de2961a58e74846ced7208d08744b4a843f5a

2022-12-19 00:33 UTC, datoybi commented
준일님 안녕하세요! 
리뷰에 대한 부분 최대한 고민하면서 적용해보았습니다.
피드백 받으며 확장성을 염두해두고 생각하는게 아직은 많이 부족한 것 같다는 생각을 했네요ㅎㅎ

### 궁금한 점
<b>object의 data type을 보장할 수 있는 방법</b>
타입을 체크하는 것 외에.. 어떻게 협업하는 분께 데이터 타입을 알려줄 수 있을까요?? jsdoc을 사용하는 것 외에 열심히 구글링했으나 다른 방법을 발견하지 못했습니다

나머지는 리뷰별로 코멘트 달았습니다.  재리뷰 부탁드립니다!
감사합니다.

2022-12-19 13:52 UTC, JunilHwang commented on src/js/model/racingcar.js
> +import { catchMessage, getType } from '../validate/validate.js';
음... 이건 적절한 해결방법이 아닌 것 같아요 ㅠㅠ

2022-12-19 14:14 UTC, JunilHwang approved these changes
안녕하세요 다솜님!
피드백 잘 반영해주셨네요 👏👏

Step2는 일단 여기서 마무리하도록 하겠습니다.

그리고 질문에 대해 답변을 드리자면,

> object의 data type을 보장할 수 있는 방법 -> 타입을 체크하는 것 외에.. 어떻게 협업하는 분께 데이터 타입을 알려주고 해당 타입이외의 변경이 일어나는 것을 방지 할 수 있을까요?? jsdoc을 사용하는 것 외에 다른 방법을 발견하지 못했습니다🥺

이럴 때 필요한게 class입니다.

```js
const invalidCarName = new CarName('123456'); // 생성 과정에서 에러 발생
const validCarName = new CarName('12345'); // 정상적으로 생성
console.log(validCarName.value); // 12345 출력
```
이렇게 CarName 자체에서 검증로직을 가지고 있다면, CarName으로 생성된 값들은 정상적인 값이라고 보장할 수 있는거죠 ㅎㅎ

그리고 이 때 set이 있으면 당연히 안되겠죠!?
```js
// 1. value를 set할 경우 오류가 발생하도록 하거나
// 2. value를 set 해도 아무 일도 일어나지 않거나
validCarName.value = 123456;
```
위와 같이 하기 위해선 어떻게 해줘야할까요?

이 외에도 고민해볼 부분들에 대해 피드백 남겨놨으니 Step3 진행하면서 확인 부탁드립니다 🙏

2022-12-19 14:14 UTC, JunilHwang commented on src/js/service/carName.js
> +  }),
throw를 catch하는 코드가 ui(view)에 있어야 하지 않을까요?
그러면 브라우저 종속성에 대한 부분도 자연스럽게 해소될 것 같아요~

2022-12-19 14:14 UTC, JunilHwang commented on src/js/validate/validate.js
>  };
앞선 내용을 참고해주세요!

2022-12-19 14:14 UTC, JunilHwang commented on src/js/validate/validate.js
> +export const getType = target => Object.prototype.toString.call(target).slice(sliceBegin, sliceEnd);
getType이라는 네이밍은 너무 포괄적인 것 같아요! 더 구체적으로 이름을 지어주면 어떨까요?

2022-12-19 14:14 UTC, merged