[클린코드 4기 이상훈] 자동차 경주 미션 STEP 2
next-step/js-racingcar pull request #139
Opened 2022-12-09 14:44 UTC by sanghunlee-711

안녕하세요 인성님! 자동차 경주 두번째 단계를 진행하였습니다! 

요구한 기능 사항을 모두 완료했으나 stub이 제 의도와 같이 작동하지 않아 완벽히 스텝을 진행했다고 생각이 들지는 않습니다.

지난번 리뷰를 통해 많이 생각하며 이것저것 적용해보고 리뷰를 참고하며 바꿔보려는 노력을 좀 해보았습니다 ㅎㅎㅎ..

제 딴애는 나름의 스토어(?)..를 만들어 보았으나 이럴거면 Proxy를 쓰는게 나을수도 있겠다라는 생각이 듭니다.

나름의 주석으로 설명을 달아놓았으나 좋은 아이디어가 있으시다면 조언 부탁드리겠습니다 :)

아래 질문사항 참고해주셔서 리뷰해주시면 감사드리겠습니다 :)

해피해피 주말 보내시길 바랍니다!

## 질문
**1. caller, callee를 대체할만한 메서드가 없을까요?**

현재 스토어 구현은 간단하게 getState를 할때 이름과 this를 억지로 받아와 렌더를 할 컴포넌트들을 임의로 저장해놓는 방식입니다!
그러다 보니 코드가 다소 별로라는 인상이 들어서 이것저것 찾아보았을때 제가 가장 이상적으로 접근할 수 있는 메서드가 caller, callee등의 키워드 였으나.. strict mode에서는 Eval 등의 위험으로 막아놓은 것 같습니다.

아마도 알 수 없는곳에서 다른 클래스, 메서드 등의 this에 접근하는 위험한 상황을 막기위해 설정한 것이라고 유추하고 있습니다만.. 욕심이 생기네요 🥲

**2. stub이 작동하질 않습니다.**
```javascript
import utils from '../../src/js/utils/index.js';
// ...
  cy.stub(utils, 'getProgressOrNot', () => {
    return false;
  });
// ...테스트 코드
```
와 같은 진행에서 테스트코드 부분에서 특정 이벤트후에 콜백으로 getProgressOrNot이 불리고 있어 이를 통해 모킹을 시도해보았으나 간헐적으로 proxy로 콘솔에 찍히는 것을 확인하였습니다. 물론 원하는 테스트 결과와 원하는 값으로 반환을 해주지 않고 있습니다.

제가 무언가 잘못 접근한 것인지.. 자료를 찾아봐도 작성방법에는 문제가 없는 것 같다고 생각이 듭니다. 혹시 비슷한 사례를 겪으셨다가 해결하신 적이 있으시면 공유 부탁드리겠습니다!

**3. 해당 리뷰에 대하여 고민 해보았으나 더 좋은 방법이 딱히 떠오르질 않습니다 😅**
https://github.com/next-step/js-racingcar/pull/127#discussion_r1039479511
이벤트 맵을 store처럼 관리하라는 말씀이 클래스를 별도로 따서 사용하는게 좋을 것 같다는 의견이신지 .. store처럼 이벤트맵을 관리한다는 의미에 어떤 방법으로 접근할 수 있을지에 대해 힌트가 더 필요할 것 같습니다!

🎯 1단계 요구사항
- [x] 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [x] 자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- [x] 사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [ ] 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.(기능완료, 테스트 미 동작)
- [ ] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다. (기능완료, 테스트 미 동작)
- [ ] 우승자가 여러명일 경우 ,를 이용하여 구분한다. (기능완료, 테스트 미 동작)

2022-12-11 14:42 UTC, InSeong-So requested changes
상훈님, 안녕하세요. 리뷰어 소인성입니다.

> 1. caller, callee를 대체할만한 메서드가 없을까요?
현재 스토어 구현은 간단하게 getState를 할때 이름과 this를 억지로 받아와 렌더를 할 컴포넌트들을 임의로 저장해놓는 방식입니다!
그러다 보니 코드가 다소 별로라는 인상이 들어서 이것저것 찾아보았을때 제가 가장 이상적으로 접근할 수 있는 메서드가 caller, callee등의 키워드 였으나.. strict mode에서는 Eval 등의 위험으로 막아놓은 것 같습니다.
- caller, callee를 쓰게 된 계기가 무엇일까요? 이번에 상훈님 코드를 보면서 의문이었던 것은, 왜 store의 상태에 각 컴포넌트의 **인스턴스**를 저장하는가 였습니다. this를 억지로 받아와 렌더를 할 컴포넌트를 저장하셨다고 했는데, 과연 이게 현재 구현된 Component 클래스의 라이프사이클을 활용하거나 observable를 활용하는 수단이 맞을까요?
- caller, callee는 현재 오픈소스나 자바스크립트로 구성된 구식 라이브러리를 뒤져보아도 그 활용처가 많지 않은, deprecated 되었거나 위험하기 때문에 사용을 지양하는 메서드입니다. call, apply, bind 함수도 사용되지 않고 있죠. 상훈님이 생각하는 "대체할만한" 이라는 뜻이 기능을 대체한다는 의미라면 caller, callee를 사용하지 않아도 되게끔 아예 구현을 다르게 가져가봤으면 좋겠습니다.

> 2. stub이 작동하질 않습니다.
- 이 내용은 코멘트에 남겨드렸으니 확인해주세요. 이 부분의 테스트는 유저 액션만을 바라보기 때문에 랜덤 값에 따라 차가 이동한다라는 비즈니스 로직의 테스트가 불가능합니다.

> 3. 해당 리뷰에 대하여 고민 해보았으나 더 좋은 방법이 딱히 떠오르질 않습니다 😅
- 상수란 그 어떤 상황에도 불변인 값입니다. EVENT_MAP은 상수 파일에 선언되었음에도 전역에서 참조 및 수정이 가능한 형태고, key-value가 set/get 될 때 유효성을 검사하지 않고 단순히 호출 및 저장만 진행하고 있습니다. 그렇다면 상수로 저장하는 것이 옳을까요?
- 또한 EVENT_MAP의 상수는 호출되어 실행되면 반드시 부수효과를 일으키게 됩니다. 그렇다면 유틸리티도 아닌 비즈니스 로직에 해당되며, 이벤트만을 관리하는 event-store 등의 관계를 이야기한 것입니다.

<br />

이번에 코드를 보면서 상훈님의 많은 시도를 보았으나... 아쉬움이 큽니다.

1. 스탭 1 때 드렸던 코멘트는 많이 반영되지 않은 것 같네요. 저는 이 과정이 TDD를 활용한 클린 코드이기 때문에 TDD를 활용하여 리팩토링/개발 시 및 빠르게 검증 가능하고, 코드를 깔끔하게 작성하여 가독성이 좋고 불필요한 의존성이 최대한 제거된 앱을 만드는 경험을 가져가야 한다고 생각합니다.
    - 테스트를 너무 잘 작성해주시고 Unit 테스트까지 만들어 확인하신 부분은 정말 대단하고 좋은 시도이나 그렇다고 "모든 팀원이 이해하기 쉽도록 작성되었느냐"에 대한 물음에는 사실 아리송해요.
    - 네이밍, 블록 스코프, tab/space, 개행 문자, for-loop, if-else, class 작성법 등 정말 간단한 코드 스타일임에도 구글, airbnb, 여러 IT 대기업이 컨벤션을 만들고 교육하고 배포하는 것은 이유가 있는 일이죠.

2. 저는 상훈님이 기능 구현을 깊이 가져가서 여러 패턴을 적용하는 경험을 하고 계시다면 너무 찬성이지만, 현재 코드는 다른 개발자들이 작성하거나 예제로 적어둔 코드를 너무 copy-paste한 느낌이 강합니다. 템플릿 메서드 패턴, 옵저버 패턴, 구독-발행 패턴, Proxy 패턴 등 하나의 구현 방법도 깊이 이해하고 사용하기 어려운데 일단 차용하고 이슈가 생기거나 해당 코드 부터 내용을 확장하는 듯 합니다. 그렇기 때문에 caller 등의 기법을 사용하게 된 것 같아요.

3. 결합도를 생각해보자면, 사실 store와 component 들은 한몸인 상태입니다. 쉽게 생각해보면 store의 상태를 가져다 사용하는게 컴포넌트들인데, store의 상태에 접근할때는 컴포넌트의 인스턴스(this)를 넘겨야 하는 상황이죠. store란 무엇일까요? 무엇이 store라는 역할을 필요로 하게 했을까요? 또, 컴포넌트는 무엇일까요?

4. utils/index.js 는 유틸리티로 생각되는 함수의 집합이라 생각했는데, 도메인에 종속된 비즈니스 로직이 혼재되어 있습니다. 이것은 도메인이란 무엇일까?에 대해 생각해볼 여지를 주는 부분입니다.

5. 상훈님의 앱은 어떤 소프트웨어 설계 패턴을 적용하셨을까요? MVC일까요, MVVM일까요? 둘 다 아니라면, 어떤 부분을 고민하고 문제를 해결하기 위해 컴포넌트 클래스와 store 등을 적용하신 걸까요?

저는 이번에 최대한 많이 상훈님과 피드백을 주고 받고 싶습니다. 제 의견이 잘못되었다 생각되면 꼭 말씀해주시고, 궁금한 부분이 있다면 반드시 질문해주세요. 새로운 기능을 구현하는 것은 너무나 즐겁고 신나는 일입니다. 반면 내가 작성했던 내용을 다시 읽고 흐름을 정리한 뒤 수정하는 리팩토링은 귀찮고 번거로운 일이죠. 하지만 꼭 거쳐가야 하는 일입니다. 우리가 미래에 더 좋은 코드, 더 견고한 앱, 더 나은 시니어가 되기 위해서는 내가 짜는 코드에 정당성이 있고 의도한 바가 명확해야합니다.

우선 리뷰한 내용을 확인해주시고, 다시 리뷰 요청 주시면 감사하겠습니다.

2022-12-11 15:00 UTC, sanghunlee-711 commented on cypress/e2e/racingcar.cy.js
>  describe('레이싱카 사이트 E2E 테스트', () => {
:)

2022-12-11 15:06 UTC, sanghunlee-711 commented on cypress/e2e/racingcar.cy.js
> +      });
submitTrial이후 Trial 컴포넌트에서는 `componentUpdated` 가 호출 됩니다. 그로 인해 내부 코드 중 `makeNewRacingMap`이 호출되며 그 내부에 `getProgressOrNot`이라는 유틸이 `racingMap`을 호출 길이를 맞출 수 있을때 까지 호출이 되는 상태입니다.

코드 상의 위치가 인성님의 말처럼 반복컨텍스트로 확인하는 것이 아니므로 질문이 이상한 것 같아 다시 수정해서 질문을 드린다면 stub이 정상작동한다면 최소 한번의 `expect(utils.getProgressOrNot).to.be.called` 는 통과가 되어야하는 것으로 판단이 되나 그렇지 않아 질문을 드려봅니다.

```javascript
      cy.stub(utils, 'getProgressOrNot', () => {
        return true;
      });
      cy.submitCarNames(CAR_NAME.DIVERSE_CAR_NAME.join(','));
      cy.submitTrial(MOVE_NUMBER);
      expect(utils.getProgressOrNot).to.be.called; //에러가 나지 않아할 것으로 유추
      
      cy.wait(WAITING_TIME * MOVE_NUMBER).then(() => {

       cy.get($element.forwardIcon).should(
          'have.length',
          MOVE_NUMBER * CAR_NAME.DIVERSE_CAR_NAME.length
        );
      });
```

2022-12-11 15:25 UTC, sanghunlee-711 commented on cypress/support/commands.js
> +  cy.get($element.moveSubmitButton).should('be.disabled');
세부적으로 호출에 대한 이야기라면 class내부의 **메서드가 엘리먼트의 이벤트에 따라 실제로 호출이 되고 있는가에 대한 테스트를 E2E 테스트에서도 진행하는 것이 필요하다** 라고보시는것으로 이해하면 되는 것일까요? 맞다고 보신다면 왜 그렇게 생각하는지 의견이 궁금합니다.

저희가 프로젝트 진행중 E2E테스트 만을 진행하고 있어 조금 다른 관점의 이야기인 것 같습니다만.. 제가 이해한 E2E테스트는 유저가 어떤 행위를 하였을때 UI상에 어떠한 변화가 일어나는지에 대한 테스트를 하는 것으로 이해를 하고 진행 해 왔습니다.

하지만 여기서 `내부 메서드가 어떻게 호출되는가?` 에 대한 부분은 유저가 굳이 알아야 하는 요소인가에 대한 의문이 듭니다.

차라리 더 하위 레벨의 테스트를 따로 분리하여 진행하는 것이 좋지 않을까요?

예를들어 이벤트에 바인딩 된 함수가 _어떤 함수를 호출하고 상태가 어떻게 바뀌어야 한다_ 와 같은 **비즈니스 로직 호출 프로세스**의 경우는 더 하위단계의 테스트로 해당 클래스를 라이브러리의 도움을 받아 모킹을 한 뒤 테스트를 진행하는등의 방식으로 E2E테스트가 아닌 다른 레벨의 테스트로 따로 빼는것이 좋은 것 같습니다.

인성님의 의견이 궁금합니다.

2022-12-11 15:33 UTC, sanghunlee-711 commented on src/js/App.js
>      });
두가지 답변을 동시에 드릴 수 있을 것 같습니다.

2번에서 지적해주신 내용이 1번의 차이점을 만든 것인데요.

최상위 태그에 이벤트를 바인딩하여 이벤트 바인딩을 위한 회문을 줄이는 것이 첫번째 목표였습니다. 그래서 1번과 같은 App 컴포넌트와 컴다른 컴포넌트는 다른 형태를 가지게 된 것입니다.

만약 앱이 확장되어 submit이벤트 등이 여러개 필요한 상황등의 경우 리팩토링은 당연히 필수인 상태입니다!

꼭 최상위 DOM에 바인딩을 하지 않아도 괜찮을까? 라는 의문은 저도 항상 가지고 있는 부분입니다. 인성님의 의견이 궁금하네요

각 컴포넌트 별로 해당 타겟에서 이벤트를 등록하는것이 복잡성 감소측면에서 더 좋다고 판단하시나요? 
아니면 다른 방식으로 확장성을 늘리고 복잡성을 줄일 방법이 있으시다면 어떤방법이 있을까요 ?

2022-12-11 15:36 UTC, sanghunlee-711 commented on src/js/components/Attempt.js
>      }
함수명을 동사로 작동하고 싶어 동사를 넣었습니다 ㅎㅎ

개인적으로는 isValidateCarNames는 validateCarNames함수를 호출한 결과를 받을 변수에 더 적합해보인다는 생각이 듭니다!

return 부분은 false로 반환하는 것이 훨씬 좋은 것 같습니다! 🤗

2022-12-11 15:37 UTC, sanghunlee-711 commented on src/js/components/Attempt.js
>      if (!isDisabledButton) $carSubmitButton.removeAttribute('disabled');
완전 동의합니다! 미쳐 캐치하지 못한부분이네요 🥲

2022-12-11 15:37 UTC, sanghunlee-711 commented on src/js/components/Attempt.js
>      if (!isDisabledInput) $carNameInput.focus();
완전 동의합니다! 미쳐 캐치하지 못한부분이네요 🥲 🔥

2022-12-11 15:39 UTC, sanghunlee-711 commented on src/js/components/Attempt.js
> +    const isDisabledInput = isVisibleTrial;
해당 부분에서 조금더 의미있는 코드로 보여지려 노력해보았던 부분 같네요 ㅎㅎ;;;
`isVisibleTrial`이라는 상태가 `isDisabledInput`이라는 조건에 부합한다는 의미입니다만.. 굳이 필요했나 싶습니다 👀

2022-12-11 15:39 UTC, sanghunlee-711 commented on src/js/components/Attempt.js
> +    });
좋은 생각이신 것 같습니다!

2022-12-11 15:39 UTC, sanghunlee-711 commented on src/js/components/Player.js
> +        }
음 그렇네요 이 부분은 별도의 함수로 분리해보도록 할게요 :)

2022-12-11 15:41 UTC, sanghunlee-711 commented on src/js/core/Component.js
> +    }
그렇네요 추상메서드에 대한 강제성이 없으니 멘션의 의미가 알맞지 않은 것 같습니다

2022-12-11 15:45 UTC, sanghunlee-711 commented on cypress/e2e/racingcar.cy.js
> +        });
이 건은 테스트 케이스를 따로 파는 것이 맞을 것 같네요 ㅎㅎ..
애초에 테스트 구문이 **다시시작하기 버튼 클릭 시** 이기때문에 **엔터키를 누르면** 등의 구문으로 테스트를 추가해보는 것이 맞을 것 같습니다.

2022-12-11 15:46 UTC, sanghunlee-711 commented on src/js/components/Trial.js
> +    const newRacingMap = makeNewRacingMap(racingMap);
여기도 불필요한 부분이네요 ㅎㅎ.. 재빠른 삭제 해보겠습니다 :)

2022-12-12 08:04 UTC, InSeong-So commented on cypress/e2e/racingcar.cy.js
>  describe('레이싱카 사이트 E2E 테스트', () => {
eslint, prettier의 적용을 검토해보면 좋겠네요!

2022-12-12 08:12 UTC, InSeong-So commented on cypress/e2e/racingcar.cy.js
> +      });
상훈님의 코드로 실험을 좀 진행했는데, 예상되는 상황은 다음과 같습니다.

1. 클래스 인스턴스에서 호출하는 내부 메서드들이 특정 이벤트에만 핸들링되어서 이를 모킹할 수 없다.
2. cypress 내부 컨텍스트가 아니라 이벤트 발생 -> 특정 클래스 생성 -> async/await 호출로 인해 문제가 생긴다.

실제로 stub은 동기 함수라서 이렇게 작성되면 무조건 submitTrial 실행을 건너뛰고 판단하기 때문에 호출되지 않는게 맞습니다. 그렇다면 then 체이닝으로 걸면 되지 않을까...? 싶었는데 이벤트 핸들러에서 호출하는 함수들은 전부 stub으로 모킹이 불가능하네요.

혹시하고 다른 파일과 cypress stub을 활용하여 유닛 테스트를 해봤는데 아래 코드는 잘 동작합니다.
```js
// ./src/js/CustomApp.js
import utils from './utils/index.js';

class CustomApp {
  constructor(){
    console.log('테스트 앱 클래스 생성');
  }

  init(){
    utils.getProgressOrNot();
  }
}

export default new CustomApp;
```
```js
import utils from '../../src/js/utils/index.js';
import CustomApp from '../../src/js/CustomApp.js';

describe('app test', () => {
  it('stub 호출 여부 확인', ()=> {
    cy.stub(utils, getProgressOrNot);
    CustomApp.init();
    expect(utils.getProgressOrNot).to.be.called;
  });
})
```


 그로 인해 추론 가능한 부분은 비즈니스 로직을 mocking해도 클래스 인스턴스 + 이벤트 핸들러로 인한 프로세스는 검증 불가능하다... 인 것 같네요😅

2022-12-12 08:36 UTC, InSeong-So commented on cypress/e2e/racingcar.cy.js
> +        });
다른 내용은 전부 상관 없이, mocking이 필요한가 합니다. 테스트의 필요성이나 철학을 논하기 이전의 문제 같네요. 그러나 상훈님이 말씀하신 내용에 제가 의도한 부분이 충분히 내포되어 있는 것 같습니다. 내부적인 로직의 복잡성으로 인해 이런 형태의 mocking이 필요하다면 그것은 앱이 잘못 설계되지 않았을까요?

makeNewRacingMap은 utils에 정의된 함수입니다. 유틸리티적인 함수라면 동일한 input-output을 가지며 어떤 환경에서도 import하여 사용할 수 있죠. 그렇다면 mocking이 필요할 수 있다고 판단됩니다. return, args등을 개발자가 간단하게 제어할 수 있으니까요. 그런데 현재 조작하는 mocking 콜백을 보면 도메인 로직에 강하게 결합되어 있어요. 그렇다면 내부 프로세스를 잘게 쪼개어서 각각의 값을 핸들링하는 함수를 호출한 뒤에 다음 프로세스를 진행하는 것이 흐름상 옳다고 생각합니다.

이미 구현되어 있는 함수임에도 `테스트를 위한 코드`라는 것도 사실 잘 와닿지 않습니다. 그렇다면 해당 함수는 실제 코드와 별개의 문맥을 가진다는 의미이기도 하기 때문입니다. mock으로 **특정 값을 밀어넣어서** 라는 의미는 기존 함수의 역할을 대체한다는 것이니까요. 테스트 코드를 믿고 리팩토링을 진행해도 다른 문맥에서의 도메인 로직이 정확히 동작하리라는 보장이 없으리라 사료됩니다.

2022-12-12 08:49 UTC, InSeong-So commented on cypress/support/commands.js
> +  cy.get($element.moveSubmitButton).should('be.disabled');
> 세부적으로 호출에 대한 이야기라면 class내부의 메서드가 엘리먼트의 이벤트에 따라 실제로 호출이 되고 있는가에 대한 테스트를 E2E 테스트에서도 진행하는 것이 필요하다 라고보시는것으로 이해하면 되는 것일까요? 맞다고 보신다면 왜 그렇게 생각하는지 의견이 궁금합니다.

E2E 테스트는 사용자 중심으로 처음부터 끝까지 어플리케이션 흐름을 테스트하는 소프트웨어 테스트 방법입니다. 액션에 의한 결과만을 바라본다면 그게 과연 흐름을 테스트하는 것일까 생각됩니다.

상훈님의 말씀처럼 UI만을 테스트하는 것이라면, 특정 주기에 상태를 확인해야 하는 테스트 코드가 필요한 경우 E2E가 아니라 유닛 테스트로 가야하는지 여쭤보고 싶어요. E2E 테스트가 UI의 변화만을 판단하는 것이라면 로그인-회원가입 등의 프로세스는 어떻게 처리하고, 그 과정에서 발생하는 에러는 어떻게 UI로 그릴 것인지도 정의해야 합니다.

상단의 코드만을 보고 제3자가 이해할 수 있는 바는 "움직이는 버튼을 클릭하면 비활성화된다" 입니다. 실제로도 그런 테스트 케이스가 있었죠. '이동 횟수를 제출 한 뒤 button이 비활성화 되어야 한다.' 이 테스트케이스는 단순히 상태만 확인할 수 있으니 전혀 문제가 없습니다.

그러나 그 하단에 이어지는 '전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.' context는 해당 E2E 테스트를 기반으로 특정 비즈니스 로직의 호출을 제어하려고 합니다. 그렇다면 상훈님이 말씀하신 E2E 테스트의 개념과도 상충된다고 생각돼요.

추가적으로 상훈님의 이벤트는 여러 컴포넌트, store 등에 사이드 이펙트를 일으키고 있기 때문에 단순히 액션-UI 변화만을 체크하기에는 위험할 것 같아요. 테스트는 정교하고 자세하면 자세할수록 배포 전/리팩토링 간 많은 도움이 될 것이니, 비즈니스 로직 호출 프로세스를 잘게 쪼개는 것이 E2E를 흔드는 형태는 아니라는 것을 말씀드리고 싶습니다.

2022-12-13 01:12 UTC, sanghunlee-711 commented on cypress/e2e/racingcar.cy.js
>  describe('레이싱카 사이트 E2E 테스트', () => {
좋은 것 같습니다 정신없이 하다보니 기본 세팅으로 계속 진행을 했네요 ㅎ..

2022-12-13 01:17 UTC, sanghunlee-711 commented on cypress/e2e/racingcar.cy.js
> +        });
맞습니다 stub의 적절한 활용을 위해서는 앱의 설계 부분이 꽤 변경되어야 할 것 같다는 생각이 드네요. 아마도 구조적인 부분을 변경하면서 코드들을 잘게 쪼개고 다듬다보면 도메인로직을 분리한 Util을 모킹하는 방식이 생겨나지 않을까 추측이 됩니다. 

** 그렇다면 내부 프로세스를 잘게 쪼개어서 각각의 값을 핸들링하는 함수를 호출한 뒤에 다음 프로세스를 진행하는 것이 흐름상 옳다고 생각합니다.** 이 부분이 많이 와닿네요 🤗

아무래도 현재 상태를 유지하면서 테스트 코드를 짜려하니 제가 이야기 드렸던 밀어넣는 방식말고는 떠오르지 않았던 것 같아요

2022-12-13 01:25 UTC, sanghunlee-711 commented on cypress/support/commands.js
> +  cy.get($element.moveSubmitButton).should('be.disabled');
**그러나 그 하단에 이어지는 '전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.' context는 해당 E2E 테스트를 기반으로 특정 비즈니스 로직의 호출을 제어하려고 합니다. 그렇다면 상훈님이 말씀하신 E2E 테스트의 개념과도 상충된다고 생각돼요.**
사실 제 개인적으로는 이 부분을 여기서 다루는게 맞는건가 하는 의문이 들었습니다. 수강생의 입장이다 보니 최대한 가능한 방식으로 요구사항을 따라가보려 하고 있습니다 ㅎㅎ;

여기서 유닛, 인터그레이션, E2E테스트 등의 개념은 회사마다 사람마다 다소 정의가 꽤 다른 걸 이번기회를 통해 주변에 자문을 구하며 느꼈습니다. 질문주신 부분은 차라리 통합테스트라는 범위로 유틸, 클래스, 상수를 복합적으로 테스트한다는 개념으로 해당부분의 플로우만 체크하는게 오히려 더 좋은 선택이 아닐까 하는 생각도 듭니다.

그리고 E2E테스트의 정의가 흐름 전체를 테스트한다면 본 cypress를 활용한 테스트 코드는 꽤나 더 잘게 쪼개져야한다는 생각이 듭니다.

 그로 인해서 코드의 리팩토링이 일어날때마다 호출순서가 변경되는 등의 사유가 생기면 E2E의 테스트코드 또한 꽤나 변경되어야할 것 같습니다.

물론 적절한 설계와 알맞은 위치에 적절한 메서드를 미리 배치해놓고 테스트를 짠다면 이것이 해결 되겠으나 TDD라는 개념으로 보았을때 선제적으로 테스트 코드를 작성하는데, 작성과 동시에 로직의 흐름마저 테스트코드에 선제적으로 배치하는건 꽤나 숙련된 상태에서야 가능할 것 같다는 생각이 드네요. 

여기서 질문을 하고 싶은 부분은 인성님은 앱의 설계 또는 구현 전 TDD의 개념으로 진행한다면 로직의 부분까지 e2e에 녹여놓은 다음 앱의 구현에 들어가시는 편이신가요? 아니면 큰틀의 UI를 먼저 체크하는 것으로 두고 추가적으로 테스트코드를 얹어보는 식이신가요?

아마도 전체적으로 이벤트에 의한 사이드이펙트 및 로직의 불안정성이 코드에 많이보이셔서 이러한 제안을 주신것이라고 이해할 수 있을 것 같습니다.

2022-12-13 01:25 UTC, sanghunlee-711 commented on src/js/App.js
>      });
** App 클래스가 과연 Component를 상속할 필요가 있는지도 생각해보시면 좋겠습니다.** 많은 힌트를 내포하신 문구네요! 전체적인 설계의 방향을 다시 생각해볼 수 있는 지점인 것 같습니다. 감사합니다 :)

2022-12-13 02:18 UTC, sanghunlee-711 commented
> 

안녕하세요 인성님! 우선 답변해주신 부분들 찬찬히 잘 읽어보았습니다 :) 길게 이야기 하시는걸  긍정적으로 받아들이시니 다행입니다 ㅎㅎ..

**1. 리뷰 태도에 대한 답변**

의견에 앞서 인성님이 직접 리뷰 태도에 대해 멘션 해주셨으니 답변을 드리는게 맞는 것 같습니다.

애정어린시선으로 욕심이 나셔서 진행하신 리뷰일 것이라 확신하고 있습니다만, 리뷰를 받는 입장에서 아쉬웠던 부분을 조금만 적어보겠습니다 😅. 

제가 느낀 큰 부분은 리뷰에서의 질문의 답변요청 사이에 개선을 위한 힌트 또는 질문의 이유가 없는 경우가 있습니다.

이러한 리뷰는 받는사람 입장에서는 답변만을 하고 생각을 이어나가지 못하는 경우가 있는 것 같습니다. 

아마도 제가 질문의 의도를 파악하는 부분에서 능력이 부족한 것일 수도 있을 것 같습니다. 

개인적인 리뷰 태도를 말씀해주셨으니 개인적인 리뷰를 받는 소감을 말씀드리는게 맞는 것 같아 사족을 덧붙여 보겠습니다 ㅎㅎ

오히려 질문 뒤 이런 방식으로 생각을 해 볼 수 있을 여지가 있다는 힌트를 주신 다거나 질문을 하신 명확한 이유를 제시 해주신다면 리뷰를 받는 입장에서 더욱 좋을 것 같습니다.

**이렇게 되면 모든 컴포넌트 클래스가 observer.observe를 호출하게 되는데.... 맞을까요?!** 가 가장 대표적인 예시라고 저는 생각이 드는데요. 

물론 **대부분의 리뷰 코멘팅에서 근거와 함께 질문을 남겨주셨으나**, 몇몇 코멘트에서는 명시적 이유가 없이 질문만 존재함 또는 이 질문을 해결함과 동시에 얻을 수 있는 코드의 이점에 대한 방식의 기재가 부재한 경우가 있었습니다. 

아마도 이런 부분은 리뷰이가 코멘트를 보게된다면 당황스러운 지점일 수 밖에 없다고 생각합니다. (저만 그런 걸수도 있습니다 😅)

현재는 저희의 긴 대화를 통해 저 코멘트의 의미가 
**이렇게 되면 모든 컴포넌트 클래스가 observer.observe를 호출하게 되는데.... (이렇게 되면 렌더링 이슈가 생길수도 있을 것 같은데 옳바른 방식이) 맞을까요?!**

위와 같다는 것으로 이해를 한 상황입니다. 

아무쪼록 애정 어린시선으로 진행된 리뷰라 생각하고 있으니 너무 염려치 않으셔도 될 것 같습니다.

**2. 구조개선에 대한 아이디어**
저는 이번스텝을 통해 인성님과 전체적인 구조 또는 플로우에 대한 합의점을 찾고 코드를 작성하는 파트로 넘어가고 싶다는 개인적인 욕심이 있습니다. 

현업에서 대부분 라이브러리, 프레임워크에 의존해서 UI,UX를 만드는 일이 많아 주어진 플로우에 맞춰 만들다 보니 이런 경험이 부족하여 이번기회에 좋은 방식으로의 설계를 할때 고려할점을 인성님의 리뷰 및 함께하는 대화를 통해서 많이 배우고 있다고 생각이 들고 있습니다.

그래서 가시적인 설계를 함께 완료한 뒤에 작성된 코드에 대한 리뷰를 받으면 이번에 등록한 스터디에서 가장 값진 프로세스가 되지 않을까 라는 생각이 듭니다.

1. **스탭 2에서 진행한 내용을 보면, 결국 상훈님이 선택한 것은 중앙 집중형 저장소인 Store를 두고 각 컴포넌트가 가진 특정 상태가 변경되면 렌더링 되도록 하는 Redux와 같은 Flux 패턴이라고 생각...되나, 현재는 각 컴포넌트가 가진 부수 효과는 그대로며 Component라는 클래스로 인해 사용하지 않는 불필요한 메서드도 강제되거나 render임에도 렌더가 아닌 특정 기능을 수행하도록 변경하고 있어요.**

2. **공통적인 기능(상수, 유틸리티 함수)을 제외하고 나면, 각 의존 관계는 한 방향을 흐르도록 하는게 제일 좋거나, 양방향이더라도 일관된 흐름이 보여야 하는데 아래를 보시면 EVENT_MAP이 상수 파일에 존재하여 모든 파일에서 접근하고, store 또한 마찬가지입니다.**

 **1,2의 멘션을 보고 생각을 이어나갔을 때 현재 구조에서 많은 문제를 일으키는 지점은 Component 클래스라고 생각합니다.** 

이야기 해주셨던데로 불필요한 메서드의 강제로 인해 의미가 맞지 않는 상황에서 들어가 있는 로직들이 존재하고 이로인해 불필요한 흐름이 생기게 되는 것 같습니다. 

따라서 생각해보았던 방식은 아래와 같습니다.

아무래도 사견을 붙여주신 부분에서 Observerable한 방식조차 마음에 드시지 않으실 수도 있으나 잘만 사용한다면 상태들을 한 곳에서 잘 관리할 수 있는 유용한 방법이라고 생각이 들어 이 부분은 유지하면서 조금 변경을 해보았습니다.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/57477415/207205890-d35035eb-c793-4f08-8735-164e8fc8a188.png">

1. observer(Proxy), store는 그대로 살려둔다. 또는 하나의 클래스로 합쳐본다.

2. Component라는 베이스 클래스를 지운 뒤 Store에서 state를 가져오는 부분이 있는 컴포넌트의 경우(Stateful이라 명명하겠습니다.) observer의 콜백에 render를 등록해준다.

3.베이스클래스를 제거 하였으므로 State가 필요하지 않은 컴포넌트의 경우(Stateless라 명명하겠습니다.) 렌더링을 최적화 시키도록 로직 변경이 가능하다.

4. 그로 인해 자연스러운 컴포넌트 나누기 및 도메인에 알맞은 유틸 분리가 가능할 것으로 유추된다. 이 과정에서 네이밍의 문제 및 유틸리티 함수의 도메인 간섭문제도 해결 될 수 있을 것 같다. 

5. 이벤트리스너도 해당 컴포넌트의 타겟에 맞춰서 넣어주면 이벤트 트리거에 의한 state변경 흐름은 일관성을 유지 할 수 있을 것 같다.(이 또한 베이스 컴포넌트의 확장 없이 작성하기에 가능할 것 같습니다).

위 내용 모두 인성님이 언급해주신 내용을 앵무새처럼 말하는건가 싶은 생각이 지금 들긴하지만.. 이해도의 싱크를 맞추고자 적어봅니다 ㅎㅎ

이렇게 변경을 해본다고 하였을때 기재된 방식에 대해서 인성님은 어떤 생각을 가지고 계신지 궁금합니다 :) 

더 개선되거나 이 부분은 이해가 가지 않는다 하시는 쪽이 있으면 코멘트에 첨언 부탁드립니다.

감사합니다 :)

2022-12-26 15:24 UTC, sanghunlee-711 commented
> 안녕하세요, 상훈님! 코멘트가 많이 늦어졌어요. 말씀하신 내용에 전적으로 공감합니다. 현재 상훈님께서 적어주신 프로세스로 코드를 리팩토링하거나, 다음 스탭을 진행하면서 상훈님의 패턴을 만들면 좋을 것 같습니다🙏

안녕하세요 인성님! 거의 2주만에 다시 요청을 하게 되네요! 
연말이 되니 각종 KR 정리로 일이 많이 바빠지네요 하하.. 

인성님도 몇일 남지 않은 연말 화이팅 하시길 바랍니다 😎

아래 몇가지 참고사항 확인해주시면서 리뷰해주시면 감사드리겠습니다 :)

### 1. STEP3를 진행하면서 위의 언급하였던 것과 같이 베이스 컴포넌트를 지웠습니다
베이스 컴포넌트를 지움으로서 렌더와 관련된 함수와 그렇지 않은 함수를 잘 분리하게 되었고 나름 깔끔해진 것 같습니다

### 2. constant, utils를 정리하였습니다.
기존에 Index 에 몰아 넣었던 것을 조금 의미있게 분산시키려 노력했습니다.

그렇게 하면서 도메인과 조금 연관이 있던 유틸들은 해당 클래스 안으로 다시 집어 넣어보았습니다.

### 3. 소소한 설정
제쳐놓은 Prettier, Eslint 설정들을 적용하였습니다.

### 4. 결국 사용하지 못한 stub
하.. 이건 도저히 지금의 로직구조를 가지고 간다면 해결이 되지 않을 것 같다고 보입니다.

클래스를 더욱 분산해서 자동차 게임을 만드는 로직만 가지고 있는 부분을 억지로 따로 클래스로 두고 stub시킨 다음 return 되는 값을 변수로 받아오는 시도 해보았으나.. 이 또한 이벤트핸들러에 연관이 있어서 인지 확인이 되지 않았습니다.

결국 stub등으로 값을 가져오는 것을 하지 못해서 화면 내에서 winners를 긁어와 이 값이 alert 또는 우승자가 뜨는 섹션의 텍스트와 동일한지 테스트하는 방향으로 진행되었습니다.

좋은 아이디어나 로직 개선방향이 보이신다면 꼭 첨언 부탁드리겠습니다.

2023-01-08 06:26 UTC, InSeong-So approved these changes
안녕하세요, 상훈님! 리뷰가 어어어어엄청 늦어졌네요😭

제 개인적인 생각으론, 어떤 정리되지 않은 추상적 집합에 대한 의존성이 많이 벗겨진 것 같아 술술 읽혔습니다.

기존 코드를 확인할 때 가장 어려웠던 점을 굳이 꼽자면, 앱이 어떻게 변화되는지를 확인하기 위해 모든 class 를 나열해두고 하나하나 비교 했어야 했던 점이었어요.
- 어느 시점에 어떤 액션에 의해 화면이 변경되고, 데이터나 상태가 변경되어 이를 처리할 수 있는지?
- 에러는 어디서 발생하고 여러 번 시도되지는 않는지?
- 흐름에 맞게 로직이 실행되는지?

이를 확인하는데 많은 소요가 걸린 반면, 지금의 코드는 파일 하나의 스코프가 대부분의 시간 흐름이나 논리를 설명하고 있어서 재밌게 읽은 것 같습니다.

eslint 설정을 몇 개 수정하셨는데, esnext 등의 옵션은 가급적이면 명시하길 추천드립니다. 2022라던지, ES6이라던지... 가끔 에디터에서 말썽을 일으키더군요.

prettier 또한 여러 옵션이 있는데 OS를 바꿔가거나 VSCode, WebStorm 그 외의 IDE/Editor 를 사용하면서 생길 법한 이슈가 몇 있으니 점진적으로 수정해보시는 것을 추천드립니다😊

프로젝트를 진행하면서 상수나 유틸적으로 조금 더 분리할 수 있거나, 혹은 과하게 분리되었거나, 그 쓰임새가 불분명한 부분들이 분명 존재할 거에요. 그 때마다 `현재 프로젝트의 규모`와 `내가 없는 자리를 채우는 개발자가 보았을 때`를 상상하면서 배치해보면 좋은 경험이 됩니다. 흡사 레고처럼요.
현재 상훈님의 코드가 많이 변경 되었지만 제가 이해한대로 동작하는 것으로 보여 좋은 분리라고 느꼈습니다.

추후 웹 컴포넌트, 비동기 상황과 갖가지 패턴(디자인, 렌더링 등)을 적용하면서 프레임워크와 라이브러리 없는 날 것 그대로의 개발을 몇 번 하시다보면 프레임워크나 라이브러리, 혹은 진영을 초월한 언어들을 공부하거나 이해할 때 큰 도움이 될 것입니다.

미션 고생 많으셨어요😊

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/CarPlayer.js
> +    });
👍 이렇게 되면 다른 컴포넌트 레벨에서 렌더링이 일어나지 않겠죠!

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/CarPlayer.js
> +          }
`isRacingEnd`가 직관적으로 분리되어서 너무 좋았어요! 조금 더 좋게 바꿔보자면, 아예 해당 영역을 raacingEndTemplate 등의 함수나 변수로 만들어서 대치하면 어떨까요?

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/CarNameRegister.js
> +    });
```js
this.$attemptWrapper.addEventListener('submit', this.onSubmitCarname);
```
이게 좀 더 보기 좋은 것 같아요!😇

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/RaceProgress.js
> +      .filter((el) => Boolean(el));
이 부분은 상단에 언급한 내용과 어느정도 일치하는 것처럼 보입니다.

조건문을 정리하고, 줄일 수 있는 Wrapper 객체를 없애거나 축약문으로 적어주면 더욱 쉽게 읽힐 것 같네요!

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/RaceProgress.js
> +      .join('');
Rece 진행 표시 컴포넌트가 CarPlayer를 다시 호출해서 셋하는군요...! 컴포넌트 간 계층 관계까 잘 안그려졌었는데 시간의 흐름에 따라 배치한 것으로 보이네요. 공통된 조상 클래스의 함수 실행 사이클이 없어지면서 좀 더 이해하기 편해진 것 같습니다👋

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/Result.js
> +    });
이 부분도 아래 처럼 바꾸면 한 줄로 깔끔해질 것 같네요!

```js
observer.observe(this.render);
```

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/TrialNumberRegister.js
> +  };
`4` 도 상수로 분리하면 더 좋을 것 같습니다! 요구사항이 4에서 3이나 5로 변경된다면 모두 찾아서 적용해줘야 하니까요🥲 이해하기도 쉽고, 관리 포인트도 줄일 수 있게 상수를 적극 추천드립니다!

2023-01-08 06:26 UTC, InSeong-So commented on src/js/components/TrialNumberRegister.js
> +      .filter((el) => Boolean(el));
이런 형식의 코드를 본 것 같은데🤔 상훈님이 즐겨쓰시는 방식을 몇 개 통합할 수 있어보입니다. 유틸 함수로 만들어보면 어떨까요?

2023-01-08 06:26 UTC, InSeong-So commented on src/js/store/index.js
만약 에러가 발생하면 어떻게 될까요?🤔
try-catch 구문이 없는 코드로 봤었는데...

2023-01-08 06:26 UTC, InSeong-So commented on src/js/utils/asyncHandle.js
> +export const waitUntil = (delay) => new Promise((resolve) => setTimeout(resolve, delay));
delay에 default value를 주면 좋을 것 같아요! 현재 undefined 등에 대한 대처가 안 될 것 같습니다.

2023-01-08 06:27 UTC, merged

2023-01-10 00:14 UTC, sanghunlee-711 commented
인성님! 오랜만입니다 :) 기간이 지났음에도 리뷰 해주셔서 정말 감사드립니다 🤗
적어주신 멘션 중 아래 코멘트를 통해 많은 생각을 해보게 되었습니다.

> 프로젝트를 진행하면서 상수나 유틸적으로 조금 더 분리할 수 있거나, 혹은 과하게 분리되었거나, 그 쓰임새가 불분명한 부분들이 분명 존재할 거에요. 그 때마다 `현재 프로젝트의 규모`와 `내가 없는 자리를 채우는 개발자가 보았을 때`를 상상하면서 배치해보면 좋은 경험이 됩니다. 흡사 레고처럼요. 현재 상훈님의 코드가 많이 변경 되었지만 제가 이해한대로 동작하는 것으로 보여 좋은 분리라고 느꼈습니다.

아마도 항상 좋은 개발자가 되어야지 말만하고 애써 외면한 개념이 아닐까 싶습니다ㅎㅎ;;.. 이번 기회를 통해 다시한번 생각하게 되네요.

오랜 리뷰기간 동안 애정을 가지고 리뷰해주셔서 정말 감사드립니다. 적어주신 개별 코멘트는 개인적으로 적용해보며 전체 흐름을 통해 조금 더 개선해보겠습니다.

스터디기간동안의 노고에 감사드립니다 :) 앞으로 좋은일만 가득하시길 바라겠습니다!