[클린코드 4기 이근휘] 자동차 경주 미션 STEP 2, STEP3
next-step/js-racingcar pull request #145
Opened 2022-12-17 15:20 UTC by Geuni620

안녕하세요 은규님!
git이 꼬여버려서 이전기록까지 다 올라간 거 같습니다;

[여기부터가 Step2 입니다!](52919731643b057b917ce1dc6359b1dc7d8a91d2)

이번에도 아낌없는 지적과 조언 부탁드릴게요! 🙏
감사합니다! 🙇‍♂️

2022-12-18 17:28 UTC, EungyuCho requested changes
안녕하세요 근휘님~

안녕하세요 근휘님~

이번에 코드리뷰를 하면서 발견했는데 작업을 하실 때 커밋별로 나중에 추가적으로 작업할 내용을 커밋 메세지에 남겨주셨더라구요~ 이렇게 추후에 작업할 작업을 기록하는게 습관화되어있는 것 같아 좋았어요 ㅎㅎ

그래서 추가적으로 권장드리고 싶은 방법이 생각나서 코멘트를 드리려고해요!
기억에서 휘발되게되면 git을 찾아보지 않는 이상 놓칠 여지가 많고 작업해야할 맥락을 찾는데 파일을 이리저리 뒤져봐야하는 문제점도 있어서 저는 개인적으로 코드에 남겨드리는걸 추천드려요! 저는 코드라인에서 `TODO`나 `FIXME`를 추가해두고 있어요. VS code에 [TODO highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight)  extension이 있는데 설치해두시면 조금 더 나중에 작업하실 때 놓치지 않고 챙길 수 있을 것 같아 권장드려요~

step2, 3 범위가 적다보니 코멘트가 그리 많진 않네요 😅 
네이밍과 인터페이스나 불필요하다고 생각이 들었던 코드들에 대해서 코멘트를 남겨드렸어요
확인해주시고 다시 리뷰요청 부탁드릴게요~

2022-12-18 17:28 UTC, EungyuCho commented on src/js/model/validation.js
> +  },
해당 조건문은 유효하지 않은 자동차 이름을 검증하는 로직이 아닌가요? 👀

2022-12-21 16:06 UTC, Geuni620 commented on src/js/model/validation.js
> +  },
반대로 작성했군요,,, 수정하겠습니다!

2022-12-21 16:22 UTC, Geuni620 commented
은규님 안녕하세요! 
TODO highlight 잘 쓰겠습니다! :) ㅎㅅㅎ
커밋에 남겨놓고 올리기전에 rebase해야하는데 깜빡했네요,,,
그래도 덕분에 유용한 extension 알아갑니다 감사합니다 🙏

리뷰해주신 내용을 토대로 수정해보았습니다!
extractWinner함수 내 winner 변수를 제거하고 바로 return 처리했습니다.

많이 배우고 있어요 감사합니다!

2022-12-21 16:40 UTC, Geuni620 commented on src/js/model/validation.js
> +  },
네 맞습니다! 
혹시 제가 놓친게 있나요,,,?
말씀하신 의도가 무엇인지 궁금합니다!

2022-12-22 13:53 UTC, Geuni620 commented
안녕하세요 은규님 🙌

리뷰남겨주신 내용을 토대로 수정해보았습니다!
commit에 TODO를 적어놓고, rebase로 정리했어야했는데, 깜빡했네요 ㅎㅎ;
그래도 덕분에 좋은 Extension 알아갑니다!

리뷰 남겨주신 내용 중에 제가 이해를 못한 부분이 있어서 댓글 남겨 놓았습니다!
이번에도 아낌없는 지적과 조언! 부탁드립니다.

감사합니다 🙇‍♂️

2022-12-24 04:58 UTC, EungyuCho commented on src/js/model/validation.js
> +  },
앗.. 그 네이밍이 반대로 되어있는 것 같아서요

2022-12-24 05:03 UTC, EungyuCho commented
게임이 끝나고 2초가 지나기 전에 게임 초기화를 하면 새 게임을 시작함에도 전 게임에서 우승자를 보여주는 팝업창이 뜨는데 없애보는것도 좋을 것 같아요 👀

2022-12-24 05:04 UTC, EungyuCho commented
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/53712717/209422301-178b2bab-5a0f-47de-8f28-646418694ceb.png">
이 케이스에서는 맨 왼쪽에 스피너가 2번째 칸에 있어야하는데 UI에 표기되지 않고있어요 🤔

2022-12-24 17:37 UTC, EungyuCho approved these changes
몇가지 코멘트를 남겨드렸어요!
수정사항들이 컨벤션 관련된 코멘트는 아니라서 한번 더 리뷰요청을 드려요 🙇‍♂️

2022-12-24 18:00 UTC, EungyuCho requested changes
Request changes를 불러야하는데 어프룹을 했네요 😢 
코멘트 확인 부탁드려요 🙇

2022-12-27 14:56 UTC, Geuni620 commented
은규님~ 리뷰남겨주신 내용으로 수정해봤습니다.

'게임이 끝나고 2초가 지나기 전에 게임 초기화를 하면 새 게임을 시작함에도 전 게임에서 우승자를 보여주는 팝업창이 뜨는데 없애보는것도 좋을 것 같아요 👀'

- 클로저를 활용해서 제거하는 방법이 없을까? 고민하다가 결국 해결하지 못했습니다 ㅠㅠ.. handleSubmitResetBtn 내에서 renderCongratulatoryMessage().clearAlert()를 호출한다 한들, progressRacingCar내 renderCongratulatoryMessage()의 호출은 어떻게 수정할 수 있는지 해결못했네요,,, 클로저로는 안되는걸까요,,,? 결국 timerId라는 전역변수를 사용했습니다.

<br>

'네이밍이 반대로 되어있는 것 같아서요' → isValidCarNames

- InValidCarNames로 변경해봤습니다!

<br>

'이 케이스에서는 맨 왼쪽에 스피너가 2번째 칸에 있어야하는데 UI에 표기되지 않고있어요.'
- startRacingCar 함수 내에서 forward일 때도 renderSpinnerIcon함수를 추가해서 해결해봤어요!

<br>

꼼꼼히 확인해주셔서 감사합니다. 🙇‍♂️ 또 리뷰남겨주세요

2022-12-28 09:59 UTC, EungyuCho commented
> 클로저를 활용해서 제거하는 방법이 없을까? 고민하다가 결국 해결하지 못했습니다 ㅠㅠ.. handleSubmitResetBtn 내에서 renderCongratulatoryMessage().clearAlert()를 호출한다 한들, progressRacingCar내 renderCongratulatoryMessage()의 호출은 어떻게 수정할 수 있는지 해결못했네요,,, 클로저로는 안되는걸까요,,,? 결국 timerId라는 전역변수를 사용했습니다.

클로저로는 힘들어보이네요.. 🤔 
다른분의 리뷰에서는 class의 static field를 통해서 해결하는 방법을 추천드렸는데 현재의 전역변수와 크게 다르지 않아서 원하시는 해결책은 아닌 것 같아요.

clearTimeout을 해야한다는 생각에서 벗어나보면 어떨까요?
section-winner-render이 보이는지 여부로 다시 시작하기를 눌렀는지 안눌렀는지 알 수 있을 것 같아요!

2022-12-28 10:21 UTC, EungyuCho approved these changes
안녕하세요 근휘님~

추가로 질문주신 부분과 추가로 조건문에 관련된 코멘트를 남겨드렸는데 한번 참고만 해주세요~
보시고 질문 있으시면 추가로 코멘트로 질문해주셔도 돼요 😄 

자동차 미션 진행하시느라 고생 많으셨어요!

2022-12-28 10:21 UTC, EungyuCho commented on src/js/model/validation.js
> +      !name
not조건을 변수에 그대로 사용하는게 편하긴한데 정확한 의미를 파악하지 못할 가능성도 있고 실수할 여지도 있어서 boolean값만 조건문으로 다루는걸 추천드려요
관련 [eslint rule](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md)

2022-12-28 10:21 UTC, merged