[클린코드 5기 김경현] - 자동자 경주 미션 STEP 1
next-step/js-racingcar pull request #156
Opened 2023-07-24 07:16 UTC by frankuserconnect

안녕하세요 리뷰어님, 

1) 온보딩 미션에서 피드백을 받았던, 매직넘버를 사용하지 않고 상수로 처리하는 부분과 상수명을 신경 썼습니다. 피드백 부탁드리겠습니다.

2) 폴더명 사용방법과, 설계 접근방법 개선점에 대해서 피드백을 주시면 감사드리겠습니다. ex) constants, util, controller, model, view 등
   -  클래스를 사용한 이유: MVC 패턴을 살짝이라도 경험하면서, 클래스 객체 지향을 경험해보고 싶었습니다. 앞으로 프로젝트 및 미션을 할 때, 여러가지 방향성을 고려하여 더 적합한 방법을 스스로 결정하는데 도움이 될 것이라 판단했습니다.
   -  테코톡 MVC 영상을 참고하여, Model 내부에 Controller와 View에 관련된 코드가 있으면 안된다, View 내부에 Model의 코드만 있을 수 있고, Controller의 코드가 있으면 안된다 라는 것을 리마인드하며 진행했으나 제가 짠 코드에 자신감이 없고, 설계가 많이 잘못된거 같아서 앞으로 쭈욱 길게 나아 갈 수 있도록, 잘못된 부분에 따끔한 지적 부탁드립니다. 
   - 관심사 분리를 할 때, 유효성 함수 및 util 함수는 어디 위치에 나두면 좋을지에 대해서도 의견을 듣고 싶습니다.
   - 프로젝트에 새로운 기능을 추가하더라도 쉽게 추가할 수 있는 시스템을 만들고 싶습니다. 프로젝트 설계는 어떠한 방법으로 접근하는 것이 좋을지 고민입니다. 어디서부터 시작해야 하지? 무엇을 해야하지? 내가 잘 할 수 있을까? 등 많은 생각이 듭니다.  개인적인 질문일수도 있겠지만,,  괜찮으시다면.. 리뷰어님은 어떠한 과정을 거치셨고, 지금은 어떻게 접근을 하시는지 궁금합니다. 

3) 에러처리 / 에러 핸들링 
   - 현재는 constants 상수로 처리해서 throw Error 처리하고 있는데, 효율적인 방법 의견 부탁드리겠습니다. 

4) 테스트 코드: 설계가 제대로 나오지 않은 상황에서, 테스트 코드를 작성하려고 하니 여러 방면에서 많이 부족함을 느꼈습니다. 
   - 일반적인 테스트 코드 방법은, 테스트 코드 먼저 작성 -> 설계 -> 메인 로직을 짜는 순서일까요?  
   - 지금 가지고 있는 코드에서 어떠한 테스트 코드를 붙여나가야 좋을지 큰 고민입니다. 힌트를 주시면 감사드리겠습니다. 

부족한만큼 채워나가려고 노력하겠습니다.

2023-07-26 18:04 UTC, Tanney-102 requested changes
안녕하세요 경현님! 리뷰어 오태은입니다.
리뷰가 늦었네요..! 죄송합니다ㅠㅠ

PR description에 적어주신 것처럼 상수화에 신경쓰신점이 잘 드러난 것 같습니다!
변수명도 최대한 이해하기 좋게 잘 지어주신 것 같아요!
몇몇 아쉬운 함수 이름이 있었는데 요건 코멘트로 확인해주세요.
폴더도 무난하게 잘 구분해주신 것 같습니다.

mvc 패턴을 학습하고 적용해보신 것으로 이해했어요.
학습하신 내용을 기반으로 모듈을 나누고 구현하신 점은 꽤나 의미 있는 시도였다고 생각해요!
다만 특정 패턴의 사용법만을 익히는 방식은 그리 추천드리고 싶지 않습니다.
Model이 Controller와 View를 의존하지 않아야 한다는 사실 자체 보다는 왜 의존하지 않아야 하는지가 더 중요 합니다. 패턴이 해결하고자 하는 문제에 공감을 해야지 단순히 따라하기만 해서는 별로 얻을 게 없을 겁니다.

이 과정을 진행하면서는 먼저 도메인 로직과 그 도메인 로직을 어떤 방식으로든 표현하는 로직(대부분 UI로직이겠죠?)을 구분하는 연습을 많이 해보셨으면 좋겠습니다.(구현하신 코드에서는 Model이 도메인, Controller와 View가 UI가 되겠네요~) 그리고 나서 mvc든 어떤 패턴이든 조금은 다른 시선으로 바라 볼 수 있게되면 그때 깊게 공부해보셨으면 합니다.

> 관심사 분리를 할 때, 유효성 함수 및 util 함수는 어디 위치에 나두면 좋을지에 대해서도 의견을 듣고 싶습니다.

util은 잘 분리해주신 것 같구요~
validation 같은 경우 구현하신 것처럼 검증을 수행하는 모듈 안에 있는 것도 괜찮고 범용적인 validation이라면 util처럼 따로 분리하셔도 무방할 듯합니다. 다만 특정 도메인과 관련이 깊은 validation이라면 최대한 사용처와 가까이 있는 편이 좋긴 하겠죠!(다른 모듈로 분리하더라도 사용처 Model과 같은 디렉터리 안에 둔다던가)
물론 프로젝트 안에서 일관성 있게만 관리되긴 해야합니다.
지금은 특정 도메인에 대한 validation 임에도 model 안에 있는 validation도 있고 util안에 있는 것도 있네요.

> 프로젝트에 새로운 기능을 추가하더라도 쉽게 추가할 수 있는 시스템을 만들고 싶습니다. 프로젝트 설계는 어떠한 방법으로 접근하는 것이 좋을지 고민입니다. ... 리뷰어님은 어떠한 과정을 거치셨고, 지금은 어떻게 접근을 하시는지 궁금합니다.

결국 경험인 것 같아요.
좋은 설계 방법, 좋은 아키텍쳐, 유명한 패턴들...
아무리 컨텐츠가 좋아도 딱 내 경험의 질과 양만큼만 이해되고 흡수가 되는 것 같습니다.

막연히 무언가를 따라하는 것보다 먼저 '의도를 가지고' 시도한 뒤에 피드백을 받아보는 경험을 늘려가셨으면 합니다. 예를 들어 이번 미션에서 매직넘버를 없애기 위해 의도적으로 많은 constants을 선언해보셨기 때문에 이에 대한 피드백이 긍정적이든 부정적이든 분명 도움이 되는 경험이셨을 겁니다. 남은 클린코드 미션들에서 이런식으로 여러 실험들을 해보시면 좋겠네요 ㅎㅎ

> 현재는 constants 상수로 처리해서 throw Error 처리하고 있는데, 효율적인 방법 의견 부탁드리겠습니다.

지금도 충분히 잘 하셨다고 생각합니다.
error를 throw하는 방법 뿐만 아니라 setter에서 항상 result를 반환해 사용처에서 명시적으로 처리할 수 있도록 하는 방법도 있으니 참고만 해주세요.
```js
const setSomeThing = (value) => {
  if (!isValid(value)) {
    return {
      status: 'error',
      error: {
        message: 'some error message',
      },
    }
  }
  
  // do something

  return {
    status: 'success',
    error: null,
  }
}

const { status, error } = setSomeThing(value)
if (status === 'errror') {
  showErrorMessage(error.message)
}
```

> 일반적인 테스트 코드 방법은, 테스트 코드 먼저 작성 -> 설계 -> 메인 로직을 짜는 순서일까요?

TDD를 제대로 적용하려는 게 아니면 순서가 크게 상관 있나 싶긴하네요

> 지금 가지고 있는 코드에서 어떠한 테스트 코드를 붙여나가야 좋을지 큰 고민입니다. 힌트를 주시면 감사드리겠습니다.

우선은 Model이 가지고 있는 동작에 대한 테스트를 먼저 작성해보시면 어떨까요? 작성하시다가 어려움이 있으면 공유해주세요! 같이 고민해보면 좋을 것 같습니다.

추가로 몇몇 코멘트 달아두었으니 확인부탁드립니다!

2023-07-28 08:53 UTC, frankuserconnect commented on src/controller/RacingCarGameController.js
> +  }
```js
   printGameStatus(gameStatus) {
     gameStatus.forEach(car => {
       console.log(`${car.carName}: ${car.forward}`);
     });
   },
```

위 코드 정도의 가공 로직은 컨트롤러에서 해야할까요?

```js
  const gameStatus = this.getGameStatus();
  updateView.printGameStatus(gameStatus);


  getGameStatus() {
    return this.gameTrack.gameStatus.map(
      car => `${car.carName}: ${car.forward}`
    );
  }
```

```js
  printGameStatus(gameStatus) {
    gameStatus.forEach(status => {
      console.log(status);
    });
  },
```

2023-07-28 11:22 UTC, frankuserconnect commented
진심으로 피드백 감사드립니다. 피드백 반영해서 다시 PR 올리겠습니다!

2023-07-30 16:43 UTC, Tanney-102 commented on src/controller/RacingCarGameController.js
> +  }
오 이 메서드를 controller로 옮기신 특별한 이유가 있을까요?

2023-07-30 16:43 UTC, Tanney-102 commented on src/controller/RacingCarGameController.js
> +  }
데이터를 '어떻게' 보여줘야 할지에 대한 영역이니 view에서 모두 처리해도 충분할 것 같습니다!

2023-07-30 16:44 UTC, Tanney-102 approved these changes
안녕하세요 경현님!
리뷰 관련해서 반영해주신 내용 잘 확인했습니다!
질문 하나 남겼는데 그 질문에만 reply 남겨주시고 다음 스텝 진행하시면 될 것 같습니다~
고생 많으셨습니다!

2023-07-30 16:44 UTC, merged

2023-07-31 00:45 UTC, frankuserconnect commented on src/controller/RacingCarGameController.js
> +  }
@Tanney-102  utils에서는 범용성 있는 함수만 처리하고 싶었습니다! 피드백 주신대로 함수명과 기능이 상이한 부분도 있었다고 느꼈습니다! :)

2023-07-31 00:51 UTC, frankuserconnect commented on src/controller/RacingCarGameController.js
> +  }
setAdvanceCars 메소드는, 아래와 같이 피드백 주신 부분처럼 어느 곳에 GameTrack을 붙여도 괜찮도록, 여러 사용처에 동시에 사용할 수 있게 개발한다고 가정했습니다. 
모델에는 DB처럼 값만 담아주고, date를 전달해주는 역할로 표현해보고 싶었습니다. 리뷰 부탁드리겠습니다! 

---

모델에서는 최대한 도메인 로직에만 관심을 두고 실제로 어떻게 보여질지는 철저하게 view에서 관리했으면 합니다.
즉, forward의 수가 "-"라는 문자로 표현된다는 사실을 GameTrack 모델이 몰랐으면 좋겠습니다.
좋은 도메인 로직은 어느 사용처에 붙여도 변경없이 바로 사용할 수 있는 로직입니다.

똑같은 GameTrack 모델을 가지고 여러 사용처에 동시에 사용할 수 있게 개발한다고 상상하시면 좋을 듯 합니다.
예를 들어

forward를 '-' 문자로 표현하는 콘솔 앱
forward를 '=>' 문자열로 표현하는 콘솔 앱
forward를 자체 아이콘으로 표현하는 웹앱
...
이런 앱들 중 어느 곳에 GameTrack을 붙여도 괜찮도록!

2023-08-02 15:20 UTC, Tanney-102 commented on src/controller/RacingCarGameController.js
> +  }
step2 리뷰에서 답변드리겠습니다~