[클린코드 5기 문광민] - 자동자 경주 미션 STEP 1
next-step/js-racingcar pull request #157
Opened 2023-07-24 15:33 UTC by KwangMin-bright-Moon

안녕하세요 리뷰어님😊
이번 미션 리뷰도 잘 부탁드립니다.

우선 이번 미션 구현 사항을 제대로 이해한건지 확신이 들지 않습니다. 그래서 차라리 빨리 피드백을 받는게 나을거 같아 먼저 리뷰요청을 드립니다.
제대로 이해가지 않았던 부분은 콘솔에 출력하는 부분인데, 사용자에게 입력을 받는 걸 구현해야하는건지 아니면 입력 받았다는 가정하에 콘솔에 메세지만 보여주면 되는 건지 제대로 이해하지 못했습니다. (우선 메세지만 보여주도록 구현했습니다)

### 고민했던 부분
- 자동차 경주는 5회로 고정한다를 테스트할 때 5번 함수가 호출된다를 테스트하기위해 mock함수를 썼는데 mock함수를 쓰지 않고 테스트 할 수 있는 방법이 있을까요?
- 테스트 코드를 작성할 때 기능 구현 사항을 보고 어느 정도 큰 그림은 보고 시작하는데 이 시간이 생각보다 오래 걸리는거 같습니다. (어떤 클래스를 쓸지, 어떤 메서드를 만들지 등을 생각) 리뷰어님은 보통 어떤 식으로 테스트 코드를 작성하는지 궁금합니다.

### 고민할 사항
- 현재 CarRace 클래스의 start 메서드에서 View 인스턴스를 사용하고 있는데 이 방법이 좋은 방법이 아닌 거 같아 이 부분은 조금 더 고민해보도록 하겠습니다.

2023-07-27 23:41 UTC, pocojang requested changes
안녕하세요
광민님

늦어서 죄송합니다.
다음부터는 쾌속의 리뷰를 진행하도록 하겠습니다!!

## 피드백

일반적인 코드는 그래도 피드백할 부분이 여러가지 있었지만 테스트코드 정말 잘 작성하셨네요.
어딘가에서 참고를 하면서 공부하신건지 경험이 있으신건지 딱히 피드백 드릴게 없었습니다.


## 고민했던 부분

### 1. 자동차 경주는 5회로 고정한다를 테스트할 때 5번 함수가 호출된다를 테스트하기위해 mock함수를 썼는데 mock함수를 쓰지 않고 테스트 할 수 있는 방법이 있을까요?

음 질문의 의도를 제가 파악하지 못한 것 같기도해요.
테스트라는 것 자체가 가상의 `Mock`을 이용하는게 아닐까요?
다시 한번 질문해주시면 확인해볼게요!

### 2. 테스트 코드를 작성할 때 기능 구현 사항을 보고 어느 정도 큰 그림은 보고 시작하는데 이 시간이 생각보다 오래 걸리는거 같습니다. (어떤 클래스를 쓸지, 어떤 메서드를 만들지 등을 생각) 리뷰어님은 보통 어떤 식으로 테스트 코드를 작성하는지 궁금합니다.

일단 테스트 코드부터 작성해놓고 그 테스트 코드가 동작하도록 코드를 구현하는게 가장 정석에 가까운 것 같아요 🥇 
저는 공부할때는 그렇게 하려는 편입니다.

---

그럼 코드 수정 후 다시 리뷰 요청해주세요~!

2023-07-27 23:41 UTC, pocojang commented on docs/REQUIREMENTS.md
> +[O] 사용자가 잘못된 입력 값을 작성한 경우 프로그램을 종료한다.
[O] 보다는 마크업 문법을 이용해서 아래와 같이 하는 것을 추천드려요!

```
- [x] 완료
- [ ] 진행 중
```

2023-07-27 23:41 UTC, pocojang commented on src/constants/index.js
> +export const RACE_LAP_LIMIT = 5;
이정도라면 주석이 아니라 네이밍에 포함해도 되지 않을까요?

2023-07-27 23:41 UTC, pocojang commented on src/domain/car.js
> +    this.#distance += 1;
확장성을 위해 기본 값은 `1` 인자로 받아서 `1`이상의 값을 할당할 수 있게하면 더 좋겠군요!

2023-07-27 23:41 UTC, pocojang commented on src/domain/carRace.js
> +    const sortedParticipants = [...this.#participants].sort(
새로나온 신상도 있답니다 ㅎㅎ
[Array.prototype.toSorted()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted)

2023-07-27 23:41 UTC, pocojang commented on src/domain/carRace.js
> +    this.#winners = sortedParticipants.filter(
`winners`를 뽑는 더 효율적인 방법이 없을까요?

2023-07-27 23:41 UTC, pocojang commented on src/domain/carRace.js
> +    return result;
```suggestion
    return getStringFromArray(names);
```

바로 반환해도 되겠는걸요?!

2023-07-27 23:41 UTC, pocojang commented on src/utils/common.js
> +}
EOL이 반복되네요!

2023-07-27 23:41 UTC, pocojang commented on src/validation/index.js
> + export const checkOverStringLength = (value, length, message = `${length}자리 이하만 입력 가능합니다`) => {
받는 인자가 많아서 사용하는 곳에서는 순서의 강제성때문에 헷갈리지 않을까요?

2023-07-27 23:41 UTC, pocojang commented on src/validation/index.js
> + export const checkEmptyString = (value) => {
`value`가 없을때도 고려하셔야겠어요

2023-07-27 23:41 UTC, pocojang commented on src/view/index.js
> +      console.log(`${name} : ${'-'.repeat(distance)}`);
repeat 👍

2023-07-27 23:41 UTC, pocojang commented on src/utils/common.js
> +        return
요 처리는 좋지 않아보이는데요?
함수의 사용자가 자신이 잘못된 값을 넘겨도 모를 수 있겠어요

2023-07-31 12:01 UTC, KwangMin-bright-Moon commented on src/domain/carRace.js
> +    const sortedParticipants = [...this.#participants].sort(
toSorted 매소드를 적용했는데 node 최신 버전에서는 인식하는데 jest에서는  toSorted is not a function 이라고 type error 가 뜨네요😢

2023-07-31 12:01 UTC, KwangMin-bright-Moon commented
리뷰어님 피드백 반영했습니다:)
winner를 구하는 더 효율적인 방법은 떠오르지가 않네요ㅠㅠ 최장 거리를 구해서 그 최장거리와 비교하면 가독성은 좋아 질 거 같은데 더 효율적인 방법은 찾지 못했습니다.

2023-07-31 23:28 UTC, pocojang commented on src/domain/carRace.js
> +    const sortedParticipants = [...this.#participants].sort(
아이고.. 그렇겠네요 😢

2023-07-31 23:36 UTC, pocojang approved these changes
스텝1은 이정도면 훌륭하기떄문에 이만 머지하겠습니다!

- `Jest`에 더 많은 API를 사용해보는게 어떨지
- `Class`를 많이 활용했는데 `Private`을 의미있게 사용했는지 생각해보시면 좋겠습니다!

그럼 스텝2에서 만나요 👋

2023-07-31 23:36 UTC, pocojang commented on src/validation/errorMessage.js
> +  CAR_NAME_LIMIT: `자동차 이름은 ${CAR_NAME_LENGTH_LIMIT}자리까지 가능합니다.`,
좋네요! 👍

2023-07-31 23:36 UTC, pocojang commented on src/domain/car.js
> +  move = (number, distance = 1) => {
👍

2023-07-31 23:36 UTC, pocojang commented on src/validation/index.js
> +  if (!value || !value.toString().trim().length) {
첫번째 검사절처럼 두번째 검사절에도 `isEmpty`를 사용해도 될 것 같은데요..?

2023-07-31 23:37 UTC, merged