[클린코드 5기 나호석] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #161
Opened 2023-07-25 17:34 UTC by HoseokNa

안녕하세요 리뷰어님!
자동차 경주 미션 첫 번째 PR 제출합니다.
테스트 코드를 작성하면서 하니까 빨간색에서 초록불로 변하는 걸 보는 재미도 있었는데
반면 아직 낯선 부분도 있다보니 작성시 어려움을 느낄 때도 많았습니다 ㅎㅎ
마지막 예외처리할 때는 테스트 코드 없이 바로 기능 구현을 했습니다.....
부족하지만 잘 부탁드리겠습니다!

# 미션 진행시 목표

- 기능 요구 사항 달성.
- 테스트 코드 먼저 작성 후 기능 구현.
- 작은 단위로 커밋 남기기.

# 결과 화면

https://github.com/next-step/js-racingcar/assets/16220817/e2117606-92fa-4a77-86be-67cfdf451791

# 개발 과정

- 우선 `기능 요구 사항`에 있는 리스트를 보면서 제가 개발해야할 내용을 고민했습니다. 주어진 요구 사항을 만족시키기 위해 조금 더 작은 단위로 나누고 해당 과제들을 해결하는 식으로 작업했습니다.
- 지난주 세션에서 들은 내용으로는 핵심을 포함한채로 중요한 내용부터 개발해나가는걸로 배웠습니다. 자동차 경주 미션은 우승을 출력하는게 핵심이였지만 입출력이 포함되는 부분들이 있다보니 `Car` -> `RacingGame` -> `GameSimulator` 순으로 개발을 진행했습니다.
- `RacingGame`과 `GameSimulator`를 분리했었던 이유는 게임 관련 로직과 입출력 부분을 분리하고 싶었습니다. 테스트 코드 작성에도 어려움이 있어서 `RacingGame`에서는 입출력과 관계 없이 개발을 진행할 수 있었습니다.
- 온보딩 미션에서는 테스트 확인을 toBe 로 다 확인을 했었는데 이번에는 여러가지 테스트 상황이 있어서 주로 GPT를 활용해서 작업을 했습니다.

# 질문 사항
- 실행시 결과가 달라지는 함수 테스트 방법
  - 요구사항 중에 1 ~ 9 사이에 랜덤 숫자를 확인하는 내용이 있었습니다. 해당 함수를 구현하기 위해서는 테스트 코드를 먼저 작성을 했어야 했는데 감이 잘 안잡혔습니다.
  - 알아본 내용으로는 결과값을 임의의 값으로 지정해서 테스트를 진행하는 방식이 있어서 [해당 내용](https://github.com/next-step/js-racingcar/commit/25a9cb3431397a947da41b058e98c3a240ce3ff4)으로 적용했는데 괜찮을지 궁금합니다.
  - 또 이렇게 랜덤값이 로직이 포함 되다 보니 나중에 우승자 관련 테스트를 작성하려고 할 때 단독 우승자와 여러 우승자를 구분해서 작성하기가 어려웠습니다.
- `GameSimulator` 의 필요성
  -  `RacingGame`과 `GameSimulator`를 나누어서 작업을 했는데 적절한 분리였는지 궁금합니다.
  - 막상 분리하고 작업을하니 불편한 점도 있었는데, 예를 들어 `GameSimulator`에서 라운드 진행시 출력 내용을 테스트한다고 했을 때 `GameSimulator`를 사용하는 곳에서는 차량들의 정보를 알 수가 없어 테스트 코드를 작성하기가 어려웠습니다. 만약에 `RacingGame`에서는 `getCars`라는 메소드가 있어서 가져올 수가 있었는데 `GameSimulator`에서도 `getCars`라는 메소드를 만들어서 사용했면 됐을까요?
  - 현재는 `Car.printInfo` 메소드로 출력하도록 구현했습니다.
- 테스트를 다루는 범위
  - 테스트 코드를 어디까지 작성하는게 좋을지 고민입니다.
  - 예를 들어 자동차가 움직여서 거리가 1 증가를 한다고 했을 때, 해당 케이스에서는 0 -> 1 로 증가하는 테스트 케이스를 작성하면 충분할지, 아니면  1 -> 2, 2 -> 3 같이 추가적인 케이스를 작성해야할지 고민이 됐습니다.
- 커밋 단위
  - 작은 단위로 커밋을 남기다 보니까 이번 미션에는 90개가 넘었는데, 혹시 너무 짧게 잡은건지 리뷰어님이 보시기에 불편한지 궁금합니다.

2023-07-26 14:23 UTC, JunilHwang requested changes
안녕하세요 호석님! 자동차 경주 미션을 함께하게 된 리뷰어 황준일입니다 😁🙇‍♂️
전체적으로 코드를 깔끔하게 작성해주신 것 같아요. 그래서 코드를 읽기가 무척 수월했답니다 👏👏
몇 가지만 보완하면 더 좋을 것 같은데요,

1. Car에서 출력을 해주는게 맞을까?
2. GameSimulator에서 자동차 이름을 검증하는게 맞을까?
3. 요구사항의 변경에 대응하기 쉬운 구조인가?

이렇게 3가지 입니다.

저는 특히 3번이 제일 중요하다고 생각하는데요,

가령 지금은 "매 라운드마다 랜덤 숫자를 만들어서 숫자가 5 이상이면 전진한다" 라는 규칙이 있어요.
그런데 이 규칙이 달라진다면 어떻게 될까요?
극단적으로 가보자면,

한 번에 사용자가 원하는 수 만큼 자동차 경주 게임을 진행시킬 수 있고,
각 자동차 경주 게임의 게임 규칙이 다르다면 어떨까요?
아예 사용자가 게임 규칙을 입력해서 진행시킨다면 어떨까요?
혹은 한 10개의 게임 규칙이 미리 만들어져있고, 이 중에 원하는걸 선택하게 한다면 어떨까요?

이렇게 요구사항을 변형해보면서 내가 작성한 코드가 이런 변화에 대응하기 쉬운지 고민해보시면 좋을 것 같아요 ㅎㅎ

지금은 거의 모든 코드가 Math.random에 의존적이다보니, 규칙이 변경되면 모든 테스트 코드가 변경되어야합니다. 배보다 배꼽이 더 커진 상황인거죠.

***

이제 질문에 대한 답변을 드리자면,

> 실행시 결과가 달라지는 함수 테스트 방법

이건 앞에서 이야기한 내용들(요구사항이 변경되면 어떻게 해야 좋을까?)에 대해 조금 더 고민해보시면 쉽게 답을 찾으리라 생각합니다!

> GameSimulator 의 필요성

이 부분은 무척 잘 해주신 것 같아요.
일종의 MVC Pattern 이라고 생각되는데,
Car, RacingGame 등은 Model(Domain)의 역할을 수행 중이고,
GameSimulator는 Viewer + Controller의 역할을 수행 하는 모습입니다.

그런데 여기서 GameSimulator가 약간의 Model의 역할도 수행하고 있고
Car 또한 Viewer의 역할을 수행중입니다.

이를 완전히 분리해주면 훨씬 테스트하기도 수월하고 관리하기도 수월할 것 같아요!

> 테스트를 다루는 범위

이게 특히 GameSimulator를 분리하는거랑 연관이 있을 것 같아요. 저는 주로 "도메인"에 대해서만 테스트를 합니다. 이건 어디서든 쓰일 수 있는 코드거든요!

가령, 현재 코드를 활용해서 Web UI 로 만든다고 하면 어떤 것들을 활용할 수 있을까요?
이에 대한 관점으로 고민해보면 좋을 것 같아요 ㅎㅎ
어플리케이션 전체 흐름에 대해서 테스트하고 싶다면 지금과 같은 방식보단 cypress나 storybook을 활용하는 방법이 있답니다!

> 커밋 단위

음 저의 경우 커밋을 보는 사람 입장을 많이 고려하는 것 같아요. 유의미한 변경사항을 커밋으로 남기는게 좋지 않을까요? 일단 정리해보자면,

1. 커밋을 작은 단위로 관리하는게 큰 단위로 관리하는 것 보단 좋다고 생각합니다.
2. 그런데 너무 작은단위로 유지할 경우 커밋을 보는 사람 입장에서 혼란스러울 수 있어요. 가령, 현재 코드에 버그가 있고, 당사자가 부재 중일 때 (퇴사를 했거나 휴가 중이라거나) 어떤 커밋으로 돌아가서 확인해야할지 막막할 수 있지 않을까요?
3. 결론은, 유의미한 변화를 커밋으로 남기는게 제일 좋다고 생각합니다.

이상입니다!

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/utils/getRandomNumber.test.js
> +  });
음... 이 테스트는 의미 있는 테스트가 아닌 것 같아요.

차라리 getRandomNumberFromZeroToNine으로 대충 10000개 정도의 값을 만들어서 전부다 0 ~ 9 사이의 값이 나오는지만 확인해보면 되지 않을까 싶기도 하네요!

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/Car.test.js
> +  });
만약에 전진 조건이 바뀌면 어떻게 해야 좋을까요?

가령 자동차 경주 게임을 한 번에 5개를 실행하는데, 5개 모두 전진 조건이 다른거죠 ㅎㅎ

위와 같은 요구사항이 생겼을 때 현재 코드는 어떤식으로 대응해야 좋을지 고민해보시면 좋을 것 같아요!

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/Car.test.js
> +    test('조건을 만작하고 자동차가 전진시 주행거리의 값이 1 늘어난다.', () => {
"만작하고" => "만족하고" 로 변경되어야할 것 같아요!

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/Car.test.js
> +  });
출력에 대한 부분은 앞선 리뷰들을 참고해주세요!

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/RacingGame.test.js
지금 전체적으로 모든 테스트가 Math.random에 의존적인 상황이네요! 그래서 목킹이 굉장히 많이 보이는데, 목킹을 하지 않고 테스트할 수 있는 방법은 없을까요?

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/GameSimulator.test.js
> +    });
GameSimulator에서 자동차 이름의 길이를 검증하는 모습이 뭔가 어색하게 느껴지네요! 이건 별도의 도메인으로 분리해야 하지 않을까 싶어요 ㅎㅎ

2023-07-26 14:23 UTC, JunilHwang commented on __tests__/GameSimulator.test.js
> +      });
round도 입력받는다고 가정해보면 어떨까요?

2023-07-26 14:50 UTC, HoseokNa commented on src/utils/getRandomNumber.js
> +};
기존 함수는 0 ~ 9 까지 고정된 함수였는데
제시 해주신 함수는 제한 범위를 인자로 받아 변경된 상황에서도 활용할 수 있겠네요!
감사합니다!

2023-07-26 14:51 UTC, HoseokNa commented on src/utils/printMessage.js
> +export const printMessage = (message) => console.log(message);
헉... 그러네요. 수정하겠습니다!

2023-07-26 14:52 UTC, HoseokNa commented on src/GameSimulator/utils.js
> +};
구현했을 때는 validate 부분을 외부로 분리하자 라고 생각을 했었는데
말씀해주신 것처럼 도메인 내용이 포함되니 util로 분리하기보다는 같이 포함되는게 맞을 것 같습니다.
수정하겠습니다!

2023-07-26 14:58 UTC, HoseokNa commented on src/GameSimulator/index.js
> +    this.#racingGame = new RacingGame(carNames.map((name) => new Car(name)));
CarName으로 추출할 생각을 못했는데
해당 클래스에서 이름 관련된 validate를 처리해서 역할을 분리하는걸까요?
고민해서 반영해보겠습니다!

2023-07-26 14:59 UTC, HoseokNa commented on src/GameSimulator/index.js
> +    carNames.forEach((name) => validateCarName(name));
반영하겠습니다!

2023-07-26 15:03 UTC, HoseokNa commented on src/Car/index.js
> +  }
개발 당시 테스트 코드를 작성할 때 이동거리 정보를 가져올 수 없는 상황이라
차량에서 출력을 하게 됐었는데
구조를 다시 확인해서 해당 클래스에서는 데이터를 반환 하도록 수정해보겠습니다.

2023-07-26 15:04 UTC, HoseokNa commented on src/GameSimulator/index.js
> +  }
다른 곳에서 해주는게 맞을 것 같습니다! 고민해보겠습니다.

2023-07-26 15:09 UTC, HoseokNa commented on src/GameSimulator/utils.js
> +  }
좋습니다!

2023-07-26 15:11 UTC, HoseokNa commented on src/RacingGame/index.js
> +  }
생각했었던건 제시해준 로직이였는데 잘못 구현을 했었네요.
꼼꼼하게 봐주셔서 감사합니다!

2023-07-26 15:12 UTC, HoseokNa commented on __tests__/utils/splitStringByComma.test.js
> +  describe("문자열일이 ',' 기준으로 파싱 된 후 배열로 반환 된다.", () => {
헉... 수정하겠습니다.

2023-07-26 15:13 UTC, HoseokNa commented on __tests__/utils/splitStringByComma.test.js
> +      expect(spliited.every((string) => array.includes(string))).toBe(true);
`toEquals`로 편리하게 사용할 수 있겠네요.
감사합니다!

2023-07-26 15:21 UTC, HoseokNa commented on __tests__/utils/printMessage.test.js
> +});
커링을 활용하면 함수를 재사용하거나 리팩토링하기 쉽다고 알고 있습니다.

제시해준 코드로 정의를 하면
현재는 `console.log`에 spy를 심어서 테스트를 하고 있는데
커링을 활용하면 spy를 넣을 필요 없이 mock 함수를 넣어서 테스트를 진행할 수 있을 것 같습니다.

제가 이해한게 맞을까요?

2023-07-26 15:23 UTC, HoseokNa commented on __tests__/utils/getRandomNumber.test.js
> +  });
보통 이런 함수들을 테스트 하려면 많이 실행해서 잘못된 값이 없는지를 확인해야할까요?
아니면 테스트 코드를 작성을 안하는게 나을까요? 😭

2023-07-26 15:24 UTC, HoseokNa commented on __tests__/Car.test.js
> +  });
넵 답글 내용과 기존 코멘트들 종합하여 고민해보도록 하겠습니다.
감사합니다!

2023-07-26 15:24 UTC, HoseokNa commented on __tests__/Car.test.js
> +    test('조건을 만작하고 자동차가 전진시 주행거리의 값이 1 늘어난다.', () => {
꼼꼼하게 봐주셔서 감사합니다! 수정하겠습니다.

2023-07-26 15:31 UTC, HoseokNa commented on __tests__/RacingGame.test.js
고민해보고 피드백 때 반영해보겠습니다 🤔

2023-07-26 15:33 UTC, HoseokNa commented on __tests__/GameSimulator.test.js
> +      });
반영하겠습니다!

2023-07-26 16:05 UTC, JunilHwang commented on src/GameSimulator/index.js
> +    const winningCarNames = this.getWinningCarNames().join(',');
음.. 저는 이런 경우에는 오히려 split, join 들이 더 직관적으로 쓰이고 있지 않나? 라는 생각을 해요 ㅋㅋ 대신 콤마(,)를 상수로 만들어서 관리할 것 같습니다.

2023-07-26 16:06 UTC, JunilHwang commented on __tests__/utils/printMessage.test.js
> +});
맞습니다 ㅎㅎ 
그리고 테스트 여부를 떠나서, Viewer에서 console.log가 아닌 다른걸 사용할 수도 있으니까요! 아예 어플리케이션의 트리거 역할을 하는 영역에서 console.log 대신 다른걸 주입해서 사용할 수도 있고여!

이렇게 인터페이스만 뚫어놓고 사용하면 유연해진다고 생각합니다.

2023-07-26 16:07 UTC, JunilHwang commented on __tests__/utils/getRandomNumber.test.js
> +  });
테스트가 유의미한가? 라고 했을때 크게 의미있는 테스트는 아닌 것 같아요 ㅎㅎ

2023-08-04 20:28 UTC, HoseokNa commented
안녕하세요 준일 리뷰어님!
피드백 반영이 너무 늦었네요 😭 죄송합니다! ㅠㅠ

저번에 남겨주신 답변과 코멘트를 참고해서 반영했습니다.
`reduce`를 활용해서 최대값을 구하는거나 `Car.of` 같은 메소드를 활용하니
코드가 더욱 간결해진 것 같아 좋았습니다 👍
특히 `each`를 활용하니 여러 테스트를 한번에 처리할 수 있어서 많이 편했습니다.
꿀팁 감사합니다!!

그리고 랜덤 숫자를 확인하는 테스트 코드는 제거하였고
split하는 util 함수도 제거한 후 코드로 바로 사용했습니다.

마지막으로 피드백 반영하면서 고민이 됐던 부분이 있었는데

**1. 주행 조건(랜덤 숫자) 처리하기.**
- 기존 PR에서 테스트 코드에 `Math.random` mock을 많이 사용했었습니다.
- 그렇게 했던 이유는 여러 조건들을 테스트하기 위함이였습니다. (자동차를 전진 시키기 위해서는 랜덤 숫자를 4이상이여야 한다.)
- 그래서 만약에 조건이 변경 된다면 관련된 코드들을 모두 다 수정해야하는 의존도가 높은 코드였었습니다.
- 그래서 피드백을 반영하고자 고민을 했는데
- 우선 현재 요구사항인 랜덤 숫자가 4이상일 때 전진할 수 있는 테스트는 `getRandomInRange` 모킹해서 canMoveForward 값이 true, false가 되는지 확인 했습니다.
- 대신에 다른 곳에서 전진 관련 테스트가 필요할 때 `Math.random`이 아닌 `canMoveForward`를 모킹해서 처리했습니다.
- 이렇게 작성하면 전진 조건이 변경되더라도 전진 조건 테스트 부분만 수정하고 나머지는 `canMoveForward`의 `boolean` 값을 사용하니 영향을 덜 받을 수 있겠다고 생각했습니다.
- 이런 방식으로 해결해도 괜찮을지 궁금합니다!

**2. 자동차 정보 출력 테스트.**
- 기존 PR에는 Car 클래스에서 정보를 출력 했었습니다.
- 그랬었던 이유는 테스트 코드를 작성하면서 `GameSimulator`에서 자동차 정보 테스트 코드를 작성하기 어려워서 정보 접근이 바로 가능한 Car 클래스에서 처리를 했었습니다.
- 그래서 피드백 반영에서는 자동차 정보 출력을 `GameSimulator`에서 처리했습니다.
- 대신에 테스트 범위를 기존에는 출력 문구가 올바르게 나왔는지를 확인했었는데 (자동차 이름과 이동거리)
- 지금은 하나의 round가 종료 됐을 때 `printCarStatus`라는 함수가 차량의 숫자만큼 호출됐는지만 확인했습니다.
- 우선 현재 테스트 코드에서 차량별로 어떤 값이 나오는지 확인하기가 어려웠고
- 조금 더 생각해보니 프론트로 따지면 특정 UI라도 볼 수 있어서 해당 부분까지는 테스트 코드를 적용안해도 되지 않을까 😱 라는 생각에 함수 호출만 확인했습니다.
- 이런 출력 관련된 부분은 호출 정도만 확인해도 괜찮을지 궁금합니다.

3. `createMessageViewer` 활용
- 코멘트에 남겨주신 `createMessageViewer`를 활용해봤는데 적절하게 사용한건지 궁금합니다.
- `GameSimulator`를 생성할 때 `MessageViewer`를 받도록 해서 `createMessageViewer`에 `console.log`를 담아서 생성을 했습니다.
- `createMessageViewer` 파일의 위치를 `src/utils`에 위치를 시켰는데 따로 분리해야할 것 처럼 느껴지긴 했는데 util 함수인 것 같아서 우선 지금 디렉토리에 위치 시켰습니다.

**4. [promise 방식으로 사용할 수도 있답니다](https://github.com/next-step/js-racingcar/pull/161#discussion_r1274964220)**
- 이 코멘트에 대해 조금 더 자세한 설명을 들을 수 있을까요?
- 링크 된 문서를 확인했을 때 예시로 나온 코드가 지금이랑 비슷한거 같아서
- promise 방식이란 표현을 제가 잘 이해 못한 것 같은데 부가 설명을 조금만 더 해주시면 감사하겠습니다!

2023-08-05 08:31 UTC, JunilHwang approved these changes
안녕하세요 호석님!
피드백 반영 잘 해주셨네요 👏👏

전체적인 피드백을 종합해보면 다음과 같습니다.

## 1. 도메인과 무관한 상수가 어째서 테스트 스펙에 쓰이는가
Car 내부적으로는 상수를 사용했기 때문에 작성한 사람은 이 테스트가 당연해보일 수 있어요. 그런데 Car의 작성자가 아닌, 즉 호석님이 아닌 다른 사람이 테스트 코드를 봤을 때 이 상수가 대체 뭐야? 라는  생각이 들지 않을까요? 이런 경우에는 상수를 어떻게 관리해야 좋을까요?

## 2. 테스트 목킹 최대한 제거하기
사실 마지막 단계에 있는 내용이긴 한데, 가령 우승자가 여러명인 경우에 대한 테스트 케이스는 우승자가 여러명이 나올 수 있는 input 자체가 없는 상태입니다. 이 테스트를 보는 사람 입장에서는 테스트를 토대로 코드의 결과를 예측하는게 불가능하지 않을까요? 이런 테스트 극단적으로 이야기하면 있으면 오히려 악효과라고 생각해요. 그럼 어떻게 기존 코드를 개선해야 예측 가능한 테스트를 작성할 수 있을까요?

## 3. GameSimulator의 역할
이 클래스는 지금 "출력"을 담당하는 부분과 "도메인"을 담당하는 부분을 둘 다 수행 중입니다. 이것도 나눠서 관리해주면 좋을 것 같아요!

## 4. 전진조건이 완전히 달라지거나 많아진다면?
현재 Car의 경우 자체적으로 관리하는 변수도 아닌 아예 외부 상수에 전진조건이 의존적인 상태입니다.
가령 전진조건이

"현재 millsecond % (1 ~ 100 사이의 랜덤 숫자) 의 값이 49 이상이면 전진한다 (ex: (new Date().getMilliseconds() % Math.random() * 100) > 500)"

이런 형태로 바뀐다거나 추가된다면, 수정되어야 하는 코드가 굉장히 많아보입니다.

가령 전진조건 10개가 있고, 이를 전진할 때 마다 취사선택 해야 한다면 어떻게 해야 좋을까요?

***

이제 질문에 대한 답변을 드리자면,

> 1. 주행 조건(랜덤 숫자) 처리하기.

이전보다는 확실히 더 유연해졌지만, 결국에 한 가지 전진조건에 강하게 결합된 모습은 그대로인 것 같아요.
조금 더 힌트를 드리자면 car에서 전진조건을 알아야할 필요가 있을까요? true/false에 따라서 전진을 하기만 하면 되는게 아닐까요?

> 2. 자동차 정보 출력 테스트.

이것도 앞에서 이야기한 것과 비슷한데요, GameSimulator가 출력을 담당하면 안될 것 같습니다. 혹은 오직 출력만 담당하게 하고 도메인 로직만 따로 수행하는 친구를 더 만들어줘야할 것 같아요!

> 3. https://github.com/next-step/js-racingcar/pull/161#discussion_r1274964220 이 코멘트에 대해 조금 더 자세한 설명을 들을 수 있을까요? 링크 된 문서를 확인했을 때 예시로 나온 코드가 지금이랑 비슷한거 같아서 promise 방식이란 표현을 제가 잘 이해 못한 것 같은데 부가 설명을 조금만 더 해주시면 감사하겠습니다!

지금은 직접 Promise를 정의하고 있는데, node api가 이미 promise를 반환해주는 i/o를 제공하고 있다는 의미였습니다 ㅎㅎ
"직접 작성하기 보다 이미 만들어져있는걸 사용하면 어떨까?" 입니다!

***

일단 이번 단계는 여기서 마무리하도록 하겠습니다. 이번에 남긴 피드백은 다음 단계 진행하면서 적용해보시면 될 것 같아요! 고생하셨습니다 😁

2023-08-05 08:31 UTC, merged