[클린코드 5기 김현규] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #163
Opened 2023-07-26 10:56 UTC by gusrb3164

안녕하세요 자동차 코드 리뷰 요청드립니다!

1. 처음에 validation하는 로직들을 controller에 작성했다가 util로 분리를 했는데요, 자동차 이름을 검사하는 것을 로직은 자동차와 컨트롤러중 어디에서 작성하는 것이 적절한가요?
2. console과 관련된 로직은 모두 view로 보는것이 맞나요?

2023-07-28 14:43 UTC, yujo11 requested changes
안녕하세요 현규님~ 

만나서 반갑습니다~ 리뷰가 조금 늦어진 점 죄송합니다 ㅠㅠ

전체적으로 코드가 깔끔하게 작성되어 있어서 코멘트 남길 내용이 많지 않았네요 👍 👍 👍 

질문으로 남겨주신 부분들은 MVC 패턴으로 작성하려고 하셨다는걸 가정하고 답변을 남겨보겠습니다

>처음에 validation하는 로직들을 controller에 작성했다가 util로 분리를 했는데요, 자동차 이름을 검사하는 것을 로직은 자동차와 컨트롤러중 어디에서 작성하는 것이 적절한가요?

상황마다 다를거 같습니다. 자동차 객체 내에 있어도 좋을거 같고, 현규님이 작성하신 것처럼 util에 있어도 좋을거 같아요.

그런데 지금처럼 util에 위치하면서 특정 도메인에 종속된 이름과 동작을 하는 것은 지양해야 할 필요가 있다고 생각합니다.

일반적으로 util은 도메인 로직과는 연관이 없는 util성 함수들을 정의하는데 많이 사용하는데요. `isExistEmptyNameCars`이나 `isValidCarNamesLength` 같은 경우는 범용적으로 쓰인다는 느낌보다는 "자동차 경주"라는 도메인에 종속된다는 느낌이 드네용

React Component가 예시이긴 하지만 결이 비슷한 얘기라서 아래 영상도 추천드리고 싶습니다!

- https://www.youtube.com/watch?v=fR8tsJ2r7Eg&t=10s

>console과 관련된 로직은 모두 view로 보는것이 맞나요?

일반적인 MVC 패턴을 생각했을 때 사용자에게 보여지는(출력되는)부분은 View에 위치하는 것이 적절하다고 생각합니다.

>private method는 test code로 굳이 작성하지 않아도 될까요?

저는 작성하지 않아도 된다고 생각합니다.

테스트 코드를 작성하는 것은 현규님이  어떤 "의도"를 가지고 코드를 작성했고, 그 "의도"대로 동작하는 것을 검증하는 것인데요.

private method의 경우 단독으로 외부에서 쓰이지 않는다는 "의도"를 가지고 작성하셨을거 같아요. 그렇기 때문에 직접적으로 private method의 동작을 검증할 필요는 없다고 생각합니다. 테스트가 필요하다면 public method를 통해 간접적으로 하는 방법이 있을거 같네요!

아래 사이트도 참고해 보시면 좋을거 같습니다 ㅋㅋ
- https://shoulditestprivatemethods.com/

---

미션 진행하느라 고생 많으셨습니다 현규님 !

2023-07-28 14:43 UTC, yujo11 commented on src/index.js
> +  console.log('실행 결과');
이런 콘솔은 불필요해 보이네요

2023-07-29 08:02 UTC, gusrb3164 commented on src/utils/splitByComma.js
> +};
trim하는 로직을 다른 util로 분리해보겠습니다!

2023-07-29 08:02 UTC, gusrb3164 commented on src/view/printRacingInfo.js
> +  console.log();
줄바꿈을 위해 추가했었는데 한개의 console.log로 처리할 수 있을 것 같네요

2023-07-29 08:03 UTC, gusrb3164 commented on src/utils/__tests__/isValidCarNamesLength.test.js
> +  test('자동차 이름은 5자 이하만 가능하다.', () => {
위에서 도메인을 분리하면서 util의 재사용성을 넓히기 위해 길이또한 인자로 받게 수정했습니다!

2023-07-29 08:04 UTC, gusrb3164 commented on src/utils/isExistEmptyNameCars.js
자동차가 아니라 문자열들의 공백을 체크하는 변수명으로 수정해봤습니다

2023-07-29 08:08 UTC, gusrb3164 commented
질문에 대해 잘 이해했습니다! 설명 감사드립니다. 
공유주신 private 사이트도 예전에 본 기억이있는데 잊고있었네요 ㅋㅋ
앞으로는 util에는 도메인이 관여하지 않도록 신경써야겠네요!

2023-07-30 11:06 UTC, yujo11 approved these changes
고생하셨습니다 현규님! 다음 step에서 다시 뵈어요~~ 👍 👍 👍

2023-07-30 11:06 UTC, merged