[클린코드 6기 변광진] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #233
Opened 2024-04-29 08:36 UTC by Quska45

안녕하세요 리뷰어님!
갑자기 회사 바쁜 일정이 좀 생겨서 아직 마무리가 덜됐지만 pr 드립니다.
일단 현상태는 기능에 대한 구현은 했지만 테스트 코드를 작성하지 못한 상태 입니다.
클래스를 2개(Car, Game) 만들었습니다. 
먼저 Car는  말그대로 자동차에 해당하는 클래스 입니다.
다음으로 Game은 게임진행을 위해 필요한 클래스를 모아놓은 클래스 입니다.
인지 하시고 검토 해주시면 좋을 것 같습니다.

1. 도메인 로직과 ui 로직?
 - 어디까지가 도메인 로직이고 ui 로직인지 잘 판단이 안서는 것 같습니다.
 - 제가 느끼기엔 이번 과제에 도메인 이라고 부를만한게 어떤 것인지 잘 모르겠습니다.

2. 테스트의 단위는 요구사항 인지, 메서드 단위 인지, 혹은 다른 무언가 인지?
- 테스트를 짤 떄 단위를 어떻게 가져가야 하는지 잘 모르겠습니다.
- 회사에서도 항상 고민하지만 해서 하지만 결국엔 그냥 대충 해버리게 되는 부분 입니다.
- 추천 하시는 방법에 대해서 알려주시면 좋을 것 같습니다.

2024-05-01 08:18 UTC, notPotter requested changes
안녕하세요 광진님! 
코드 리뷰가 늦었습니다! 고민해주신 부분과 전반적인 피드백먼저 알려 드리도록 할게요!

### 고민해주신 부분에 대하여

> 도메인 로직과 ui 로직?
어디까지가 도메인 로직이고 ui 로직인지 잘 판단이 안서는 것 같습니다. 제가 느끼기엔 이번 과제에 도메인 이라고 부를만한게 어떤 것인지 잘 모르겠습니다.
> 

 `Car` 와 `Game` 클래스에 속하지 않아도 되는 코드들이 있을 거 같습니다. 하나 예시를 들자면 자동차의 이름을 검증하는 `getCarsByCarsString` 있습니다. 

- string을 `,` 기준으로 나눠주는 기능
- string의 존재 여부 및 공백 여부를 확인하는 기능
- string의 길이를 적절한지 확인하는 기능

간단하게 바꿔보면 도메인 로직과 결합되어있지 않아도 되는 기능들인 것 같습니다. 

> 테스트의 단위는 요구사항 인지, 메서드 단위 인지, 혹은 다른 무언가 인지?
테스트를 짤 떄 단위를 어떻게 가져가야 하는지 잘 모르겠습니다.
회사에서도 항상 고민하지만 해서 하지만 결국엔 그냥 대충 해버리게 되는 부분 입니다. 추천 하시는 방법에 대해서 알려주시면 좋을 것 같습니다.
> 

모든 곳에 적용할 수 있는 완벽한 방법은 없지만, 저는 테스트의 단위는 기본적으로 요구사항을 만족하는지 테스트하는 거라고 생각합니다.

그래서 기능 요구사항을 굉장히 상세하게 적어 놓는 편입니다. 기능 요구사항을 상세하게 적어두면, 문서화의 효과를 넘어서서 테스트와 구현 모두 고려하면서 개발하기에 더 좋은 것 같습니다. 

어떤 요구사항은 메서드를 테스트하는 것으로 충분할테고, 그렇지 않은 기능 요구사항도 있을 것입니다! 기능 요구사항 적어두고, 구현하면서 점점 더 상세하게 발전 - 변경 시켜보시면 좀 더 테스트 단위를 지정하시기 편리할 것 같습니다!

### 피드백

- **고차함수 활용**
    
    `for` , `forEach` 문이 굉장히 많았던 것 같아요. 고차함수를 사용한다면 단순히 **“반복을 하겠다”** 외에 더 많은 의도를 드러낼 수 있어요.
    `filter` 를 사용한다면, 조건에 맞는 요소만 걸러내겠다는 의도를 드러낼 수 있고, `every` 를 사용한다면 요소 전체가 조건에 맞는 지 확인하겠다는 의도를 드러낼 수 있어요. 고차함수를 적극 사용해보시길 바랍니다!
    
- **기능 요구사항과 테스트**
    
    코멘트에도 남겨뒀지만, 기능 요구사항이 제목 - 내용이 일치하지 않는 경우, `자동차 경주가 이뤄질 수 있도록 하는 게임이라는 클래스를 만든다.` 어떤 걸 구현해야하는지, 테스트해야하는지 확인하기 어려운 내용들이 많았어요.
    그렇다 보니 테스트도 해피케이스에 대한 경우만 진행하고 있는 것 같아보여요.
    요구사항을 상세하게 정리해보고 (엣지 케이스 등등) 테스트와 구현으로 옮겨 보시면 좋을 것 같아요.
    
- **코드 컨벤션**
    
    대체로 코드 컨벤션이 없는 느낌이 들었어요.
    어떤 선언문은 다른 선언문과 붙어있고, 어떤 선언문은 다른 선언문과 떨어져 있어요. 선언문과 명령문이 붙어있는 경우와 떨어져 있는 경우도 혼재하고 있어요.
    
    `return` 문 전에 한 줄 공백을 두는 곳과 그렇지 않은 곳도 혼재하고 있어요.
    
    eslint 와 prettier를 적극적으로 활용해보면 좋을 것 같아요!

2024-05-01 08:18 UTC, notPotter commented on src/index.js
> +  for (let i = 0; i < carNames.length; i++) {
마찬가지로 고차함수를 사용하면 좋을 것 같네요!

2024-05-01 08:18 UTC, notPotter commented on src/Game.js
> +    if (this.playTime > 4) {
`4`와 같은 언제든 수정될 수 있고, 수정된다면 
여기 뿐아니라 테스트 코드도 수정해야되는 번거로움이 있을 거 같아요!
상수화 해두면 좋겠네요!

2024-05-01 08:18 UTC, notPotter commented on src/index.js
> +let endFlag = true;
while문으로 게임실행을 관리하신 이유가 있나요?

2024-05-01 08:18 UTC, notPotter commented on __tests__/Game.test.js
> +    testCar4.winCount = 3;
winCount를 Car 외부에서 조작할 수 있어도 괜찮나요?

2024-05-01 08:55 UTC, Quska45 commented on src/Car.js
> +    this.winCount = 0;
자동차 별로 자신이 몇번을 이겼는지에 대해서 가지고 있어야 한다고 생각이 들었습니다.
승리 횟수를 자동차가 가지지 않고 관리할 수 있는 방법이 있을까요?

2024-05-01 11:29 UTC, Quska45 commented on src/Game.js
> +  }
네 수정했습니다.

2024-05-01 11:38 UTC, Quska45 commented on src/Game.js
> +  getCarsByCarsString(carNamesString) {
체크로직 및 테스트 추가 했습니다.

2024-05-01 11:41 UTC, Quska45 commented on __tests__/Game.test.js
> +  });
하나 삭제 했습니다.

2024-05-01 11:41 UTC, Quska45 commented on __tests__/Game.test.js
> +});
체크 로직 및 테스트 추가했습니다.

2024-05-01 11:59 UTC, Quska45 commented on __tests__/Game.test.js
> +  });
말씀 하신 테스트 케이스도 추가했습니다.

2024-05-01 12:20 UTC, Quska45 commented on src/index.js
> +  for (let i = 0; i < carNames.length; i++) {
네 수정 했습니다.

2024-05-01 12:22 UTC, Quska45 commented on src/Game.js
> +    if (this.playTime > 4) {
네 상수 추가했습니다.

2024-05-01 12:31 UTC, Quska45 commented on src/index.js
> +let endFlag = true;
특별한 이유는 없습니다.
무한루프에 대한 가능성 때문에 언급해 주신것 같다는 생각이 들어서 for문으로 수정 했습니다.

2024-05-01 13:31 UTC, Quska45 commented on __tests__/Game.test.js
> +    testCar4.winCount = 3;
win 메서드를 만들어 놓고 사용하지 않고 있었습니다.
win메서드로 변경 했습니다.

2024-05-02 13:57 UTC, notPotter requested changes
광진님! 수정해주신 부분들에 대하여 코멘트 남겼습니다! 
확인 부탁드릴게요!

step2 에서는 말씀 드린 기능 요구사항 작성, 커밋 메시지, 코드 컨벤션에 대해서도 더 고민해보시면 좋을 것 같습니다!

2024-05-02 13:57 UTC, notPotter commented on src/Car.js
> +    this.winCount = 0;
승리횟수 자체는 `Game`과 관련된 부분이 아닐까요?
`Car`에 `Game`에 관심사가 묻어있다고 보입니다

2024-05-02 13:57 UTC, notPotter commented on src/Game.js
> +  }
외에도 아직 `for`, `foreach`를 사용하는 곳들이 많은 것 같아요!
다양한 고차함수들이 있으니 `for`, `foreach` 사용하기 전에 한 번 목적에 더 부합하는 함수는 없을지 확인해보시면 좋을 듯합니다

2024-05-02 13:57 UTC, notPotter commented on src/index.js
> +let endFlag = true;
무한루프보다는 "게임 실행을 몇 번 하는가?"는 앱 자체보다는
`Game`의 관심사라고 생각했습니다. `Game`에서 게임 실행 횟수를 인자로 받는다고 하면
다른 곳에서 `Game`의 관심사를 들고 있을 필요가 없을 것 같네요

2024-05-03 03:45 UTC, Quska45 commented on src/Car.js
> +    this.winCount = 0;
먼저 자동차가 자신이 몇 번 이겼는지에 대한 값을 가지고 있다는게 어색하다는 느낌이 들지는 않았습니다.
Game은 우승자가 누구인지만 구하고 자동차별로 승리 횟수는 Game이 관리할 필요가 없지 않나 싶었습니다. 
그리고 자동차가 자신의 승리 횟수를 가지고 있지 않다면 Game쪽 에서 코딩이 더 들어가야 하기 때문에 비효율적이지 않나 싶기도 했었구요.
car가 승리횟수를 가지지 않았을 때 더 좋은 점에서 대해서 알려주실 수 있을까요?

2024-05-03 03:45 UTC, Quska45 commented on src/Game.js
> +  }
안써버릇 하다보니 쓰기가 생각보다 어렵게 느껴지네요 ㅠㅠ 최대한 적용해보겠습니다.

2024-05-03 03:56 UTC, Quska45 commented on src/index.js
> +let endFlag = true;
네 수정했습니다.

2024-05-03 03:57 UTC, Quska45 commented on src/Game.js
>        }
잘못 들어간 코드여서 삭제 했습니다.

2024-05-03 03:57 UTC, Quska45 commented on src/Game.js
> +      console.log("cars", this.cars);
삭제 했습니다.

2024-05-03 04:02 UTC, Quska45 commented on src/index.js
> +    return;
실수로 뺴먹었습니다 ㅠ
프로미스로 리턴될 boolean값을 활용해 게임이 비정상적으로 종료됐을 때 뭔가 로직을 추가할 수 있는 방법도 추가해봤습니다.

2024-05-03 04:03 UTC, Quska45 commented
> 광진님! 수정해주신 부분들에 대하여 코멘트 남겼습니다! 확인 부탁드릴게요!
> 
> step2 에서는 말씀 드린 기능 요구사항 작성, 커밋 메시지, 코드 컨벤션에 대해서도 더 고민해보시면 좋을 것 같습니다!

했던 걸 다시 하려고 하니 몸이 쉽게 움직이질 않네요 ㅠㅠ. 다음 미션 부터는 더 많이 신경 써보도록 하겠습니다!

2024-05-03 07:15 UTC, wad-umjihyeok approved these changes
광진님! 알겠습니다, 일단 머지하도록 할테니
step2에서 같이 개선해보도록 해요!

2024-05-03 07:16 UTC, notPotter approved these changes
광진님! 알겠습니다, 일단 머지하도록 하겠습니다!
다음 스텝에서 같이 개선해보도록 해요!

2024-05-03 07:16 UTC, merged

2024-05-05 04:25 UTC, notPotter commented on src/Car.js
> +    this.winCount = 0;
지금보니 제가 놓친 부분이 있었네요.
누가 가지냐 이전에 가장 먼저 우승자를 구할 수 있는 `distance`값이 있는데 `winCount`가 왜 필요할까? 라고 생각했는데요.
먼저 요구사항과 다르게 구현이 되어 있습니다.

>전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다. 

광진님은 매 게임에서 랜덤값을 `distanceString`에 더해서 그려준 후, `distance`를 초기화 주고 계셨네요.
이 부분이 요구사항에 맞게 고쳐지는 게 우선일 것 같고, 그렇게 되면 없어질 로직과 값들일 것 같네요/1

2024-05-05 07:50 UTC, Quska45 commented on src/Car.js
> +    this.winCount = 0;
네 저도 완전 잘못보고 있었네요 ㅠ 수정해서 두번째 미션에 포함 시켜서 커밋하도록 하겠습니다!