[클린코드 6기 백건우] 자동차 경주 미션 STEP 2
next-step/js-racingcar pull request #240
Opened 2024-05-01 03:02 UTC by gwbaik9717

안녕하세요, 윤호님! 

지난 번 미션 때 꼼꼼한 피드백 주셔서 감사합니다! 😀
지난 STEP 1 미션에서 마지막 리뷰에 남겨주신 코멘트에 대한 수정과 이번 미션의 새로운 기능 구현을 추가하여 PR 을 올려봅니다. 
이번 미션에서 고민을 했던 부분은 다음과 같습니다.

- **입력 관련 로직은 어디에 두어야 할까?**
 이번 미션은 유저의 입력과 관련된 로직이 꽤나 복잡해졌다고 느껴졌습니다. 지난 미션은 유저로부터 `Car` 의 이름만 받아오면 되었지만, 이번에는 `Car` 의 이름 뿐만 아니라  `CarRace` 의 전체 횟수도 받아와야 하고, 입력 값이 특정 조건에 부합하지 않으면 재입력을 유도해야하기 때문입니다. 입력 관련 로직이 복잡해지다보니 저는 크게 `getTotalRaceCountFromUserInput` 과 `getCarNamesFromUserInput` 함수를 만들어 유저로부터 각각 전체 자동차 경주 횟수와 자동차들의 이름을 입력 받는 함수를 만들었습니다. 
 미션 초반에는 `getTotalRaceCountFromUserInput` 는`CarRace` 와 직결된 로직이라 판단하여 `CarRace` 내 static 메서드로 정의를 하였고, `getCarNamesFromUserInput` 은 단일 `Car` 가 아닌 복수 개의 `Car` 와 관련된 로직이라 생각하여 `utils/cars` 파일 내 정의하였습니다. 다만, 하는 역할은 거의 동일한데 반해 위치가 동떨어져 있는게 맞나 싶었습니다. 따라서, `utils/view` 파일을 통해 입력과 출력 관련된 함수를다루도록 작성해보았습니다. 

- **validation 을 2번 하는게 맞을까?**
지난번 미션에도 고민을 했던 부분이긴 한데요, 현재 `Car` 의 이름이나 `CarRace` 의 전체 횟수를 validate 하는 로직은 최악의 상황을 방지하기 위해 아래와 같이 각 클래스의 생성자 내에 위치하고 있습니다. 
`CarRace`
```javascript
class CarRace {
  constructor(competitors, totalRaceCount = 0) {
    CarRace.validateTotalRaceCount(totalRaceCount);

    // 생략
  }

  static validateTotalRaceCount(totalRaceCount) {
    if (!isNumber(totalRaceCount)) {
      throw new Error(ERROR_CAR_RACE_COUNT_NOT_VALID);
    }

    if (totalRaceCount < 0) {
      throw new Error(ERROR_CAR_RACE_COUNT_NOT_VALID);
    }
  }
}
``` 
다만, 현재 유저로부터 전체 자동차 경주 횟수를 입력 받는 과정에도 아래와 같이`validateTotalRaceCount`  로직이 쓰고 있습니다. 물론 해당 함수를 직접 부르지 않고 `new CarRace()` 를 통해 validation을 간접적으로 할 수 있다고 생각했습니다. (어차피 생성자 안에도 validation 로직이 있으므로)  하지만, 단순히 validation을 목적으로 불필요한 객체를 만드는 것이 직관적이지 않다고 판단하여 직접 `validateTotalRaceCount` 를 호출하도록 하기로 하였습니다. 하지만, 결국 validation 로직이 2번 있는건데 해당 부분에 대해 약간의 찝찝함이 들었습니다!

```javascript
export async function getTotalRaceCountFromUserInput() {
  while (true) {
    const input = await readLineAsync("시도할 회수는 몇회인가요?");
    const totalCount = Number(input);

    try {
      CarRace.validateTotalRaceCount(totalCount);
      return totalCount;
    } catch (e) {
      console.log(ERROR_CAR_RACE_COUNT_NOT_VALID);
      console.log();
    }
  }
}
```

2024-05-02 09:09 UTC, yujo11 requested changes
안녕하세요 건우님~

step2 미션 진행하느라 고생 많으셨습니다 ㅎㅎ 코멘트 남기다보니 지난 step1 때 놓쳤던 부분이 보여서 해당 부분들에도 코멘트 남겼는데 같이 확인해주시면 좋을거 같습니다!

>입력 관련 로직은 어디에 두어야 할까?

위치 관련해서는 코멘트로도 남겼지만 `utils/cars`에 해당 로직이 존재하는 게 조금 어색하게 느껴지는데요. view라는 디렉터리를 별도로 만들어 해당 디렉터리 안에서 관리하면 더 직관적일거 같습니다!

>validation 을 2번 하는게 맞을까?

validation을 2번 하게 되면 코드가 중복되는 느낌이 들 수 있지만 최악의 상황을 방지한다는 건우님의 목적에 잘 부합하는 방법인데요.

한 지점에서의 검증이 실패하더라도 다음 지점에서 다시 검증을 진행하며 객체의 무결성을 보장할 수 있는 좋은 방법이라고 생각합니다 ㅎㅎ

---

고생 많으셨습니다 건우님~ 

추가로 궁금하신 부분 있으시면 코멘트 남겨주세요!

2024-05-02 21:25 UTC, gwbaik9717 commented on src/utils/cars.js
말씀해주신대로 `view` 와 관련된 로직을 `domain/View` 로 옮겨보았습니다. 이때 View 내 모든 메서드들은 `static` 이기에 클래스보다는 객체 리터럴을 통해 객체를 생성하였습니다.

2024-05-02 21:50 UTC, gwbaik9717 commented on src/utils/cars.js
> +  carNames.forEach((carName) => {
제안 주셔서 감사합니다! 한가지 궁금한 부분이 있는데요. `validateNames` 는  자동차 이름들을 `validate` 하는 로직이다보니, `every` 를 적용함으로써 함수의 리턴값이 boolean 이 되는 것이 약간 어색하다고 느꼈습니다. 만약 every 와 함께 사용하려면 `isValidNames` 과 같은 이름 및 관련 기능을 가진 함수에 더 적절하지 않을까 생각했습니다. 또한, `every` 의 콜백으로 사용될 `validateName` 또한 리턴값이 boolean 이 아니라 약간 애매하고 느꼈습니다. 해당 부분에 대한 의견이 궁금합니다!

2024-05-02 22:07 UTC, gwbaik9717 commented on src/domain/Car.js
>    positionToString() {
두 함수 모두 view 와 관련된 로직이라 판단되어 각각 `domain/View` 파일로 이전하였습니다.

2024-05-02 22:10 UTC, gwbaik9717 commented on src/utils/number.js
> +}
해당 부분 수정했습니다!

2024-05-02 22:14 UTC, gwbaik9717 commented on __tests__/IO.test.js
> +  test("자동차 경주 횟수를 입력할 때 0 미만의 정수 또는 정수가 아닌 값을 입력한 경우 에러 메시지를 출력하고 0 이상의 정수가 입력될 때까지 무한 반복한다.", async () => {
해당 부분에 대한 테스트 케이스 추가하였습니다!

```javascript
test("자동차 경주 횟수를 입력할 때 0 미만의 정수 또는 정수가 아닌 값을 입력한 경우 에러 메시지를 출력하고 0 이상의 정수가 입력될 때까지 무한 반복한다.", async () => {
    // given
    readLineAsyncSpy
      .mockImplementationOnce(() => Promise.resolve("-1"))
      .mockImplementationOnce(() => Promise.resolve("1.3"))
      .mockImplementationOnce(() => Promise.resolve("abc"))
      .mockImplementationOnce(() => Promise.resolve("5"));

    // when
    const totalCount = await View.getTotalRaceCountFromUserInput();

    // then
    expect(logSpy).toHaveBeenCalledWith(ERROR_CAR_RACE_COUNT_NOT_VALID);
    expect(readLineAsyncSpy).toHaveBeenCalledTimes(4);
    expect(totalCount).toBe(5);
  });
```

2024-05-02 22:17 UTC, gwbaik9717 commented on src/utils/view.js
말씀해주신대로 view 와 관련된 로직을 domain/View 로 옮겨보았습니다. 이때 View 내 모든 메서드들은 static 이기에 클래스보다는 객체 리터럴을 통해 객체를 생성하였습니다.

2024-05-02 22:52 UTC, gwbaik9717 commented on src/utils/view.js
> +  const joinedCarRaceWinners = joinCarNamesByComma(winners);
제가 말씀을 정확하게 이해했는지 확실하지는 않지만, 말씀주신대로 `,` 이외에 다양한 출력 조건이 있을 수 있을 것 같아 `joinCarNamesByComma` 라는 별도의 함수를 만들기보다 다음과 같이 조건을 그때 그때 마다 줄 수 있게 변경해 보았습니다.

```javascript
 printCarRaceWinners(cars) {
    const carNames = cars.map((car) => car.name);
    const joinedCarNames = carNames.join(", ");

    console.log(`${joinedCarNames}가 최종 우승했습니다.`);
 }
```

2024-05-03 03:42 UTC, gwbaik9717 commented on src/domain/CarRace.js
> +        }
자동차를 움직이는 조건을 어디에 둘지 고민 끝에 `CarRace` 내 static 메서드로 관리해보았습니다!

```javascript
static generateCarMoveCondition() {
    const randomValue = Math.floor(Math.random() * 10);
    return randomValue >= 4;
  }

  race() {
    while (this.#remainingRaceCount > 0) {
      this.competitors.forEach((competitor) => {
        const canCarMove = CarRace.generateCarMoveCondition();
        if (canCarMove) {
          competitor.move();
        }
      });
       // 생략
    }
  }
```

2024-05-03 10:24 UTC, yujo11 commented on src/utils/cars.js
> +  carNames.forEach((carName) => {
아하 그런 상황이라면 어떤 방식을 사용하나 큰 차이가 없을거 같네요 ㅎㅎ

2024-05-03 10:26 UTC, yujo11 commented on src/domain/CarRace.js
> +        }
static 메서드로 만드신 이유가 있을까요?

2024-05-03 10:26 UTC, yujo11 commented on src/domain/CarRace.js
> +        }
애플리케이션 전체에 걸쳐 static 메서드를 많이 사용하고 계신거 같은데 어떤걸 기준으로 static 메서드를 만들고 계시는건지 궁금하네용

2024-05-03 10:27 UTC, yujo11 commented on src/utils/view.js
> +  const joinedCarRaceWinners = joinCarNamesByComma(winners);
View에서 단순 입/출력만 담당하는게 아니라 "어떻게" 값을 보여줄지까지 결정하고 있어서 해당 부분은 Domain 로직에서 결정하고 View는 단순 입/출력만 담당하면 어떨까 하는 생각이 들어 남긴 리뷰였습니다 !

2024-05-03 10:30 UTC, yujo11 requested changes
안녕하세요 건우님~

코멘트 꼼꼼하게 확인해주셔서 감사합니다! 

추가적인 코멘트와 질문 몇 개 남겼는데 확인해주시면 좋을거 같습니다! 고생 많으셨습니다~~ 👍 👍 👍

2024-05-03 10:30 UTC, yujo11 commented on __tests__/IO.test.js
> +      .mockImplementationOnce(() => Promise.resolve("abc"))
👍 👍 👍

2024-05-03 10:30 UTC, yujo11 commented on src/domain/CarRace.js
> +    return randomValue >= 4;
4라는 값도 상수화가 되면 좋을거 같네요

2024-05-03 12:02 UTC, gwbaik9717 commented on src/domain/CarRace.js
> +        }
저는 메서드를 작성할 때 만약 메서드가 클래스 내 어떠한 필드도 참조하지 않는다면, 해당 메서드는 인스턴스가 아닌 클래스와 관련된 로직이라 간주하고, static 으로 만들고 있습니다. 물론 static 메서드를 사용하지 않아도 되지만, 추후 해당 메서드가 클래스 외부에서 사용되는 상황을 고려할 때  인스턴스를 만들지 않고 클래스만으로 접근할 수 있다는 것은 큰 이점이라 생각되어, 최대한 활용하려고 하였습니다! (그런데 한번 찾아보니 메모리 관리 측면 등에 의해서 남용하지 말라고 나와있군요..!)

2024-05-03 12:24 UTC, gwbaik9717 commented on src/domain/CarRace.js
> +    return randomValue >= 4;
아래와 같이 상수로 만들었습니다!

`constants/carRace.js`
```javascript
export const CAR_MOVE_CONDITION_BOUNDARY = 4;
```

2024-05-03 12:36 UTC, gwbaik9717 commented on src/domain/CarRace.js
> +        }
`static` 을 전수조사 해본 결과, `generateCarMoveCondition` 은 해당 클래스 내 메서드 이외에 사용되는 곳이 없더군요! 나중에도 해당 메서드만 따로 외부에서 호출할 가능성은 없어보여서`static` 을 제거하였습니디다. 이외에 `static` 이 쓰이고 있는 다른 메서드들 가령 `createCarsFromCarNames`, `validateCarNames` 은 클래스 외부에서 적절히 사용되는 것으로 판단되어 그대로 두었습니다.

2024-05-03 12:46 UTC, gwbaik9717 commented on src/utils/view.js
> +  const joinedCarRaceWinners = joinCarNamesByComma(winners);
아하! 이해했습니다. 말씀해주신대로 다음과 같이 수정해보았습니다.

`src/index.js`
```javascript
// 우승자 출력
 View.printCarRaceWinners(carRace.winnerNames.join(", "));
```

`domain/View.js`
```javascript
printCarRaceWinners(winnerNames) {
    console.log(`${winnerNames}가 최종 우승했습니다.`);
}
```

2024-05-03 13:18 UTC, gwbaik9717 commented on src/utils/view.js
> +  const joinedCarRaceWinners = joinCarNamesByComma(winners);
관련해서 한가지 궁금증이 생겼습니다. 다음은 View 내에 있는 자동차의 현재이름과 위치를 출력하는 함수입니다. 마찬가지로, 아래 메서드도 출력에만 집중할 수 있도록 하고 싶어 `carPosition` 을 계산하는 로직을 없애고 싶더라구요 !

`domain/View`
```javascript
printCarStatus(car) {
    const carPosition = "-".repeat(car.position);

    console.log(`${car.name} : ${carPosition}`);
}
```

따라서, 아래과 같이 한번 수정해보기로 하였습니다만, 한가지 궁금증이 생겼습니다.

`domain/View`
```javascript
printCarStatus(carName, carPosition) {
    console.log(`${carName} : ${carPosition}`);
}
```
 아래 함수는 `printCarStatus` 를 여러번 호출하는 함수입니다. 결국 해당 함수도 print 에 집중해야하는데, 다시 
`carName`과 `carPosition` 을 계산하는 로직을 가지고 있어서 다시 원점으로 돌아간거 아닌가 싶더라구요! 물론 어쩔수 없다고 생각하기도 하지만서도 궁금합니다!
 
`domain/View`
```javascript
printCarsStatus(cars) {
    cars.forEach((car) => {
      const carName = car.name
      const carPosition = "-".repeat(car.position);
      this.printCarStatus(carName, carPosition);
    });
    console.log();
 }
```

2024-05-04 15:04 UTC, yujo11 commented on src/utils/view.js
> +  const joinedCarRaceWinners = joinCarNamesByComma(winners);
View가 단순히 전달받은 값을 보여주는(출력하는) 역할만 수행하게 한다면 `cars`에 대한 정보를 알고 있는 곳에서 this.printCarStatus를 호출하게 만들수도 있을거 같아요

2024-05-04 15:05 UTC, yujo11 approved these changes
안녕하세요 건우님~

사실 지난 번 리뷰 때도 바로 merge해도 괜찮다는 생각이 들었지만 코드 내용 중 궁금한 내용들이 있어 request-chages를 드렸는데요. 이번 step 진행하느라 고생 많으셨습니다! 👍 👍 👍 

step3에서 다시 뵙겠습니다!

2024-05-04 15:06 UTC, merged