[클린코드 6기 허다미] 자동차 경주 미션 STEP 2
next-step/js-racingcar pull request #250
Opened 2024-05-05 11:56 UTC by supreme-d

안녕하세요, 리뷰어님.

이렇게 리뷰를 통해서 처음 인사 드리게 되었습니다. 😄 

STEP 2를 진행하면서 관심사 분리의 중요성을 깨달을 수 있었던 시간이었어요...!

미션을 진행하면서 몇 가지 질문 사항이 생겨서 정리해보았습니다.

### 질문

**1. 어떤 걸 클래스, 모듈로 만드는 게 좋을지**
    아직 어떤 걸 클래스나 모듈로 만들어야 할지 감이 잘 오지 않는 것 같아요.
    혹시 이와 관련하여 조언해주실 만한 것이나, 참고할 만한 자료를 알려주실 수 있을까요?

**2. 적절한 에러 처리 위치**
    조건을 만족하는 값을 받을 때까지 사용자로부터 입력을 받는 로직을 아래와 같이 만들어보았는데요.
    try/catch 구문을 지금과 같이 넣으면 될지, 아니면 `parseFunction` 내부에 넣는 게 적절한지 아직 감이 잡히질 않습니다.
    이와 관련하여 조언을 구할 수 있을까요?

    ```javascript
    export const getValidInput = async (promptMessage, parseFunction) => {
      let result;
    
      while (true) {
        try {
          const userInput = await IO.readLineAsync(promptMessage);
          result = parseFunction(userInput);
          break;
        } catch (error) {
          printError(error);
        }
      }
    
      return result;
    };
    ```

**3. 위의 함수에 대한 테스트 코드 작성**
위와 같은 함수에 대해서도 테스트 코드를 작성할 수 있을지 궁금합니다!

---

리뷰해주셔서 감사합니다. 피드백 주신 사항은 잘 반영해서 더 좋은 코드로 개선해보도록 하겠습니다! 😄

2024-05-08 01:13 UTC, greenblues1190 requested changes
안녕하세요 다미님! 이번 미션은 요구사항도 적고, 스텝1에서 깔끔하게 잘 구현해주셔서 피드백할 부분이 많지 않았어요. 프롬프트 로직과 관련해 피드백 하나 남겼습니다~

질문주신 부분에 대해 답변을 드리자면,

1. 어떤 걸 클래스, 모듈로 만드는 게 좋을지
> 아직 어떤 걸 클래스나 모듈로 만들어야 할지 감이 잘 오지 않는 것 같아요. 혹시 이와 관련하여 조언해주실 만한 것이나, 참고할 만한 자료를 알려주실 수 있을까요?

[필요성이 느껴지지 않는데](https://ko.wikipedia.org/wiki/YAGNI) 굳이 모듈화 해야 할지는 의문이 드네요. 코드 볼륨이 커지고 동일 로직이 반복해서 나타난다면 자연스럽게 분리가 필요한 계층이나 도메인이 보이고, 그때 모듈화하면 되지 않을까요?

현재 구조에서 스케일이 커진다면 다음과 같은 로직을 모듈화할 수 있을 것 같네요.

- 유효성 검증 (zod, yup...)
- 커맨드라인 IO (inquirer.js, enquirer...)

참고 자료라면.. [SOLID](https://ko.wikipedia.org/wiki/SOLID_(%EA%B0%9D%EC%B2%B4_%EC%A7%80%ED%96%A5_%EC%84%A4%EA%B3%84))만 떠오르네요!

2. 적절한 에러 처리 위치
> 조건을 만족하는 값을 받을 때까지 사용자로부터 입력을 받는 로직을 아래와 같이 만들어보았는데요. try/catch 구문을 지금과 같이 넣으면 될지, 아니면 parseFunction 내부에 넣는 게 적절한지 아직 감이 잡히질 않습니다. 이와 관련하여 조언을 구할 수 있을까요?
> ```js
> export const getValidInput = async (promptMessage, parseFunction) => {
>   let result;
> 
>   while (true) {
>     try {
>       const userInput = await IO.readLineAsync(promptMessage);
>       result = parseFunction(userInput);
>       break;
>     } catch (error) {
>       printError(error);
>     }
>   }
> 
>   return result;
> };
> ```

parseFunction이 이름 그대로 제출된 입력값을 파싱하는 역할을 한다면 내부에 에러처리로직이 있으면 안될 것 같습니다. 관련해서 아래 코멘트 확인해주세요!

3. 위의 함수에 대한 테스트 코드의 필요성
> 위와 같은 함수는 내부적으로 여러 가지 함수를 이용하고 있는데요. 이러한 함수는 의존성이 많다보니, 단위 테스트보다는 통합 테스트?가 적절할 것이라고 판단하였는데, 리뷰어 님의 생각은 어떠신지 궁금합니다...!

process.stdin, process.stdout 의존성에 대해 단위테스트 진행하면 좋을 것 같네요!

2024-05-11 03:29 UTC, supreme-d commented
멘토님 안녕하세요!
이번에도 친절하고 도움이 많이 되는 피드백 주셔서 감사해요.

알려주신 사항 참고해서 수정해보았는데, 가능하실 때 피드백 부탁 드릴게요! 

정말 감사합니다. 😃

2024-05-11 03:31 UTC, supreme-d commented on src/utils.js
> +};
enquirer가 여러 곳에서 많이 쓰이고 있네요..!
미션 뿐만 아니라, 일을 할 때도 도움이 될 만한 자료인 것 같아요.
좋은 자료 공유해주셔서 감사합니다! 😄

2024-05-12 01:50 UTC, wad-woojeongmin approved these changes
다미님 자동차 경주 미션 수행하시느라 수고하셨습니다. 머지하도록 하겠습니다!

2024-05-12 01:50 UTC, wad-woojeongmin commented on __tests__/utils.test.js
> +    const laps = await prompt("경주할 자동차 이름을 입력해주세요.(쉼표(,)를 기준으로 구분)", {
질문 문자열이 잘못 들어간 것 같아요

2024-05-12 01:50 UTC, greenblues1190 approved these changes
다미님 자동차 경주 미션 수행하시느라 수고하셨습니다. 머지하도록 하겠습니다!

2024-05-12 01:51 UTC, merged