[클린코드 1기 정재남] 자동차경주 미션 Step 1 ~ 3
next-step/js-racingcar pull request #38
Opened 2021-11-24 08:20 UTC by roy-jung

저로서는 각 스텝별 요구사항이 단계별로 구분지어가며 작업하기 너무 어렵네요^^; 
3단계까지 몰아서 한 번에 다 해버렸습니다.
이해하기 어렵거나 궁금한 점에 대한 질문, 이상하거나 아쉬운 점에 대한 지적, 뭐가 되었든 마구마구 주세요!
감사합니다.

(일정이 많이 남았으니 리뷰는 천천히 주셔도 됩니다. 압박/부담 느끼지 않으시기를..)

## 데모

[바로가기](https://roy-jung.github.io/js-racingcar/)

## 웹 vscode 환경

[바로가기](https://github.dev/roy-jung/js-racingcar/tree/roy-jung)

## 주안점

- MVC 패턴 대신 flux 비슷한 아키텍쳐를 고안해 보았습니다. 컨셉은 redux에서 많이 차용했지만, 능력의 한계로 클로저를 잔뜩 활용한 connect 같은 함수를 만들지는 못하겠어서, 각각의 view마다 'watch'라는 메서드를 통해 필요한 데이터만 추출하게끔 하였습니다. 이를 위해 store - view 사이에 viewStore라는 중간다리를 두었습니다.
- 데이터 흐름은 [ event -> dispatch(action) -> worker(reducer 및 redux-thunk 혼합? 개념) -> store -> viewModel -> 등록된 데이터들 중 변경사항이 있는 경우에만 해당 view에 전파 ] 이런 흐름입니다.
- requestAnimationFrame을 적극 활용하였습니다. cancel을 위해 abortController라는 걸 처음 써봤는데 좋네요!

## 요구사항

### 1단계
- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [x] 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [x] 자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- [x] 사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [x] 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.

### 2단계
- [x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.
- [x] 우승자가 여러명일 경우 ,를 이용하여 구분한다.

### 3단계
- [x] 자동차 경주 게임의 턴이 진행 될 때마다 1초의 텀(progressive 재생)을 두고 진행한다.
- [x] 애니메이션 구현을 위해 setInterval, setTimeout, requestAnimationFrame 을 활용한다.
- [x] 정상적으로 게임의 턴이 다 동작된 후에는 결과를 보여주고, 2초 후에 축하의 alert 메세지를 띄운다.

2021-12-01 15:00 UTC, limhizy15 requested changes
안녕하세요 재남님! 리뷰를 맡은 임희지라고 합니다.
코드가 어려워보여 지금까지 미루다가 결국 지연되버린 점 죄송합니다 😌
일단 코드 전체 구조를 아직 다 파악하지 못해서 이해한 부분만 질문과 제안을 남겨두었습니다. 거의 물음표살인마 수준으로 질문이 많은데요,, 요녀석이 아직 잘 모르는 구나하고.. 잘 봐주시면 감사하겠습니다. 코드 리뷰하면서 새로운 web API들도 많이 알게 되어서 좋았습니다!

몇 가지 질문이 있는데요
1. ts로 작성했는데도 import할 때는 js파일을 불러오는 이유가 뭔지 알 수 있을까요?
2. 전반적으로 class 안에 #을 붙여 private하게 만드는 걸 봤는데 그냥 사용되는 프로퍼티들을 숨기려고 그런 건지 아니면 각 각 이유들이 있어서 그런건지 궁금합니다.
3. 아래 그림과 같이 a, b b나 E AST, W EST를 입력하면 띄어쓰기 이전 문자만 차 이름으로 반영이 됩니다. 사실 너무 사소한 거라 신경쓰지 않아도 될 부분인 것 같긴한데 재남님 코드에서는 차 이름을 trim을 활용해서 양쪽 공백을 없애시던데 왜 이름들이 이렇게 반영되는지 잘 이해가 되지 않습니다.
![image](https://user-images.githubusercontent.com/41099712/144256280-34eee766-704b-48d9-b860-2660d451f0f7.png)
![image](https://user-images.githubusercontent.com/41099712/144256550-4d0c0609-9992-4ed2-9a73-fd577d18a8f7.png)

2021-12-02 00:21 UTC, roy-jung commented on cypress/integration/racingcar.spec.js
> +import { CongratulationMsg, ErrorMsgs } from '../../dist/constants.js'
브라우저는 ts를 직접 로딩할 수 없고 오직 js로 변환된 파일만을 인식합니다. 일반적으로 ts를 그대로 import할 수 있는 케이스는 웹팩 등의 번들러가 그렇게 인식할 수 있도록 도움을 주기 때문이고, 그러한 번들러를 쓰지 않는 경우에는 ts를 그대로 import 할 수 없어요.

2021-12-02 00:26 UTC, roy-jung commented on cypress/integration/racingcar.spec.js
> +}
Command는 어떤 복잡한 명령을 함수화해서 좀 더 편하게 자동화해주기 위한 도구 정도로 인식하였습니다. 이 명령에 '테스트'까지 포함되는 것은 바람직하지 않다 생각해요. 테스트를 위한 파일(spec.js)의 역할과 도구인 Command의 역할이 서로 겹치면 혼란스러울 것 같아요. initialTest 함수는 말그대로 '테스트'까지 수행하는 함수이므로 spec.js 내부에 존재하는 것이 맞다고 생각했습니다.

2021-12-02 00:27 UTC, roy-jung commented on cypress/integration/racingcar.spec.js
> +        console.log(text)
맞아요! 지우겠습니다 ㅎㅎ

2021-12-02 00:28 UTC, roy-jung commented on cypress/integration/racingcar.spec.js
> +        .next()
cypress가 jquery의 메서드를 많이 차용하고 있더라구요 :)

2021-12-02 00:36 UTC, roy-jung commented on cypress/support/commands.js
> +})
이건 네이밍 컨벤션이라고 봐야할 것 같은데요, 실무에서도 계속 고민중인 부분이긴 합니다.
[Button / Form / Input / Card / Box / List] 등의 일반적인 속성을 지니는 컴포넌트명을 지을 때, 
[해당 컴포넌트를 특정하기 위한 고유명사 + 일반속성] 의 방식이 맞을지, 
반대로 [일반속성 + 고유명사]의 방식이 맞을지에 대한 고민이에요.
예를 들어, 'PersonNameInput' vs. 'InputPersonName' 이 둘의 차이에 대한 고민입니다.
파일트리 상에서 a-z오름차순 정렬이 된 상태일 때
전자는 Person과 관련한 파일이 한 데 모여있어 편한 반면 속성(Input)으로 찾기는 어렵고, 
후자는 반대로 Input / Form 등 공통속성을 지닌 요소들이 한 데 모여있는 반면 Person과 관련한 파일이 여기저기 흩어질테고요.
이 두 장단점 사이에서의 양자택일의 문제인 것 같습니다.

2021-12-02 00:37 UTC, roy-jung commented on src/ts/store/worker.ts
> +    }, [])
개인적으로 previousValue를 줄여서 p라고 종종 씁니다.
accumulator를 줄여서 a라고 쓰시는 분도 많이 봤어요.

2021-12-02 00:38 UTC, roy-jung commented on src/ts/store/worker.ts
> +export default (actionType: keyof typeof Actions) => workerWithErrorCatcher(worker[actionType])
정확합니다!

2021-12-02 00:41 UTC, roy-jung commented on src/ts/view/constructor.ts
> +  }
특별한 기준을 정해서 그렇게 한 건 아니지만,
- 유독 가독성이 떨어지는 경우
- 특별히 주의가 필요한 함수
- 눈에 좀 더 잘 띄기를 원하는 함수
등등의 경우에는 줄을 띄우고자 하는 습성이 있어요.

2021-12-02 00:57 UTC, roy-jung commented
`전반적으로 class 안에 #을 붙여 private하게 만드는 걸 봤는데 그냥 사용되는 프로퍼티들을 숨기려고 그런 건지 아니면 각 각 이유들이 있어서 그런건지 궁금합니다.`

-> 해당 프로퍼티에 대한 접근/변경 권한을 오직 해당 객체(클래스)만 갖도록 하기 위함입니다. 그렇지 않으면 외부에서 개입할 수 있게 되는데, 이 '개입가능성'을 차단하는건 멀게는 사용자들의 악용을 막는 효과도 있지만, 그보다 훨씬 가깝게, 개발자들에게 큰 도움이 되기 때문입니다. 
예를 들어 개발자X가 작성한 A 클래스가 있는 상태에서 개발자Y가 B 클래스를 개발하던 중, A클래스의 멤버 a가 private인줄 모른 채로 [B가 A의 a를 변경]하는 코드를 작성하였다면, 작성과 동시에 오류가 발생할 겁니다. 이 오류/경고 덕분에 Y는 A의 a를 건들지 않는 다른 방법을 찾게 될 것이고, 그덕분에 a는 안전하게 보호되겠죠.
그러니까 이후에 다른데서 개입하여 변경하면 안되는 멤버에 대해서 '미리미리 방지하자'는 차원으로 이해하시면 좋을 것 같네요.

`a, b b나 E AST, W EST를 입력하면 띄어쓰기 이전 문자만 차 이름으로 반영이 됩니다. 사실 너무 사소한 거라 신경쓰지 않아도 될 부분인 것 같긴한데 재남님 코드에서는 차 이름을 trim을 활용해서 양쪽 공백을 없애시던데 왜 이름들이 이렇게 반영되는지 잘 이해가 되지 않습니다.`

-> 이부분 제가 실수가 있었습니다. 띄어쓰기를 입력할 생각을 해보지 않아서 미처 발견하지 못한 오류였네요. 감사합니다!
html 파싱과정에서의 문제였습니다.

```html
<racingcar-player name=${name} index=${i}>
```
이렇게 넣었더니, 실제 html태그상에는 `<racingcar-player name="a" b index="0">` 이런 식으로 들어가더라구요..
```html
<racingcar-player name="${name}" index=${i}>
```
이렇게 따옴표로 묶어줘야 정상동작하게 되겠어요.

2021-12-02 01:06 UTC, roy-jung commented on cypress/support/commands.js
> +})
Cypress 공식문서에서 얘기하는 내용은 한마디로 요약하면 '정확히 특정가능하고 값 또는 attribute의 변경이 있더라도 선택된 대상이 바뀌지 않아야 한다' 인 것 같습니다. 맨 밑의 'isolated from all changes'가 가장 권장되는 내용이죠.
이에 따르면 만약 테스트하는 대상 html상에 div태그가 단 하나만 존재한다면, cy.get('div') 조차도 권장할 수 있는 선택지가 될 것입니다. 일반적으로는 div가 단 하나만 존재하는 케이스는 잘 없기 때문에 위와 같은 표를 소개한 것일 뿐, 저기서 'recommend'하는 내용을 반드시 따라야 하는 것은 아닌 것 같아요 :)

2021-12-02 01:13 UTC, roy-jung commented on src/ts/app.ts
> +  static #template = /* html */ `
1. static으로 선언한 멤버는 class의 인스턴스에는 상속되지 않습니다. 그러면서도 class의 고유한 속성을 정의할 수 있죠. 따라서 인스턴스로부터 고립시키면서도 해당 class의 인스턴스들에게 공통된 속성을 부여하기 위한 목적으로 사용했습니다. template은 고정된 값으로, 인스턴스들마다 달라질 여지가 없고, 그와 동시에 각 인스턴스들이 굳이 해당 내용을 알아야할 이유도 없다고 생각했습니다.
2. private에 대해서는 앞서 말씀드린 이유와 마찬가지여서 여기서는 답변을 생략하겠습니다 :)
3. 👍

2021-12-02 01:14 UTC, roy-jung commented on src/ts/app.ts
> +        <racingcar-form-attempts></racingcar-form-attempts>
위 코멘트와 겹치는 내용이라 넘어갈게요 ^^

2021-12-02 01:22 UTC, roy-jung commented on src/ts/app.ts
> +    el(this, [el(App.#template)])
element를 줄인겁니다! 보통 elem / el 요런식으로 많이 씁니다.
여기저기서 많이 쓰이는 함수라서 간결하게 줄여서 썼어요.
제이쿼리의 $ 같은 시그니쳐 정도로 생각해주시면 좋을 것 같네요 ㅎㅎ

el 함수의 내용은 다음과 같습니다.
인자로 parent, children(생략가능. 반드시 배열이어야 함)을 받고, HTMLElement를 반환합니다. 
- parent가 문자열일 경우: 해당 문자열을 HTMLElement로 만든다.
- parent가 HTMLElement일 경우: 해당 HTMLElement을 그대로 사용한다.
- children이 없을 경우: HTMLElement인게 확실한 parent를 반환.
- children이 있을 경우: 각 child들을 HTMLElement으로 만들어서 전체 children을 parent에 넣어주고, 전체를 반환.

2021-12-02 01:25 UTC, roy-jung commented on src/ts/constants.ts
> +  MaximumNameLength: 5,
상수의 경우 두가지 컨벤션을 혼용합니다.
1) `NAME_LENGTH_LIMIT`과 같이 모두 대문자로 쓰고 띄어쓰기를 _로 대체하는 경우도 있고
2) `ForwardCutOff`와 같이 파스칼표기법을 쓰는 경우도 있는데요

보통은 1)을 많이 쓰는 것 같지만 개인적으로 입력하기가 어렵고 가독성도 떨어져서 2)를 선호합니다.
그런데 이제 보니 저도 마구 혼용해서 쓰고 있었던 것 같네요 ^^;
이제라도 한가지 방식으로 통일시키는 편이 좋을 것 같습니다.

2021-12-02 01:28 UTC, roy-jung commented on src/ts/store/index.ts
> +    })
this는 app이 아닌 store 자신을 가리킵니다. arrow함수는 this를 바인딩하지 않아서 상위의 this를 그대로 쓰기 때문이죠.

2021-12-02 01:34 UTC, roy-jung commented on src/ts/store/index.ts
> +    this.#observers.add(viewStore)
store가 변경사항을 전달해줄 대상을 등록하는 함수입니다.

그러고보니 observer라는 명칭 자체가 잘못된 것 같아요.
publish / subscribe 패턴에 좀 더 가까운 것 같네요. 전체적으로 수정해서 푸시하겠습니다.

2021-12-02 01:45 UTC, roy-jung commented on src/ts/store/viewStore.ts
> +    const newState = this.#view.watch!(state)
이부분은 typescript에서만 존재하는 '단언(assertion)'명령입니다. this.#view.watch 라는 메서드가 있는게 확실하다! 의심하지 말아라! 에러 내지 말고 믿고 그냥 넘어가라! 뭐 이런 느낌이에요.

2021-12-02 01:48 UTC, roy-jung commented on src/ts/store/viewStore.ts
> +    }, {})
newState가 넘어왔을 때, newState의 각 프로퍼티들을 하나하나 prevState의 프로퍼티와 비교해서, 
값이 다른 경우에만 'updatedKeys'에 추가하고 'updatedState'에도 추가해주는 겁니다.
최종적으로 updatedKeys는 값이 다른 프로퍼티의 키값들로만 이루어진 set이 될 것이고,
updatedState에는 값이 다른 프로퍼티들로 구성된 객체가 되겠죠.

2021-12-02 01:53 UTC, roy-jung commented on src/ts/store/viewStore.ts
> +      this.#view.onStoreUpdated(updatedState, state)
view/constructor.ts 파일은 abstract 클래스(View)입니다.
즉 View가 직접 인스턴스로 활용되는 케이스는 없고, 
다른 view 컴포넌트들이 View를 상속(extends)받아서 쓰는 용도에요.

각각의 view 컴포넌트는 store를 'watch'하는지 여부에 따라 onStoreUpdated가 구현되어 있거나 그렇지 않는 경우도 있는데,
원래 onStoreUpdated는 store를 'watch'하는 경우에 한해서 호출되는 것이 정상적인 흐름이지만
혹시라도 그렇지 않은 경우를 대비해서 abstract 클래스에도 빈 메서드를 마련해 두었습니다.
일종의 안전장치 개념이에요.

2021-12-02 01:57 UTC, roy-jung commented on src/ts/store/worker.ts
> +    abortAlert()
64번줄(raceFinished 함수 내부)에서 `abortAlert = abortDelay` 를 할당해주고 있습니다.
즉 race가 끝났을 때에는 abortAlert이 의미가 생기고, 그렇지 않을 경우에는 빈 함수만 있는 상태입니다.
둘 중 어느 경우에도 `abortAlert()`을 호출했을 때 문제없이 동작하기 위한 조치에요.

미션 스펙상에 '경기 종료후 2초 뒤에 alert을 띄운다'고 되어있는데, 
2초가 경과하기 전에 form을 입력해서 재경기를 하게 될 경우에는 
abortController라는 Web API를 이용해서 'alert을 띄우는 명령'을 취소하고자 하였습니다.

2021-12-02 01:58 UTC, roy-jung commented on src/ts/store/worker.ts
> +    store.dispatch(Actions.race, { trial: 1 })
네! 전체는 totalAttempt라고 했으니 다른 단어를 써봤어요. 좀더 좋은 명칭이 있다면 제안주시면 좋겠습니다!

2021-12-06 12:44 UTC, limhizy15 commented on cypress/integration/racingcar.spec.js
> +}
그렇군요! 제가 `Command = 함수` 이렇게 생각했었는데 잘못됐었네요! 테스트가 길어지고 복잡해질 때 재남님처럼 Command가 아니라 함수로 사용해야겠습니다 😌

2021-12-06 12:44 UTC, limhizy15 commented on cypress/support/commands.js
> +})
명쾌한 답변 감사합니다! 제가 두루뭉실하게 머릿 속에서만 떠올린 걸 재남님께서 깔끔하게 정리해주신 느낌입니다!

2021-12-06 12:44 UTC, limhizy15 commented on src/ts/app.ts
> +  static #template = /* html */ `
자바할 때 배웠던 개념들이라 다 잊어버렸었는데 지금 답변보고 다시보니까 되게 기초적인 질문이었네요 😂  자바스크립트에서 static이라는 키워드를 쓸 수 있다는 걸 알게되서 정말 좋아요

2021-12-06 12:44 UTC, limhizy15 commented on src/ts/store/viewStore.ts
> +      this.#view.onStoreUpdated(updatedState, state)
감사합니다!

2021-12-06 12:44 UTC, limhizy15 commented on src/ts/store/worker.ts
> +    store.dispatch(Actions.race, { trial: 1 })
전체는 totalAttempt이니까 몇 번째 시도인지 나타내는 변수는 attempt로 해도 괜찮지 않을까요? 저 질문을 달 때 attempt랑 trial이 섞여있어서 조금 헷갈렸던 것 같습니다 ㅎㅎ

2021-12-06 12:45 UTC, merged

2021-12-08 08:51 UTC, guymoon reviewed
안녕하세요 재남님.. 코드 보다가 질문이 하나 생겨 질문드립니다. 바쁘실텐데 시간 괜찮으시면 답변해주시고, 아닌 경우에는 무시해주세요 ㅎㅎ

2021-12-08 08:51 UTC, guymoon commented on src/ts/view/formAttempts.ts
> +  $form
안녕하세요 재남님! PR보고 많이 배웠습니다! 혹시 이렇게 필드를 선언해주셨는데 필드 선언해서 this 때문에 그럴까요? 궁금합니다 ㅜㅜ

2021-12-08 09:20 UTC, roy-jung commented on src/ts/view/formAttempts.ts
> +  $form
특별한 이유 때문이라기보다, 타입스크립트에서는 클래스 내에서 사용할 멤버들을 사전에 정의해두지 않으면 오류로 잡아내서 그랬어요.
https://www.typescriptlang.org/docs/handbook/2/classes.html#--strictpropertyinitialization

2021-12-08 09:23 UTC, guymoon commented on src/ts/view/formAttempts.ts
> +  $form
아하 ts가 그렇군요... ㅎㅎ 답변 감사드립니다 :) ts공부하고있는데 주의해야겠네요.ㅎㅎ

2021-12-08 09:26 UTC, roy-jung commented on src/ts/view/formAttempts.ts
> +  $form
참고로 class fields는 ES 2022에서 정식으로 올라갈 예정이에요

https://github.com/tc39/proposals/blob/master/finished-proposals.md
<img width="1034" alt="스크린샷 2021-12-08 오후 6 26 45" src="https://user-images.githubusercontent.com/6881617/145183312-18b56c0e-e3c8-4795-ad32-6c1a38045ed6.png">
.

2021-12-09 04:19 UTC, guymoon commented on src/ts/view/formAttempts.ts
> +  $form
오 아직 시범중인? 기능이라고 들었는데 이제 정식으로 올라가는군요!! 좋은 정보 감사합니다 ㅎㅎ 클래스 필드에 대해 공부해봤습니다. 재미있네요~!!

2021-12-09 07:43 UTC, guymoon reviewed
안녕하세요 재남 님... 
다시 찾아왔습니다ㅜㅜ (죄송합니다..)

코드를 계속 돌려봤는데 이해가 잘 안 되는 부분이 있어서요.
괜찮으시다면 편하신 시간에 간략하게 답 주실 수 있으실까요..? 

View 클래스에서 `show()`, `hide()` 같은 메서드가 존재하고, View클래스의 자식 클래스(FormAttempts 같은)에서 위 메서드를 사용하신 것 같습니다. 그런데 여기서 this가 어떻게 html요소를 가르키고 있는건지 여쭤볼 수 있을까요? 제 생각에는 this가 클래스를 가르키고 있을 것 같은데, `this.show()`와 같은 것을 어떻게 동작하게 하셨는지 궁금합니다!

바쁘실텐데 시간내주셔서 감사드립니다. 당연한 질문을 매번 하는 것 같은데 항상 친철히 답변해주셔서 감사드립니다 ㅜㅜ 즐거운 하루 보내세요!

2021-12-09 07:43 UTC, guymoon commented on src/ts/view/abstract.ts
> +  show() {
이 부분 어떻게 View 자식 클래스에서 어떻게 this가 dom 요소를 가르키게 되는지 여쭤볼 수 있을까요..?

2021-12-09 07:47 UTC, guymoon commented on src/ts/view/abstract.ts
> +  show() {
```js
show(){
    this.style.display = ''
    return this
  }
```

이 부분 입니다! 짤리네요.. 코멘트를 잘못된 위치에 달았나봅니다 ㅜㅜ

2021-12-09 14:51 UTC, roy-jung commented on src/ts/view/abstract.ts
> +  show() {
html5에 도입된 customElement에요
https://developer.mozilla.org/ko/docs/Web/API/Window/customElements
HTMLElement를 상속받은 View 클래스를 상속받은 하위클래스들은 결과적으로 모두 HTMLElement(customElement)가 됩니다.
이 클래스들의 인스턴스가 곧 dom 그 자체에요.

2021-12-10 06:03 UTC, guymoon commented on src/ts/view/abstract.ts
> +  show() {
지난 미션때도 많이 봤는데.. 커스텀엘리먼트 사용이 뭔가 확 느낌이 안 오네요... ㅎㅎ 레이싱카 미션에 커스텀 엘리먼트로 바꾸려다가 포기하고 다시 원래대로 돌렸네요..ㅎㅎㅎ 그래도 이번 재남님 코드 보고 다음에는 적용 할 수 있을 것 같아요! 감사합니다 :)