[클린코드 2기 신다혜] 자동차 경주 미션 STEP1
next-step/js-racingcar pull request #61
Opened 2022-04-02 07:13 UTC by dahye1013

안녕하세요. 클린코드 2기 신다혜입니다!

그 동안 미션을 진행하면서 제가 생각만 장황해서, 불필요한 코드를 많이 사용했다는 생각을 하게 되었습니다. 
그래서 이번에는 최대한 필요한 코드만 작성하려고 명령형으로 쭉 쓰고, 조금씩 선언형으로 리팩토링하는 방식으로 진행했습니다! 
[[레이싱 실행하기]](https://dahye1013.github.io/js-racingcar/)

## 🎯 요구사항

### 🎯 기능 요구사항

- [x]  자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [x]  자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- [x]  사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [x]  주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [x]  전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.

### 📊 자체 테스트 요구사항

- [x]  초기 화면에는 자동차 등록 input 관련만 보인다.
- [x]  자동차는 1~5글자로 작성해야 한다.
- [x]  자동차 이름을 등록하면 자동차명 이름 등록 버튼은 비활성화 된다.
- [x]  유저가 입력한 자동차 개수 만큼 렌더링된다.

## 🗒 고려한점

- 그 동안 피드백 받으면서 렌더링 관련해서 고민을 해보다가 Document Fragment 키워드를 얻어서 [템플릿](https://developer.mozilla.org/ko/docs/Web/HTML/Element/template) 요소를 적용해봤습니다. 렌더링 되지 않는 템플릿들을 index.html에 미리 만들어두고, 아이디 기반으로 select 하여 복제해서 사용하는 방식으로 진행했습니다!
- 이런 렌더링 최적화 관련해서도 여러가지 공부해보고 있는데, [CSS - will change](https://dev.opera.com/articles/ko/css-will-change-property/) 를 사용하면 레이어를 분리하여 repaint가 적용되지 않고, composite만 변경된다고하여 적용해봤습니다! will chnage - transform, opacity를 사용하였습니다. 크롬 개발 툴에 있는 퍼포먼스 탭에서 확인 했을 때는 for문으로 엘레먼트는 하나씩 조작한 버전보다는 최적화가 된 것을 확인 할 수 있었습니다!

2022-04-02 14:53 UTC, JunilHwang commented on package.json
> +    "live-server": "^1.2.1",
live-server가 설치되긴 했는데,  사용되진 않고 있네요!

2022-04-02 14:53 UTC, JunilHwang commented on package.json
> +    "install": "^0.13.0",
install이라는 패키지는 처음 보는 것 같아요 ㅎㅎ 이건 어떤 용도로 설치하신걸까요?

2022-04-02 14:53 UTC, JunilHwang commented on index.html
> +    </template>
template 활용 👍

2022-04-02 14:53 UTC, JunilHwang commented on src/js/app.js
> +const App = () => {
import와 실행 코드 사이에 개행을 해주면 좋을 것 같아요!

2022-04-03 05:06 UTC, dahye1013 commented on package.json
> +    "install": "^0.13.0",
앗 제가 yarn을 사용하는게 익숙하지가 않아서 liver-server랑 cypress를 install하다가 중간에 좀 꼬였어서 그 흔적이 남아버렸네요.😅   제거해두겠습니다~!

2022-04-03 05:06 UTC, dahye1013 commented on package.json
> +    "live-server": "^1.2.1",
live-server는 원래 vscode 익스텐션으로 사용하고 있었는데, dependency 넣어서 써보고 싶어서 `yarn live-server` 혼자 돌려봤습니다ㅎㅎ. 지금 딱히 사용하지는 않아서 제거해두겠습니다.

2022-04-03 12:00 UTC, JunilHwang requested changes
안녕하세요 다혜님! 자동차 경주 미션을 함께하게 된 리뷰어 황준일입니다 🙇‍♂️
최소한의 코드로 미션 진행을 잘 해주신 것 같아요 👍 
다만 몇 가지 고민할 부분에 대해 피드백 남겼으니 확인 부탁드립니다 😁

요약해보자면,
- 도메인 로직과 UI를 분리하는 작업이 필요할 것 같습니다.
- 만약에 자동차의 전진 조건이 변경된다거나, 혹은 똑같은 input에 대한 output이 나오도록 테스트하기 위해선 어떻게 코드를 작성해야 좋을까요?
  - 지금은 무조건 랜덤하게 테스트를 하기 때문에 가령, 함수를 실행 했을 때 항상 일정하게 true가 나오는지 false가 나오는지 감지하기가 어렵습니다.
  - 무조건 자동차를 전진시키겠다! 라는 테스트를 한다면?
  - 반대로 무조건 자동차를 전진시키지 않겠다! 라는 테스트를 한다면?
  - 위와 같은 테스트를 위해서는 코드를 어떻게 관리해야 좋을까요?
- 그리고 제가 위와 같은 질문을 드리는 이유에 대해서 유추해보시면 좋을 것 같아요!

핵심 적인 내용은 위와 같습니다.

자동차 미션 앞으로 잘 부탁드립니다! 감사합니다 🙏🙇‍♂️

2022-04-04 02:18 UTC, dahye1013 commented on src/js/app.js
> +    state.isGameRunning && GameProcess({ carNames, playTimes });
다음 스텝에서 게임끝나면 다시 `isGameRunning` 상태를 수정하고, 게임 결과를 알려주는 함수를 실행시키려고 만들어 두었는데요.
수정해주신걸보니 `GameProcess` 결과를 await으로 받아서 실행하면 될 것 같네요.👀 수정 해두겠습니다!

2022-04-04 02:32 UTC, dahye1013 commented on src/js/utils/validation.js
> +    this.name = 'ValidationError';
이런식의 에러 핸들링을 이번에 처음 해봤는데, 예시들을 몇 개 봤더니 instanceOf 말고 이런식으로도 하는 것 같아서요!
```javascript
if (err.name === 'ValidationError') alert(err.message);
```
이런 샘플링해보다가 코드가 깔끔하게 지우지 못했네요 😅.  name은 다른 인스턴스들이랑 중복된 이름을 가질 수 있는게 문제가 될 수 있다고해서 instanceOf 기준으로 작업 해두었습니다. 우선 name은 현재 기준으로 필요하지 않아서 삭제해두겠습니다!

2022-04-04 02:35 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +  const updateState = newState => (state = Object.assign(state, newState));
제가 할당을 두번이나 했네요! 훨씬 깔끔해지네요!

2022-04-04 03:15 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +  const $currentElement = duplicateTemplate(TEMPLATE.RACING_CAR_LIST_SECTION);
맞아요! 나름대로 트래킹하기 위해서 selector.js를 만들어 두었는데요.
template이 있는 html, template id가 있는 selector, component 파일을 계속 수동으로 확인해야해서 불편했습니다. 🥲
선택자 줄이는 방법과 web component 샘플링을 조금 더 해보고 진행해보도록 하겠습니다 👀

2022-04-04 04:56 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +    carNames,
다른 곳에서 받아온 property는 다 state로 재할당해서 사용해두었는데
변경되지 않는 데이터들은 그럴 필요가 없네요,,, 👀  state를 애매하게 사용했던 것 같아요. 수정해두겠습니다!

2022-04-04 05:22 UTC, dahye1013 commented on src/js/constants/message.js
> +});
테스트 코드를 먼저 작성하고, 기능을 개발하는 식이면 메시지를 하드코딩 상태로 두어도 되지 않을까 생각했었어요!
테스트 코드가 명세 용도라고 생각했었거든요. 문구가 바뀌거나 오타가 발견되었을때, 테스트 코드를 하드 코딩 문구를 바꾸고 상수화된 메시지를 따로 추가 혹은 수정하는 식으로 진행하면 좋지 않을까 생각해봤습니다.
지금 보니 E2E에서 굳이 필요한 테스트는 아닌 것 같네요  👀 수정해두겠습니다~!

2022-04-04 07:24 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +  const isStepForward = () => Math.floor(Math.random() * 10) > 4;
제가 현재 랜덤 값을 1초마다 생성해서 전진하도록 구현을 해두었는데요. 
다른 방법으로 생각했던 것은 실제 1초마다 랜덤 값을 생성하는게 아니라, 이동 결과를 미리 만들어놓고 게임을 실행시키는 방식으로 수행하는 방식이었습니다.
1. car 객체마다 유저가 입력한 실행 횟수 빈 배열을 생성한다.
2. 배열 횟수만큼 전직 조건 충족 여부를 [1,0,1,1,0] 등으로 채운다.
3. 1초마다 미리 만들어놓은 결과에 따라 전진한다.

결과를 미리 만들면 이동 조건 결과를 충족하는 배열에 대한 상태값을 가져와서 테스트할 수 있을 거라고 생각했었습니다.
그렇게하면 저 목업 결과를 어떻게는 미리 만들어서 볼 수 있지 않을까 고민하다가 그 이상으로 생각이 안닿아서요 😅 
결과 값을 미리 만드는 방법은 혹시 어떻게 생각하시나요? 게임 룰과는 안맞는 방법인가 싶기도 해서요 👀!

2022-04-06 07:08 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +      $el.style.willChange = 'transform, opacity';
우선 `setSpinnerWillChangeHint` 함수 실행은 element가 만들어질때로 수정해두었습니다! 혹시 이 방법이 아니라 forEach를 개선하는 방향을 말씀하신 걸까요? 👀

2022-04-06 11:49 UTC, dahye1013 commented
안녕하세요. 황준일 리뷰어님! 우선 꼼꼼한 리뷰와 생각해봐야하는 방향들을 제시해주셔서 너무 감사드립니다! 🙇‍♂️

덕분에 정말 다양하게 알아보면서 공부해 볼 수 있었습니다!! 🙏 고민하는 시간이 필요한 작업들이 있어서 금방 작업할 수 있는 것들 위주로 작업을 먼저 진행하였습니다. 고민해 볼 부분들은 아직 완료하지 못하였고, 리뷰 주신 내용 기반으로 현재 작업중에 있습니다.

🗒 현재 고민하면서 계속 작업하고 있는 부분은 아래와 같습니다.

- [x]  도메인 로직과 UI 로직 분리
- [ ]  자동차의 전진 조건이 변경된다거나, 혹은 똑같은 input에 대한 output이 나오도록 테스트하기 위해선 어떻게 코드를 작성하면 좋을지
- [ ]  template 코드 개선

## 도메인 로직, UI 로직분리

제가 로또 미션을 수행 할 때는 로또, 금액 모델을 각각 만들어서 사용했는데요. 이 때는 도메인은 서비스에 핵심이 되는 데이터 모델이라 생각을 했습니다. 그러다보니 로또 모델에서 메인 로직 계산, validation, Dom 조작을 다 하다보니 부여된 역할이 과해졌다는 생각을 하게 되었습니다. 그래서 이번에는 도메인에서의 역할을 줄이는 방향으로 작업을 해서 비교해보고 싶었습니다!

도메인 역할을 줄이는 생각에 매몰되다보니 input 값만 들어오면 게임이 순방향으로 실행되고, 게임 결과가 히스토리로 남지 않는 게임에도 도메인이 필요할까? 로 이어져서 도메인이 만들지 않았습니다. 제가 중간 없이 굉장히 극과극으로 구현을 했던 것 같아요 😅 💦

질문하신 의도를 유추해보면서 도메인이 무엇인지 다시 고민을 해봤는데요. 이 과정이 ‘**클린코드**’인 만큼 그것과 관련이 있다고 생각했습니다. 도메인에 대해서 검색하면서 찾아봤는데, 공통의 언어(유비쿼터스)를 코드에 반영하지 않으면 그 코드는 개발자에게 코드의 의미를 해석해야 하는 부담을 준다는 것을 알게 되었습니다. 그래서 도메인을 통해서 코드의 가독성을 높이고, 공통된 언어를 사용하도록 유도하기 위해서는 도메인을 만드는 것이 중요한 것이라는 생각을 하였고, 클린한 코드를 만드는데 도움이 될 것이라는 나름의 결론을 내려보았습니다. ☺️

도메인을 찾아보니 DDD 패턴이 가장 많이 나왔는데, 도메인은 소프트웨어로 해결하고자 하는 문제 영역이고, 모델은 특정 도메인을 개념적으로 표현한 것이라고 나오더라구요. 레이싱 게임에서 문제영역은 게임을 실행시키는 것이라고 생각하여 `state.js` 으로 게임을 전반적으로 관리하는 단일 도메인으로 설정했습니다. 그리고 유저 input이 게임 설정이라고 정의하여, `gameConfiguration` 모델을 만들어 관리하였습니다. 추후, Step2를 진행하며 `gameResult` 관련된 모델을 추가하고자 합니다.

- 기존에 컴포넌트마다 `updateState`함수를 만들어서 사용했습니다. 이것과 관련하여 변경을 제어하는 방법에 대한 코멘트를 받았었는데요.
    1. 컴포넌트는 도메인에 선언된 getter로 상태를 읽을 수만 있다.
    2. 모델 내에 있는 함수로만 상태 값을 수정할 수 있다. 

이런 방향으로 상태를 제어해보고자 모델링 해봤습니다. 👀


## 랜덤값 테스트

cypress에 적용하지는 못했지만, 랜덤 값 생성하는 함수를 수정해두었습니다.

랜덤값 테스트도 나름의 고민을 해봤는데요. 기존에는 1초마다 랜덤 값을 생성하는 방식에서 이동 결과를 미리 만들어놓고 게임을 실행시키는 방식으로 수행하는 방식으로 수정했습니다.

- `‘차이름’ : [1,0,1,1]` 와 같이 해쉬테이블 형태로 만들어 두었습니다.

이런 식으로 코드를 작성하면, 자체적으로 해쉬 테이블 형태의 input 관련한 목업데이터를 만들어서 해당 로직의 ouput을 검증할 수 있을 것이라고 생각했습니다.

하지만, E2E테스트에 어떤식으로 적용해야할지 의문이라 관련해서 조언을 구하고 싶습니다. 혹시 이 방향성이 아닌걸까요 👀 ?

```javascript
setGames = ({ carNames, playTimes }) => {
    this.#carNames = carNames;
    this.#playTimes = playTimes;

    this.#racingCarList = this.#carNames.reduce((acc, cur) => {
      acc[cur] = Array.from({ length: this.#playTimes }, () =>
        this.#isStepForward()
      );
      return acc;
    }, {});

    this.startGame();
  };

```

## template 개선

웹 컴포넌트는 제가 만든 도메인을 활용하기 어려워서 보류해두었습니다.

😅 도메인이 우선 제대로 잡힌 다음에 작업하는게 더 좋을 것 같아서요!

아래는 제가 원래 구현하고자 했던 방향입니다.

1. html에 마크업해둔 `game-process`에 `carNames` 와 `playTimes`라는 `observedAttributes` 의 대상이 되는 속성값을 넣어둡니다.
2. 게임 시작에 필요한 input값이 정상 입력시, `carNames` 와 `playTimes` value를 변경합니다.
3. `attributesChangedCallback` 를 레이싱 게임 로직 실행합니다.

구현 자체은 가능하지만, 위의 방법을 사용하면 사실 도메인과 UI를 나누는 의미가 사라지게 되어서요. 지금 당장 `custom-element`에 파고 들면 구현에만 목적을 두게 될 것 같아서요. 리뷰 받은 내용인 도메인과 UI 고민을 좀 더 해보고자 잠시 보류해두었습니다.

해당 샘플링은 렌더링은 가능하나 미완성입니다. 리팩토링 진행상황만 전달 드리고자 첨부드려요. 아직 리뷰요청 드릴 상태가 아닌 듯 하여 코드에 반영하지 않았습니다! 웹 컴포넌트를 사용하지 않고, 선택자 사용을 최소화 할 수 있는 방법으로 리팩토링하려고 고민하고 있습니다.

<details>
<summary>[웹 컴포넌트 샘플링]</summary>
<div markdown="1">

- app.js
    
    ```javascript
    import UserRacingInput2 from './components/UserRacingInput2.js';
    import GameProcess2 from './components/GameProcess2.js';
    
    const App = () => {
      window.customElements.define('user-racing-input', UserRacingInput2);
      window.customElements.define('game-process', GameProcess2);
    };
    
    App();
    
    ```
    
- index.html
    
    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
    </head>
    <body>
    	<script type="module" src="./src/js/app.js" defer></script>
        <user-racing-input></user-racing-input>
        <game-process carNames="NONE" playTimes="0"></game-process>
    </body>
    </html>
    
    ```
    
- game-process Component
    
    ```javascript
    const customAttribute = 'carNames';
    
    const template = document.createElement('template');
    template.innerHTML = `<section class="d-flex justify-center mt-5">
                              <div id="racing-car-list-items" ${customAttribute} class="mt-4 d-flex"></div>
                          </section>`;
    
    export default class GameProcess2 extends HTMLElement {
      constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.appendChild(template.content.cloneNode(true));
      }
    
      static get observedAttributes() {
        return [carNames];
      }
    
      attributesChangedCallback() {
        // 레이싱 실행 로직
      }
    }
    
    ```
    
- user-racing-input component
    
    ```javascript
    import { makeDisableByID } from '../utils/templateUtil.js';
    import { ERROR } from '../constants/message.js';
    import { MAX_RACING_CAR_NAME } from '../constants/unit.js';
    import { ID } from '../constants/selector.js';
    import ValidationError from '../utils/validation.js';
    
    const template = document.createElement('template');
    template.innerHTML = `
          <section class="d-flex justify-center mt-5">
            <form>
              <fieldset>
                <h1 class="text-center">🏎️ 자동차 경주 게임</h1>
                <p>
                  5자 이하의 자동차 이름을 콤마로 구분하여 입력해주세요. <br />
                  예시) EAST, WEST, SOUTH, NORTH
                </p>
                <div class="d-flex">
                  <input
                    id="car-name-input"
                    type="text"
                    class="w-100 mr-2"
                    placeholder="자동차 이름"
                  />
                  <button
                    id="car-name-submit-btn"
                    type="submit"
                    class="btn btn-cyan"
                  >
                    확인
                  </button>
                </div>
              </fieldset>
              <fieldset>
                <p>시도할 횟수를 입력해주세요.</p>
                <div class="d-flex">
                  <input
                    id="racing-times-input"
                    type="number"
                    class="w-100 mr-2"
                    placeholder="시도 횟수"
                  />
                  <button
                    id="racing-times-submit-btn"
                    type="submit"
                    class="btn btn-cyan"
                  >
                    확인
                  </button>
                </div>
              </fieldset>
            </form>
          </section>
    `;
    
    export default class UserRacingInput2 extends HTMLElement {
      #gameConfiguration = {
        isNameSubmitted: false,
        carNames: [],
        playTimes: 0,
      };
    
      constructor() {
        super();
    
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.appendChild(template.content.cloneNode(true));
      }
    
      connectedCallback() {
        this.shadowRoot.addEventListener('submit', e => {
          e.preventDefault();
          !this.#gameConfiguration.isNameSubmitted
            ? this.submitName()
            : this.submitTimes();
        });
      }
    
      isValidCarName = inputNames => {
        const isValid = inputNames.every(
          carName => carName.length > 0 && carName.length <= MAX_RACING_CAR_NAME
        );
    
        if (!isValid)
          throw new ValidationError(ERROR.INVALID_LENGTH_RACING_CAR_NAME);
      };
    
      removeTimesInputWillChangeHint = () => {
        const $timesInput = this.shadowRoot.querySelector('form').lastElementChild;
        $timesInput.style.opacity = 1;
        $timesInput.style.willChange = 'auto';
      };
    
      submitName = () => {
        const inputNames = document
          .getElementById(ID.CAR_NAME_INPUT)
          .value.split(',');
    
        try {
          this.isValidCarName(inputNames);
          makeDisableByID(ID.CAR_NAME_INPUT);
          makeDisableByID(ID.CAR_NAME_SUBMIT_BTN);
    
          this.#gameConfiguration.carNames = [...]

2022-04-07 09:53 UTC, JunilHwang commented on src/js/components/GameProcess.js
> +      $el.style.willChange = 'transform, opacity';
아아.. 만들어지는 시점을 제가 정확히 파악을 못했네요 ㅎㅎ

2022-04-07 13:00 UTC, JunilHwang commented on src/js/model/State.js
> +  };
State에서 Component를 만들어내는 이유가 있을까요?
다르게 생각해보면, 이게 State의 역할일까요?

2022-04-07 13:04 UTC, JunilHwang commented on src/js/model/State.js
> +  }
이렇게 재선언하는 과정이 꼭 필요할까요?
객체의 역할에 충실한 방법일까요?

2022-04-09 07:07 UTC, dahye1013 commented on src/js/model/GameConfiguration.js
> +  }
추천해주신 코드스피츠 강의를 보고 준일님 코드를 보니까 정말 눈이 번쩍 뜨이네요! 
객체지향에 대해서 공부를 하고나서 코멘트 주신 내용들을 복기를 하고 있는데요. 
다 이해했다고는 할 수는 없지만, 코드에서 보이는게 좀 달라지는 것 같아요. 😳 
명확하게 짚어주신 부분을 이해했는데 `state.js`나 구조적으로 수정이 필요한 부분은 도식화하면서 고민을 해야할 것 같아서 그려가면서 해보고 있습니다.  ☺️
객체를 더 많이 만들어서 책임을 분담해야할 것 같더라구요. 그래서 component마다 모듈을 만드는 방법으로 수정하려고 생각하고 있습니다! 고민을 계속 하느라 코드 수정을 못하고 있네요 😅

2022-04-09 07:18 UTC, dahye1013 commented on src/js/components/UserRacingInput.js
> +      throw new ValidationError(ERROR.INVALID_LENGTH_RACING_CAR_NAME);
`GameConfiguration` 모델 쪽으로 옮겨두었습니다!

2022-04-09 07:32 UTC, dahye1013 commented on src/js/components/GameProcess.js
> +    }, 1000);
상수화 해두겠습니다. 한글도 정말 좋은 것 같아요! 이제까지 상수화는 거의 영어로만 했는데, 다음에는 상수화를 한글 위주로 해보고 싶네요! ☺️

2022-04-10 11:06 UTC, dahye1013 commented on src/js/model/State.js
> +  };
제가 state.js를 싱글톤 객체로 만들면서 이쪽으로 모든 일을 다 위임해버렸던 것 같아요. 
처음에는 객체망으로 뭔가 상태를 관리하려는 목적이었는데, 게임시작이나 모든 것들을 다 저기에 몰아버렸네요ㅠ

2022-04-10 11:11 UTC, dahye1013 commented on src/js/model/State.js
> +  }
외부에서 가져다 쓰려고 했는데, 지금보니까 되게 생각이 짧았던 것 같아요. 👀  
`state.js` 만능객체로 잘못 만들면서 불필요하게 생긴 과정이네요. 
객체망으로서의 기능이 아니라 모든 역할을 거기서 수행하고 심지어 다른 컴포넌트에서도 해당 필드 값들을 사용하면서 생긴 문제였어요.

2022-04-10 11:13 UTC, dahye1013 commented on src/js/model/GameConfiguration.js
> +  };
`updateCarNames`, `updatePlayTimes` 두 함수는 예시로 보여주신 전략 패턴 방식으로 각 검증용 객체를 만드는 방식으로 수정해두었습니다!

2022-04-10 12:29 UTC, dahye1013 commented on src/js/model/State.js
> +export default class State {
좀 고민을 오래했는데. 제가 원하던게 controller였다는 생각이들어요. 
제일 처음에 만들었던게 코드가 콜백으로 데이터를 받아와서 그냥 다른 컴포넌트에 데이터를 전달하는 방식이었는데요. 그 전달을 해줄 객체망을 만들고 싶었던 건데, 정확히 무슨 책임을 부여하고 싶은지 몰랐어서 만능객체가 되었던 것 같아요. 

controller에서 인스턴스화 된 특정 객체를 파라미터로 받고, 다시 다른 컴포넌트에 전달하고...
전략 패턴 보여주신 것 처럼 서브 도메인 기준 오버라이드 된 인스턴스 내장 함수로 처리 한 후에 다시 인스턴스 상태로 반환해서 다른 컴포넌트에 넘기고...그렇게 할 수 있을 것 같다는 생각이 들어요.
이걸 객체지향 지식이 부족해서 코드와 글로 표현을 못했던 것 같아요 👀 이번에 객체에 대해 많이 배운 것 같아요.

사이드 이펙트는 내장 객체의 인스턴스 타입 체크를 안하고 있어서 생기는 문제들일까요? 그것과 제가 getter로 서브 도메인들의 메소드와 필드를 이것저것 꺼내서 쓰고 있었는데 전혀 캡슐화되어있지 않아서 문제가 생길 것 같아요.

2022-04-10 15:10 UTC, dahye1013 commented on src/js/model/GameConfigurationStrategy.js
> +  }
처음에는 말씀해주신대로 전략패턴을 사용해서 c96c0d1
수정했는데요. 유효성 검사해야하는 부분들이 instance를 생성한다음에 instance type인데 체크를 계속 해주니 코드가 반복되더라구요. 24f292c
    
이 문제를 어떻게 해결할까 고민하다가 처음에는 다음과 같이 instance임을 확인할 수 있는 함수를 만들었습니다.
    
```javascript
    instanceCheck() {
        if (!(movingStrategy instanceof ConfigurationStrategy))
          throw Error('ConfigurationStrategy 인스턴스의 인자만 받을 수 있습니다.');
      }
    
     #isStepForward(movingStrategy, _ = this.instanceCheck(movingStrategy)) {
        return movingStrategy.isMoveable() ? 1 : 0;
    }
```
    
 
하지만 이렇게하고나니 제가 instance를 `isStepForward` 외에는 다른 유효성 검사 함수들은 validation 직전에 인스턴스를 만들고 있었는데, (당연하게도) 인스턴스가 없어서 콜백으로 할수 없다는 문제를 직면했습니다. 💦

그래서 생성, validation을 체이닝 구조로 하는 방식으로 
    `new StepForwardConfigurationStrategy().isVaild()`   
이런 식으로 작성하다가, 이런식으로 작성할거면 차라리 빌드패턴을 쓰는게 낫지 않을까? 라는 생각으로 이어져 수정하게 되었습니다.
제가 주신 코멘트를 기억하지 못하고있다가 리뷰 주신 것을 다시 봤는데, 싱글톤으로 해도 되었을 것 같아요. 아직 어떤 패턴을 사용하는게 적합한지 기준을 어디에 두어야하는지 학습이 더 필요한 영역같습니다. 👀

2022-04-10 16:37 UTC, dahye1013 commented
황준일 리뷰어님 다시 한번 감사의 말씀을 드려야 할 것 같네요 🙇‍♂️

제가 패턴이나 이론에 대해서 깊게 공부를 한 경험이 없어서 무엇이 부족했는지 갈피도 못잡고 있었는데, 도움이 정말 많이 되었습니다! 자바스크립트 클래스를 문법적으로만 학습해서 제대로 활용을 못하고 있었네요. 제가 만들고 있는 `state.js` 가 싱글톤이자 만능 객체였다는 것을 깨달았습니다. 😅 

너무 재밌게봐서 bind로 제어의 역전을 통해 MVVM 패턴과 유사하게 구현하는 것을 계속 따라해보고 있었는데, 이것만 계속하다가는 미션 진행을 못할 것 같다는 생각이 들었습니다. 중간에 이해안가는 부분을 계속 돌려가면서 보면서 봤더니, 시간도 거의 몇 배로 들어서요. 소화하는 시간이 필요할 듯 하여, 질문 주신 내용 위주로 1회차를 다시 곱씹으면서 다른 회차는 천천히 보려고 합니다! (리액트 공부를 시작하려했는데, 이걸 한번은 다 보고 하고 싶네요! 나중에 몇 번 더 돌려봐야할 것 같아요.)

객체 지향을 한번 공부하니까, 공부해야 할 키워드들이 계속생겨서요. SOLID 라던지, GOF 디자인패턴도 접하고... 각각 패턴은 무슨 특징이 있는거지? 그 중에 자바스크립트 언어 특성을 고려해서 차용할만한 좋은 패턴은 어떤 것들이 있지? 내가 만든 레이싱 게임에서는 어떤 패턴을 어디에 접목해야하는거지? 이러니까 끝이 안보여서요.👀 모르니까 계속 다른길로 빠져서 공부를 하더라구요. 한편으로는 한번쯤은 꼭 고민해봐야할 일이라는 생각도 들었습니다. 이해하기가 좀 어려워서 정리를 해가면서 학습했습니다.

[(코드스피츠 - 객체지향 자바스크립트 정리)](https://economic-brace-cb7.notion.site/1-f98f9670404a4c30b5d860522a16218f)
<details>
<summary>[코멘트로 받은 객체 관련 키워드 요약]</summary>
<div markdown="1">

### 1. **객체란 무엇인가**

- Polymorphism 2가지 조건을 성립하면 객체라고 볼 수 있다.
    1. Substitution
        
        → 자식은 부모를 대체할 수 있다.
        
    2. Internal Identity
        
        → 객체 생성시의 고유 속성을 유지하는 내적 일관성을 유지한다.
        

### 2. 객체가 되기 위해서는 어떤 조건이 필요한지

- 객체의 본질에 필요한 2 가지 조건
    1. Hide State
        
        → 모든 속성(필드)을 외부에 노출하지 않는다.
        
    2. Encapsulation 
        
        → 메소드는 캡슐화되어야 한다.
        

### 3. 역할과 책임이 무언인지

- 객체의 역할이란?
    - 책임의 집합이다.
    - 모델링시에 객체가 아니라 역할에 책임을 할당한다.
- 객체가 가져야 할 책임이란?
    - (Doing) - 객체를 생성, 다른 객체 행동 조작,
    - (Knowing) - 사적인 정보, 관련 객체
    - 만능 객체가 되지 않도록 책임 이상의 업무를 수행하지 않는다.
        - 책임을 다른 객체에 할당한다.
        - 객체망을 통해서 메시지를 보내 해결한다.

⇒ 책임을 수행하는 대상이 한 종류면 객체, 여러 객체가 참여하면 역할

### 4. 상호 작용이 왜 필요한지

1. 변화에 대한 격리 구간을 세워서야 하기 때문이다.
    - 변화는 오염을 주고, 오염의 전파는 어플리케이션을 실패시킨다. 이를 방지하기 위해 격리하여야 한다.
2. 격리 구간을 세운 후, 통신하기 위함이다.
    - 책임과 역할이 분리되어 특정 객체가 할 일과 아닌 일을 구분하여, 단일 책임 원칙을 지키게 한다.
    - 특정 객체가 바라는 일이 있으나, 객체의 책임이 아닌 경우 메시지를 보내 해결하는 목적을 달성함으로서 오염을 방지한다.
</div>
</details>


객체지향 자바스크립트도 보긴했는데, 이걸 실제로 적용하려니까 막막하게 느껴졌는데, 다행히 전략패턴을 어떻게 구현해야할지 구체적으로 알려주셔서, ‘아 이건 이런식으로 쓰면 유용하구나!’ 를 생각할 수 있었습니다. 

도메인과 서브도메인 기준으로 해야하는 것까지는 조금 알 것 같은데, 프론트엔드 영역에서 도메인은 어떻게 분리해야하는건지 또 의문이더라구요. 비즈니스 단위보다는 컴포넌트 단위로 모듈을 나눠서 관리하는게 나은 것 같기도 하고... 유명한 라이브러리나 프레임워크가 괜히 컴포넌트 단위로 상태 관리하는게 아닌 것 같다는 생각이 들었습니다. 

`State.js`는 정말 많이 잘못되었다고 느꼈습니다. 컴포넌트 사이에 연관관계가 전혀 없어서, 그 전달을 해줄 객체망을 만들고 싶었던 건데, 정확히 무슨 책임을 부여하고 싶은지 몰랐어서 만능객체가 되었던 것 같아요 💦 질문 주신 내용인 이 `State.js`를 범용적인 이름에 걸맞게 관리할 수 있는 느낌이지만, 범용적으로 사용되는 코드가 아니라면? 이 때는 어떤 책임들을 가진 역할을 수행할까라고 생각하니 controller라고 떠올랐습니다. controller는 view와 store를 알기 때문에, 도메인을 객체 단위의 파라미터로 전달받아 넘겨가며 데이터를 핸들링할 수 있고 view 상태를 업데이트 할 수 있어서요. 그래서 아래처럼 짜보고 싶었는데, 고민만 많이 하다가 진도가 안나가지더라구요. 어떻게해야하는지도 조금 헷갈리고해서 진도는 많이 못나갔습니다 😅 
레이싱 게임 기준으로는 컨트롤러는 하나 밖에 없어서 싱글톤이어야 할 것 같다고 생각했습니다. 근데 또 전략패턴을 쓰면 모델마다 컨트롤러를 추상화한 기준으로 오버라이드해서 사용해도 될 것 같더라구요. 기준이 명확하지 않은 상태에서 뭔가를 구현하기 망설여지더라구요.

<details>
<summary>[본래 의도 컨트롤러]</summary>
<div markdown="1">

```javascript
import { instanceCheck } from '../utils/typeCheck.js';
import UserRacingInputModel from './UserRacingInputModel.js';

export default class Controller {
  static instance;

  static getInstance() {
    if (!this.instance) this.instance = new Controller();
    return this.instance;
  }

  startGame(
    gameProcessSettingData,
    _ = instanceCheck(gameProcessSettingData, UserRacingInputModel),
    callback
  ) {
    callback(gameProcessSettingData);
  }
}
```


``` javascript
// components
import UserRacingInput from './components/UserRacingInput.js';
import GameProcess from './components/GameProcess.js';

// models
import GameProcessModel from './model/GameProcessModel.js';
import UserRacingInputModel from './model/UserRacingInputModel.js';

// controller
import Controller from './Controller.js';

const App = () => {
  const controller = Controller.getInstance();

  UserRacingInput({
    userRacingInputState: new UserRacingInputModel(),
    startGame: controller.startGame,
  });

  GameProcess({
    gameProcessState: new GameProcessModel(data),
  });
};

App();
```
</div>
</details>


수정할수록 자꾸 미궁에 빠져들어서요... 도대체 인스턴스는 어느시점에 초기화를 해서 만들어야하고, 언제 타입체크를 하는 것인지. 
어떤 생성 방식을 써야하는건지. 전략 패턴용 클래스 인스턱스들은 어떤 디렉토리쪽에 위치시켜야하는지...  고민하는 시간이 길어서 코드에 손도 잘 안가고, 뭔가를 했다가 다시 돌리게 되더라구요 ✍️.  우선순위를 두고 코드를 수정해야 할 텐데, 우선순위를 파악하지 못하고 있거나, 제가 할 수 있는것보다 좀 욕심을 부리는 것 같다는 생각도 들었습니다. 

> 아직 다혜님께서 실험중인 부분이 있는 것 같아서 RequestChanges로 남겨놓겠습니다. 혹시 피드백을 반영하면서 바로 다음미션을 진행하고 싶다면 이야기 해주세요!

다음 미션 시작전에 피드백을 다 반영하지 못할 것 같아서 동시에 진행해도 될까요 👀 ?? 이렇게 오래 걸릴 줄 몰랐어서 조금 걱정이 되네요 🥲

2022-04-10 16:40 UTC, dahye1013 commented on src/js/model/GameConfigurationStrategy.js
> +  build() {
요 부분은 처음에는 말씀해주신대로 전략패턴을 사용해서 validation 코드들을 c96c0d1 수정했는데요. 유효성 검사해야하는 부분들이 instance를 생성한다음에 instance type인데 체크를 계속 해주니 코드가 반복되더라구요. 24f292c

이 문제를 어떻게 해결할까 고민하다가 처음에는 다음과 같이 instance임을 확인할 수 있는 함수를 만들었습니다.

```javascript
    instanceCheck() {
        if (!(movingStrategy instanceof ConfigurationStrategy))
          throw Error('ConfigurationStrategy 인스턴스의 인자만 받을 수 있습니다.');
      }

     #isStepForward(movingStrategy, _ = this.instanceCheck(movingStrategy)) {
        return movingStrategy.isMoveable() ? 1 : 0;
    }

```

하지만 이렇게하고나니 제가 instance를 `isStepForward` 외에는 다른 유효성 검사 함수들은 validation 직전에 인스턴스를 만들고 있었는데, (당연하게도) 인스턴스가 없어서 콜백으로 할수 없다는 문제를 직면했습니다. 💦

그래서 생성, validation을 체이닝 구조로 하는 방식으로
`new StepForwardConfigurationStrategy().isVaild()`
이런 식으로 작성하다가, 이런식으로 작성할거면 차라리 빌드패턴을 쓰는게 낫지 않을까? 라는 생각으로 이어져 수정하게 되었습니다.
제가 주신 코멘트를 기억하지 못하고있다가 리뷰 주신 것을 다시 봤는데, 싱글톤으로 해도 되었을 것 같아요. 아직 어떤 패턴을 사용하는게 적합한지 기준을 어디에 두어야하는지 학습이 더 필요한 영역같습니다. 👀 사실 공부를하다보니 의도한건 아닌데 패턴을 계속 찾아보게 되서 코드에 자꾸 반영하게 되더라구요.

2022-04-10 16:57 UTC, dahye1013 commented on src/js/components/UserRacingInput.js
> +import UserRacingInputModel from '../model/UserRacingInputModel.js';
이 모델은 기존에 GameConfiguration이라는 이름으로 사용하고 있던 모델입니다!
객체 지향을 한다면 프론트 입장에서는 컴포넌트는 애초에 도메인 모델 기준으로 나누어야 변화에 대응 할 수 있는 구조가 될 것이라는 생각이 들더라구요.
그럼 이름을 모델 이름도 컴포넌트 + model, 전략의 경우도 컴포넌트 + model + strategy 이런 식으로 지어져야 될 것 같다고 생각했습니다.

2022-04-12 04:02 UTC, JunilHwang approved these changes
안녕하세요 다혜님!
무척 고민을 열심히 하신게 느껴지네요 ㅎㅎ
정답을 향해 나아간다기보단, 이런 고민 과정을 통해서 다혜님만의 확고한 관점을 만들어가는 모습이 무척 보기 좋습니다 👍 

다만 지금은 무척 혼란스러운(?) 느낌이 들어요 ㅋㅋ
일단 이번 단계는 여기서 마무리하고, 다음 단계 진행하면서 더 고민해보시면 좋을 것 같습니다.

그리고 몇 가지 피드백 더 남겼으니 확인 부탁드려요!
핵심 포인트는, 자동차 경주에서 제일 중요한게 객체가 뭘까요? 에 대한 부분입니다.

조금 더 힘내봅시다! 화이팅 💪

2022-04-12 04:02 UTC, JunilHwang commented on src/js/model/UserRacingInputModel.js
> +export default class UserRacingInputModel {
이건 지극히 개발적인 관점의 클래스인 것 같아요.
자동차 경주이기 때문에 자동차 클래스를 제일 먼저 만들면 어떨까요?

2022-04-12 04:02 UTC, merged