[클린코드 2기 소인성] 자동차 경주 미션 STEP1
next-step/js-racingcar pull request #62
Opened 2022-04-02 08:35 UTC by InSeong-So

안녕하세요, 클린코드 2기 소인성 STEP1 제출합니다.
도메인을 분리하도록 노력하고 구조에 대한 고민을 지속적으로 적용해보고 있습니다.

<br>

## 구현
### [실행화면 바로가기](https://inseong-so.github.io/js-racingcar/)

### [웹 VSCode로 보기](https://github1s.com/InSeong-So/js-racingcar)

<br>

2022-04-03 08:43 UTC, roy-jung requested changes
안녕하세요, 리뷰어 정재남입니다.
구조에 많은 신경을 쓰신 것 같아요. 그런데 그러다보니 코드 복잡도가 너무 올라간 것 아닌가 싶습니다. 서비스 규모에 비해 코드를 분석하고 이해하는 데에 드는 노력이 많이 요구되어 리뷰하기가 참 어려웠네요. 
여러가지 욕심을 내신걸로 보여요. virtual dom - real dom 비교, pub/sub, functional, prototype, proxy... 이런 것들이 이번 미션의 요구사항을 구현하는 데에 있어 필요했던 것인지, 혹은 그만한 가치가 있는지를 생각해보시고, 가능한 오버엔지니어링을 지양해 주시면 좋겠습니다.
제가 정신이 혼미하여 코드 전반에 대한 리뷰는 드리기가 어렵고, 몇가지 코멘트는 남겼어요.

2022-04-03 08:43 UTC, roy-jung commented on src/js/domain/services/racingGame.service.js
> +    const winnedCars = this.#racingGame.cars.filter(car => car.getMoveCount === winnedCount);
순회 한 번으로 찾아낼 수는 없을까요?

2022-04-03 12:26 UTC, InSeong-So commented on src/js/@helper/valid.js
> +export const isNil = value => value == null;
미션 2를 수행하면서 isNull과 isNil을 어떻게 해당 앱에 녹일까를 고민하다가 포괄적인 isNil선택했었습니다.

리뷰어님 말씀대로 null만을 비교하기 위해선 isNull이 옳았지만 인자 존재 여부를 조건문의 `!`연산으로 체크하는 게 아니라 명시적으로 표현하고 싶었기 때문입니다. 사용 결과 최대한 억제하는 게 옳아 보입니다!

2022-04-03 12:55 UTC, InSeong-So commented on src/js/@helper/dom/diff.js
> +};
테스트해보니 리뷰어님 말씀대로 노드 변화에 따른 diff 수행이 제대로 되고 있지 않네요. DOM 요소가 innerHTML 처럼 동작하고 있어서 의미 없는 비교가 되었습니다.

diff를 넣은 것은 리뷰어님들의 리뷰를 받아보기 위함이었으니, 다음 피드백 때 해당 미션에 맞는 엔지니어링을 진행해볼게요.

2022-04-04 01:34 UTC, InSeong-So commented on src/js/@helper/dom/diff.js
> +    if (isEqualsAttribute(realNode, virtualNode, $r, $v)) return true;
혼란을 줄 수 있는 네이밍이네요. 수정했습니다☺

2022-04-04 01:34 UTC, InSeong-So commented on src/js/@helper/dom/diff.js
> +  for (let i = 0; i < $realNodeAttributes.length; i++) {
max Length를 기준으로 잡았어야 했는데 놓친 부분이 있었네요😭

2022-04-04 01:38 UTC, InSeong-So commented on src/js/@helper/dom/diff.js
> +};
코드를 조금 더 깔끔하게 만들어볼 수 있지 않을까 하는 의도에서 탄생했던 형태입니다.

2022-04-04 01:40 UTC, InSeong-So commented on src/js/@helper/dom/diff.js
> +  if (!isTextNode(virtualFirstChild)) return false;
말씀하신 부분을 생각해보니 그렇네요. 조건문은 `||` 연산자로 합치고 네이밍과 그에 대응하는 로직의 적합성을 다시 한 번 점검해보겠습니다.

2022-04-04 01:40 UTC, InSeong-So commented on src/js/@helper/dom/dom.js
> +  root.innerHTML = stringHTML;
미처 생각하지 못했네요. 적용하겠습니다!

2022-04-04 01:41 UTC, InSeong-So commented on src/js/@helper/util.js
> +      handler(args);
이 코멘트에 대해 추가적인 설명이 가능할까요?

`펼쳐서 제공한다`와 `규칙을 하나 줄인다`를 제대로 이해하지 못해서요😥

2022-04-04 01:41 UTC, InSeong-So commented on src/js/@helper/valid.js
> +export const isLastChar = (target, char) => target.at(-1) === char;
DOM API 활용을 적극적으로 시도해보겠습니다🙏

2022-04-04 01:42 UTC, InSeong-So commented on src/js/Application.js
> +    this.#publisher.subscribe({ render: this.render.bind(this) });
미처 생각하지 못하고 악습관대로 작성했네요. 수정하겠습니다!

2022-04-04 01:42 UTC, InSeong-So commented on src/js/domain/controllers/racingGame.controller.js
> +export default class RacingGameController {
과한 래핑 중 하나라고 생각되며, 제거하는 것에 공감합니다.

2022-04-04 01:44 UTC, InSeong-So commented on src/js/domain/models/car.model.js
> +export default () => ({ __proto__: _interface_(CarModelProps) });
proxy를 사용해서 타입스크립트의 타입 시스템을 흉내 내어 보았습니다. 도메인 모델을 interface로 작성해보려고 했던 시도였어요.

던더 프로토는 2주 전 세션 때 포코가 언급해주셔서 사용을 해봤습니다. setPrototypeOf나 Object.create를 시도해봐야겠네요.

2022-04-04 01:44 UTC, InSeong-So commented on src/js/domain/services/racingGame.service.js
> +    const winnedCars = this.#racingGame.cars.filter(car => car.getMoveCount === winnedCount);
고민해보겠습니다!

2022-04-04 01:49 UTC, InSeong-So commented
우선 정신이 혼미하셨다니 죄송스럽네요🥺

오버 엔지니어링이 맞았으나 좋은 리뷰어들께 리뷰를 받을 수 있는 유일한 시간이었으므로 유의미한 시도였다고 생각합니다. 이번에 조금 무리하더라도 시도해보지 않았던 여러 기술들이나 구조들을 적용해보았고, 회사에서 사용하든 DDD나 헥사고날 아키텍처를 이해하기 위해 작은 규모의 앱임에도 최대한 분리하고 고민함으로써 스스로 공부가 되기도 했습니다. diff의 경우 주니어 레벨 스터디를 리딩하면서 혼자 개발했던 것이므로 꼭 리뷰를 받고 싶어서 꾸겨 넣었습니다.

다른 분들의 커밋된 파일 수에 2배, 만개는 3배에 육박하더군요... 얼마나 힘드셨을지 짐작이 갑니다. 그럼에도 불구하고 좋은 리뷰 남겨주셔서 감사합니다. 다음 리뷰 때는 현재 구조를 전혀 기용하지 않고 앱에 맞는 규모로 코드를 작성할게요.

2022-04-04 04:12 UTC, roy-jung commented on src/js/@helper/util.js
> +      handler(args);
단순히 `handler(...args)`를 의미한 거였어요. handler쪽에서 인수를 배열로 받아야 한다는 규칙을 줄여보자는 의미였습니다 ㅎㅎ

2022-04-12 12:35 UTC, roy-jung approved these changes
인성님 안녕하세요! 전반적인 코드 가독성이 확 올라서 즐겁게 읽었습니다.
다만 service, factory, helper, template의 각 명칭들이 뭔가 딱 와닿지 않는 느낌이랄까, 애매하다는 느낌이 드는데, 콕집어 뭐라고 말해야 좋을지는 모르겠어요 ㅎㅎ 서비스가 내가 아는 서비스가 맞나? 무엇을 팩토리라고 하는거지? 템플릿이랬는데 템플릿이 아닌것 같은...? 
위 내용 및 각 파일에 남긴 코멘트들은 개인적인 소감이나 의견일 뿐이라 크게 신경쓰지 않으셔도 될 것 같아요. 다만 테스트해보니 동작이 안되는 버그가 있는데 이건 해결해주시면 좋겠습니다.
일단은 승인하고, 버그만 해결해주시면 바로 머지하도록 하겠습니다. 고생하셨어요 :)

2022-04-12 12:35 UTC, roy-jung commented on src/js/factory/service.js
> +      if (maxMoveCount === moveCount) return [...result, name];
여기서 새 배열을 만들어야 하나요?

2022-04-12 12:35 UTC, roy-jung commented on src/js/helpers/utils.js
> +// prettier-ignore
이 주석이 종종 보이는데, 어떤 이유에서 무시하게끔 하신건지 궁금해요

2022-04-13 02:00 UTC, InSeong-So commented on src/js/Template.js
> +  }
삭제할게요! 최상위 웹 컴포넌트에서 무엇을 정의하여 효율적으로 사용할 수 있을까를 고민하다가 지우질 않았네요🙇‍♂️

2022-04-13 02:02 UTC, InSeong-So commented on src/js/App.js
> +  #handler = [];
말씀대로 명명하는 게 최선으로 보입니다! 초기값을 배열로 할당한 건 최상위 웹 컴포넌트의 내부에 핸들러를 선언했을 때 오버라이딩을 하지 않으면 에러가 나길래 했었는데... 현재는 각 자식 컴포넌트에 저장해두고 있죠. 이 부분은 제가 놓쳤습니다! 감사합니다🤗

2022-04-13 02:03 UTC, InSeong-So commented on src/js/App.js
> +    ];
이중배열은 제3자가 해당 코드를 봐야만 순서를 이해할 것 같으니 Map으로 수정해보겠습니다!☺

2022-04-13 02:05 UTC, InSeong-So commented on src/js/components/GameSection.js
> +    this.#tryCount = this.getAttribute('try-count');
핫 맞네요...! 의미 없이 할당한 뒤에 호출하고 있었던 코드니 말씀대로 수정하겠습니다🙇‍♂️

2022-04-13 03:17 UTC, InSeong-So commented on src/js/components/ResultSection.js
> +    setTimeout(() => alert(`이번 레이싱 게임의 승자는\n\n${winners} 입니다!\n\n✨축하해요✨`), RESULT_ALERT_DELAY);
좀 더 사용자 직관적이게 변경하겠습니다💪

2022-04-13 03:19 UTC, InSeong-So commented on src/js/components/ResultSection.js
> +  };
로직을 하나 빠뜨렸는데, store를 통해 관리하던 tryCount의 문제입니다. 자동차 이름들은 입력 시 재할당 되어 문제가 없지만... maxTryCount는 게임이 진행된 후에 체크하거든요.

시도 횟수가 최초 3회 > 다시 시작 후 2회 라면 maxTryCount와 같지 않으므로 winner 측정이 안되었던 것입니다.

후다닥 수정했습니다!🤗

2022-04-13 03:27 UTC, InSeong-So commented on src/js/factory/service.js
> +      if (maxMoveCount === moveCount) return [...result, name];
배열을 만들고, 다시 `join`으로 문자열로 치환하고... 불필요한 행위네요. car-names가 많아지니 리소스도 낭비됩니다.
삼항식으로 짧게 만들고 문자열로 변경했습니다!

2022-04-13 03:34 UTC, InSeong-So commented on src/js/helpers/utils.js
> +// prettier-ignore
개인적인 느낌이지만... `prettier` 규격에 정해 놓은 포맷은 가끔 사람이 읽기 난해하게 정렬하는 것 같아요.

- 적용
![1](https://user-images.githubusercontent.com/18283006/163094888-d997a9f2-09d8-4282-88fe-bb0b0fe5cef2.png)

- 무시
![2](https://user-images.githubusercontent.com/18283006/163094893-44d39e7a-d83e-45bd-ab0f-5ba55a05886c.png)

<br />

그래서 좀 더 읽기 편하게 일관성을 지켜줄 필요가 있어보이는 코드에 적용하는 편입니다.

2022-04-13 03:55 UTC, InSeong-So commented
안녕하세요, 재남님! 리뷰 감사합니다. 관련 부분을 수정하여 다시 PR 요청 드릴게요!

+ 적어주셨던 몇몇 코멘트를 설명으로 대체하려고 합니다.

> 다만 service, factory, helper, template의 각 명칭들이 뭔가 딱 와닿지 않는 느낌이랄까, 애매하다는 느낌이 드는데, 콕집어 뭐라고 말해야 좋을지는 모르겠어요 ㅎㅎ 서비스가 내가 아는 서비스가 맞나? 무엇을 팩토리라고 하는거지? 템플릿이랬는데 템플릿이 아닌것 같은...?

저도 이 부분은 많은 고민을 하고 있습니다!

최초 `factory`라는 폴더는 `services`로, 나머지 하위 파일은 각 컴포넌트의 도메인 로직에 맞게 `inputSection.service` 등을 사용했었어요. 그러다보니... ` 한 파일에 하나의 로직만 존재하고, 이를 export하는 너무 과도한 오버엔지니어링 아닌가`라는 의문점이 들었죠. 어떻게 해야 규모에 맞고 제3자가 읽고, 이를 확장할 때 유연하게 대처할 수 있을까?에 대한 좋은 방법을 찾다보니 코드가 짜여진 형태로 그들의 생각을 일관되게 만들고자 했습니다.

`index`에서 export하는 함수명칭은 `pipeline`이죠. `공장은 어떤 재료가 들어가든 완성된 형태로 무언가 반환되므로, 파이프라인을 통해 어떤 input을 집어넣으면 이러한 역할을 한다`의 취지로 접근했습니다. 파이프만으로는 결과물이 나오지 않으므로 이를 제어할 실제 기기들, 즉 `service`라는 명칭으로 분리하여 pipline에 service가 의존하도록 설계했습니다.

어제 세션 이후 다른 참여자분들과 4시간 넘게 이야기하면서, 그들이 어떻게 받아들이는지 물어본 결과 재남님과 동일한 느낌을 받았고, 저도 동일하게 생각했습니다. 의도는 이러한데 충분히 드러나지 않는 느낌이에요. 다만... 다음 미션을 위해 설계적인 부분을 건드리면 너무 과하게 작업을 해야할까 현재 상황을 유지하고자 합니다😭

혹시 재남님이라면 어떤 네이밍을 채택하셨을까요? 다음 미션 때는 적극적으로 생각해보고 코드를 작성하고 싶네요.
마지막으로 해당 미션은 종료가 되어 다른 리뷰어님으로 배정되었으니... 재남님 생각에는 프론트엔드 개발자로서 어떤 것을 더 심화적으로 공부하면 좋을 지 키워드를 알려주실 수 있을까요?

2022-04-13 04:16 UTC, InSeong-So commented on src/js/factory/index.js
> +};
이 부분은 아래 길게 코멘트에 대체했습니다.
최초 작성 시 재남님 의견대로 했으면 더 깔끔했을 수 있겠네요😥

각 컴포넌트가 `factory`에만 의존해서 서비스 로직을 알 필요 없게 만들고자 했습니다. factory에는 try-catch로 에러도 처리하고, 서비스 로직은 pipe를 통해만 호출하도록...
하지만 그 결과 의도가 정확히 전달되지 않고 개발자들 사이의 표준을 헤집어 놓은 느낌이네요...😇

2022-04-13 05:16 UTC, roy-jung commented on src/js/helpers/utils.js
> +// prettier-ignore
요건 아마도 prettier 설정에 'printWidth'를 현재 설정보다 작게 잡으시면 해결될 것으로 보여요. 물론 완전한 해결책은 아니긴 하지만 ;)

2022-04-13 05:33 UTC, roy-jung commented
아래 내용은 `이렇게 하는게 좋겠다` 보다는 `저라면 이렇게 해볼것 같다` 정도이고 제가 인성님 코드를 똑같이 짤 자신은 없으니..
그냥 `저사람은 저렇게 생각하는구나` 정도로만 여겨주시길 바라며... 

- factory/index => executor들을 실제 호출하는 곳들로 옮기고 나면 pipeline만 남게 되니 pipeline을 utils로 옮깁니다.
- service는... store를 끼얹은 renderer 뿐이므로, view(component)에 위치시키는 편이 좋을 것 같아요. store와 component의 의존성을 끊었다곤 하지만 그 대신 view에 직접 관여하는 service가 store와 결합했으니, 결과적으론 마찬가지 아닌가 싶거든요.

> 프론트엔드 개발자로서 뭘 더 심화적으로 공부하면 좋을지

이미 차고 넘치게 잘 하고 계신 것 같습니다. 생각의 깊이나 지식의 양은 저보다 월등히 뛰어나신 것 같다고 생각해요. 아마도 지금 느끼시는 갈증은 아마도 절대적 경험량의 부족에서 기인한 것이라 생각합니다. 이론을 많이 알고 있더라도 어떤 상황에서 어떤 이론을 적용할지 혹은 하지 않을지를 판단하는 데에는 경험을 통해서만 체득되는 암묵지 영역이 존재하니까요. 이러한 암묵지는 단기에 채울 수 없기에 그저 많이 고민하고 다양하게 시도해보며 시행착오를 겪는게 최고라 생각합니다. 스스로 부족하다 생각하지 마시고 그저 코딩을 즐기시길 바라요 :)

2022-04-13 05:37 UTC, roy-jung approved these changes
깊이 고민하고 많은걸 개선하느라 너무 고생하셨습니다!! 승인 및 머지하곘습니다.

아래 내용은 `이렇게 하는게 좋겠다` 보다는 `저라면 이렇게 해볼것 같다` 정도이고, 제가 인성님 코드를 똑같이 짤 자신은 없으니..그냥 `저사람은 저렇게 생각하는구나` 정도로만 여겨주시길 바라며...

- factory/index => executor들을 실제 호출하는 곳들로 옮기고 나면 pipeline만 남게 되니 pipeline을 utils로 옮깁니다.
- service는... store를 끼얹은 renderer 뿐이므로, view(component)에 위치시키는 편이 좋을 것 같아요. store와 component의 의존성을 끊었다곤 하지만 그 대신 view에 직접 관여하는 service가 store와 결합했으니, 결과적으론 마찬가지 아닌가 싶거든요.

> 프론트엔드 개발자로서 뭘 더 심화적으로 공부하면 좋을지

이미 차고 넘치게 잘 하고 계신 것 같습니다. 생각의 깊이나 지식의 양은 저보다 월등히 뛰어나신 것 같다고 생각해요. 아마도 지금 느끼시는 갈증은 아마도 절대적 경험량의 부족에서 기인한 것이라 생각합니다. 이론을 많이 알고 있더라도 어떤 상황에서 어떤 이론을 적용할지 혹은 하지 않을지를 판단하는 데에는 경험을 통해서만 체득되는 암묵지 영역이 존재하니까요. 이러한 암묵지는 단기에 채울 수 없기에 그저 많이 고민하고 다양하게 시도해보며 시행착오를 겪는게 최고라 생각합니다. 스스로 부족하다 생각하지 마시고 그저 코딩을 즐기시길 바라요 :)

2022-04-13 05:37 UTC, merged