[클린코드 2기 곽세진] 자동차 경주 미션 STEP1
next-step/js-racingcar pull request #66
Opened 2022-04-03 19:28 UTC by Blackraven93

리뷰어님 반갑습니다 :)
자동차 경주 미션 1단계 제출합니다!

이번 미션에서 MVC 패턴을 구현하기 위해서 노력했습니다.
나름 공부하고 적용한 부분인데 익숙하지 않아서 잘하고 있는지 피드백 부탁드립니다!

또한 랜덤 관련하여 테스트 코드 작성에 어려움이 있어 키워드를 얻고 싶습니다!

마지막으로 setTimeout의 활용도가 적절한지 궁금합니다.  

[샘플 링크](https://blackraven93.github.io/js-racingcar/)
[명세 정리](https://github.com/Blackraven93/js-racingcar/tree/step1/src)

2022-04-06 02:58 UTC, pocojang requested changes
안녕하세요
세진님!

리뷰어 장현석입니다.
일단 리뷰가 좀 늦어 죄송합니다.

## 전반적인 리뷰

코드 정말 재미있게 봤어요
정말 많은 고민과 시도 그리고 도전이 보여서 좋았습니다.
꽤 많은 시도를 하셨는데 코드가 담백하고 제 역할만 하는 것으로 보여 좋았어요

## 불필요한 것들 정리

불필요한 찌거기 파일들이 많이 남아있어요!

- 주석
- 맥, 젯 브레인 불필요한 로컬파일
- EOL, EOF

## 구조

### 컨트롤러

컨트롤러와 이벤트의 결합이 애매하게 있어요
완전히 포함시키던가 완전히 분리할 수 있는 방법을 찾아보시면 좋겠네요.
사실 제가 세진님의 의도를 파악하지 못한 것도 있어요

### IIFE

꼭 사용했어야 했을 이유가 무엇인지 궁금한데 반대로 남겨주시면 의미를 파악하고 리뷰해볼게요!

### render

정말 여기저기 잘 활용되고 있는데요
코드도 깔끔하고 단위도 작아서 이해하기 좋았어요.
다만 더 커질 수 있는데 그에 대한 예외나 명시적인 부분이 보여서 한번 고려해보시면 좋겠네요

### 로딩 스피너

로딩 스피너 `setTimeout`이 너무 날 것으로 있는데 반복문과 렌더링 로직까지 있어서
향후 성능상, 에러 대응상 어려움이 많을 것 같아요

`Promise`로 바꿔보시는 것을 제안합니다 :)

---

이 외에 항목들은 코멘트로 남겨놨습니다!

2022-04-06 02:58 UTC, pocojang commented on src/js/Model/Validator.js
> +    return text.split(',').some(e => e.length > MAX_CARNAME_LENGTH)
`some` 활용 좋아요 👍

2022-04-06 02:58 UTC, pocojang commented on src/js/View/Component/Form/Fieldset.js
> +const Fieldset = (name, placeholder) => {
상태가 존재하지 않는 컴포넌트를 만들어보셨네요 좋은 시도입니다!

2022-04-06 02:58 UTC, pocojang commented on src/js/View/Component/Form/InputText.js
> +const InputText = (text) => {
이 부분은 꼭 컴포넌트화할 필요가 있을까? 고민이 들긴하는데요
`<p>`와 `InputText`와의 연관성도 잘 느껴지지 않기도하고요

2022-04-06 02:58 UTC, pocojang commented on src/js/View/Render/removeSpinner.js
> +      .forEach((tag) => tag.removeChild(tag.querySelector('.spinner-component')))
반복문이 아니라 일괄로 지울 수 있는 방법이 없을까요?

2022-04-06 02:58 UTC, pocojang commented on src/js/View/render.js
> +  fragment: document.createDocumentFragment(),
👍

2022-04-06 02:58 UTC, pocojang commented on src/js/View/render.js
> +  create(component) {
`textContent`에만 대입되는 상황인데 어떤 이유가 있으셨나요?!
명시적인 표현도 필요해보입니다

2022-04-06 02:58 UTC, pocojang commented on cypress/integration/racing/racing.spec.js
> +
😢

2022-04-06 16:00 UTC, Blackraven93 reviewed
리뷰어님 피드백 주셔서 감사합니다. 🙌
혹시 리뷰에 대해 피드백을 받고 코드를 작성하고 싶습니다!

그리고 궁금한 부분이 있어 코멘트 남깁니다.

1. 로또와 비슷하게 랜덤한 숫자에 대해 어떤 방식으로 테스트할 지 잘 모르겠습니다.. 테스트를 작성하다 보면 마치 구현처럼 두서없이 길어져 지우고 작성하고를 반복하는 것 같습니다 ㅠㅠ 스스로 해결하고 싶은데 키워드를 받을 수 있을까요?

2. Event와 Controller를 조금 더 명확하게 분리하거나 결합하라고 코멘트 남겨주셨습니다.
formHandler에 대한 부분일까요? 어떤 부분을 개선하면 좋을 지 조금만 이야기해주시면 감사하겠습니다.

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/Model/Racing.js
> +      .map(e => e >= WINNING_NUMBER )
- 당시에 의미를 명확하게 하도록 구분했는데 지금 보니 불필요한 것 같습니다. 수정하겠습니다
- 아.. 이 부분은 제가 신경을 못썼던 부분입니다.. 수정하겠습니다.

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/Model/Validator.js
> +  static isEmpty(text = '') {
아 당시 Validator의 static isEmpty를
자동차 시도횟수 및 자동차 이름 이렇게 두곳 모두에서 사용할까 고민했습니다.
결국 분리해서 처리 했는데 당시 type을 제가 인식하기 위해 default를 설정했습니다.
(input type이 number일 때 도 string인데 당시에는 계속 헷갈렸습니다 😅)

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/View/Component/Form/Fieldset.js
> +const Fieldset = (name, placeholder) => {
하지만 상태를 처리하지 못하고 이벤트를 처리하지 못해 리터럴에 대한 의미가 컴포넌트를 모아 렌더링하는 이점말고
다른 부분을 느끼지 못했습니다. 제가 모르는 키워드와 개념이 있는 것 같습니다.

궁금한 부분이 상태라고 정의하는 것이
`프론트서버의 상태와 동기화된 마크업의 어느 한 형태`라고 정의하면 좋을까요?

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/View/Render/removeSpinner.js
> +      .forEach((tag) => tag.removeChild(tag.querySelector('.spinner-component')))
생각해보겠습니다.

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/View/render.js
> +  create(component) {
XSS 관련하여 innerHTML을 지양하게 되는 것 같습니다.
명시적으로 표현하고 따로 문자열 처리를 통해 잡는 것이 적절한 방법 같습니다.
보안적인 지식은 굉장히 짧아 기능적으로 textContent를 사용할 수 있을 때는 주로 사용했었습니다.
리액트는 `dangerouslySetInnerHTML`를 제공해줘 고려를 안했던 것 같은데..
제가 잘 모르는데 고민만 많은 것 같습니다..

2022-04-06 16:00 UTC, Blackraven93 commented on src/js/Controller/InputEvent/racingCarInputEvent.js
> +export const racingCarInputEvent = (function(){
IIFE를 사용하기 전까지 고려했던 부분은
class를 사용할까? 인스턴스가 반복되지 않고 static만 사용한다면 너무 번잡할거라고 생각했습니다.
도메인 부분에 클래스를 사용한 이유는 비록 인스턴스가 하나밖에 만들어지지 않았지만 해당 모듈에 관한 내용들이
많아질거라고 생각해 특별하게 클래스로 구성했습니다. (2단계 & 3단계를 고려)
객체리터럴을 사용할까? 그러기에 데이터를 서로 전달할 수 있는 수단이 없어 보였습니다 (클로저)
단순하게 함수를 이용하여 표현을 해도 괜찮지만 함수를 실행한다는 개념 (동작) 보다 객체를 이용한 메서드로
보다 명시적으로 작성하기 위해 IIFE를 고려하게 되었습니다.

두서없이 말이 길어졌는데 제가 고려하는 부분이 제가 보는 시야의 한계여서 개선점에 대해 화두를 던져주시면 좋을 것 같습니다!

2022-04-07 15:36 UTC, pocojang commented on cypress/integration/racing/racing.spec.js
> +  describe('레이싱 게임 테스트', () => {
좋습니다 👍 
TODO 주석을 활용해보는 것도 추천드려요!

2022-04-07 15:36 UTC, pocojang commented on src/css/index.css
> +@import "./ui/spinner.css";
수정할 필요는 없습니다 ㅎㅎ

2022-04-07 15:37 UTC, pocojang commented on src/js/Controller/InputEvent/commons/convertDisabledAttr.js
> +const convertDisabledAttr = ({input, button}) => {
`util`의 사전적인 의미를 먼저 파악해보시는게 어떨까요?

2022-04-07 15:39 UTC, pocojang commented on src/js/Controller/InputEvent/racingCarInputEvent.js
> +    if (Racing.validate.carNameLength(value)) return alert(VALIDATE.ALERT_WRONG_RACING_CAR_NAME)
반환되는 것을 활용하는게 없다면 `alert()`을 반환할 필요는 없답니다ㅎㅎ
`alert()`은 반환이 없기 때문인데 `formHandler()`에서 반환받는게 없다면 반환할 필요가 없지 않을까요?

2022-04-07 15:40 UTC, pocojang commented on src/js/Controller/InputEvent/racingCarInputEvent.js
> +          button: event.target.nextElementSibling
`nextElementSibling`이 100% 보장되는 경우일까요?
그렇다면 수정할 필요가 없습니다.
예를들면 `그룹 버튼` 같은 형태면 보장된다고 볼 수 있겠죠?
더 안전할 필요가 있다면 더 명시적이고 안전한 방법이 좋을 수 있죠 ㅎㅎ

2022-04-07 15:41 UTC, pocojang commented on src/js/Model/Validator.js
> +  static isEmpty(text = '') {
아하 많은 시도를 해보신 흔적이군요 ㅎㅎ

2022-04-07 15:44 UTC, pocojang commented on src/js/View/Render/removeSpinner.js
> +      .forEach((tag) => tag.removeChild(tag.querySelector('.spinner-component')))
혹은 `Fragment()`를 고려해보실 수도 있고요?

2022-04-07 16:23 UTC, pocojang commented
> 리뷰어님 피드백 주셔서 감사합니다. 🙌 혹시 리뷰에 대해 피드백을 받고 코드를 작성하고 싶습니다!
> 
> 그리고 궁금한 부분이 있어 코멘트 남깁니다.
> 
> 1. 로또와 비슷하게 랜덤한 숫자에 대해 어떤 방식으로 테스트할 지 잘 모르겠습니다.. 테스트를 작성하다 보면 마치 구현처럼 두서없이 길어져 지우고 작성하고를 반복하는 것 같습니다 ㅠㅠ 스스로 해결하고 싶은데 키워드를 받을 수 있을까요?
> 2. Event와 Controller를 조금 더 명확하게 분리하거나 결합하라고 코멘트 남겨주셨습니다.
>    formHandler에 대한 부분일까요? 어떤 부분을 개선하면 좋을 지 조금만 이야기해주시면 감사하겠습니다.

## 1. 랜덤 테스트

@padawanR0k 님의 사례를 참고해보실까요?!

https://github.com/next-step/js-racingcar/pull/65#discussion_r844068354

## 2. Event & Controller

Event와 Controller가 얽혀있는 느낌입니다.
@Blackraven93 님 말씀대로 `formHandler()` 영향도 없지는 않고요.
폴더 구조만을 봤을때도 좀 애매하기도 한데요

해당 피드백은 제 견해도 들어간 부분이 저의 피드백을 무작정 수용하실 필요없습니다!
수정해야할 근거를 모르겠는데 리뷰어의 피드백이 무조건 옳다고 생각하시지는 않으셔도 된답니다 :)

다만 현재 스텝1일뿐이니 완벽하게 해결하지 못하시고 넘어가셔도 되고요~
스텝2가면서 차근차근 생각해보시는 것도 좋아요!

2022-04-29 14:41 UTC, pocojang commented on src/js/util/disable.js
> +const disable = ({ input, button }) => {
무엇을 `disable`하는지 정의하는게 좋겠네요~
실제로는 정의할 수 있는 요소가 한정적이거든요

2022-04-29 14:43 UTC, pocojang commented on src/js/View/Component/Game/Track.js
> +      ${type === 'go' ? Go() : Wait()}
### 1.
타입과 같은 문자열은 오타가 날 수 있는 경우가 상당하니 상수로 관리하는 것을 추천합니다 


### 2.
`Go()`
`Wait()`
와 같은 녀석이 `HTML String Template`인데 함수명은 동작을 의미하니 상당히 헷갈리네요

2022-04-29 14:44 UTC, pocojang commented on src/js/View/Component/Form/SubForm.js
> +    <div class="d-flex" data-form="${dataName}-container">
`data-*`가 큰 의미는 없어보여 아쉽네요 😢

2022-04-29 14:45 UTC, pocojang commented on src/js/Model/Racing.js
> +  }
오우 너무 멋진 시도입니다

2022-04-29 14:45 UTC, pocojang commented on src/js/Controller/racingGameController.js
> +      return alert(VALIDATE.ALERT_LESS_RACING_COUNT);
이런 개행의 경우 중괄호로 감싸주는게 안전하답니다 :)

2022-04-29 14:47 UTC, merged