[클린코드 3기 이수진] 자동차 경주 미션 STEP 1
next-step/js-racingcar pull request #99
Opened 2022-07-24 08:34 UTC by jin-2

안녕하세요 :)
리뷰 잘 부탁드립니다.

## 요구사항
- [x] 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [x] 자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- [x] 사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [x] 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.

2022-07-26 00:14 UTC, jho2301 commented on cypress/e2e/racing_car.cy.js
> +  });
테스트는 그 자체로 스펙문서의 역할을 할 수 있어야 한다고 생각해요. 위 테스트가 어떤 스펙을 보장하는지 모호한 것 같아요.

2022-07-26 00:15 UTC, jho2301 commented on cypress/support/commands.js
> +});
깔끔하네요 👍

2022-07-26 01:16 UTC, jho2301 requested changes
안녕하세요 수진님
리뷰 맡게된 전환오입니다!

전반적으로 모듈이 적절하게 분리가 되어있는 것으로 보여요.
추상화레벨도 적절하다고 생각됩니다
덕분에 드릴 수 있는 코멘트가 그렇게 많지는 않네요😅

미션하시면서 고민이 생기셨다면 PR메시지에 올려주세요 같이 고민해볼 수 있을 것 같아요!
코멘트 확인해주시고 의견 남겨주시면 감사하겠습니다!

2022-07-26 01:16 UTC, jho2301 commented on src/js/selector.js
> +export const $racingCarInner = document.querySelector('#car-racing-inner');
자동차경주같은 경우 초기 렌더 후 DOM요소에 대한 변경이 없지만, 
프로그램 라이프사이클에서 DOM요소가 추가되거나 제거될 여지가 충분히 있기 때문에
변경에 대한 고려가 있으면 좋을 것 같아요

2022-07-26 01:16 UTC, jho2301 commented on src/js/util/index.js
> +  const forwardStandard = 3;
```ts
export const isValidNumberOfCharacters = (textList) => {
  const MAXIMUM_NUMBER_OF_CHARACTER = 5;
  return textList.every((text) => text.length <= MAXIMUM_NUMBER_OF_CHARACTER);
};
```

위 함수는 상수가 uppercase인데 getIsForward camelcase네요
일관적으로 네이밍컨벤션이 적용되면 좋을 것 같아요

2022-07-26 01:19 UTC, jho2301 commented on package.json
> +  }
https://www.geeksforgeeks.org/difference-between-dependencies-devdependencies-and-peerdependencies/

위 아티클이 깔끔하게 정리돼있어서 일독 추천드려요

2022-07-26 01:45 UTC, jho2301 commented on src/js/racing.js
> +  }
1. 반복문이나  상위스코프 변수에 사이드이펙트를 일으키게 작성되었는데 필요 이상으로 복잡해보여요. 좀 더 간결하게, 선언적으로 변경해볼 수 있을 듯해요
2. 하나의 forEach에서 여러 동작을 하는데 분리를 해볼 수 있을 것 같아요!

```ts
[...Array(tryCount)].forEach(() => {
    const resultOfOneCycle = cars.map((car) => getIsForward(getRandomIntInclusive(0, 9)));

    cars.forEach((car, i) => updateCarStep(car, resultOfOneCycle[i]));
  
    appendRacingEl(resultOfOneCycle);
})
```

2022-07-30 07:04 UTC, jin-2 commented on cypress/e2e/racing_car.cy.js
> +  });
"주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다." 이 요구사항을 테스트 케이스로 만들고 싶었는데요. 
랜덤하게 전진할 수도 있고 멈출수도 있어서, 어떻게 테스트를 작성해야 좋을지 잘 모르겠네요.🥲
이런 부분은 테스트를 작성하지 않는게 좋을까요?

2022-07-30 07:23 UTC, jin-2 commented on package.json
> +  }
링크 감사합니다! devDependency로 다시 설치했어요!

2022-07-30 07:28 UTC, jin-2 commented on src/js/selector.js
> +export const $racingCarInner = document.querySelector('#car-racing-inner');
음... 변경에 대한 고려라면 🤔
초기 렌더링시에 변수에 담아두는게 아닌,
돔을 조작할 때 셀렉팅해서 사용하는 것을 말하는 걸까요?

2022-07-30 07:30 UTC, jin-2 commented on src/js/util/index.js
> +  const forwardStandard = 3;
옷! 변경했습니다 😅

2022-07-30 13:01 UTC, jin-2 commented on src/js/racing.js
> +};
cars.js 파일로 분리해 보았습니다!

2022-07-30 13:04 UTC, jin-2 commented on src/js/racing.js
> +};
- createCars 함수는 newCars를 바로 반환하도록 수정했습니다.
- updateCars 함수를 생성하여 createCars의 역할을 분리했습니다.

2022-07-30 13:09 UTC, jin-2 commented on src/js/racing.js
> +  }
제안 주신 코드를 반영하여 함수로 분리했습니다! 
`[...Array(tryCount)]` 요렇게 작성하니 `undefined`가 채워져서 배열이 만들어지네요. 감사합니다. 👍🏽

2022-07-30 13:15 UTC, jin-2 commented
환오님, 안녕하세요! 
제가 고민했던 코드들을 쏙쏙 찝어서 리뷰해 주셔서 감사합니다.👍👍

다시 한번 내용 확인 부탁드려요!

2022-08-01 03:00 UTC, jho2301 commented on cypress/e2e/racing_car.cy.js
> +  });
여러가지 접근방법이 있을 것 같아요. 
일단 제가 생각하는 방법을 구체적인 구현을 제하고 생각해본다면,
1. 유닛테스트로 세분화해 기능의 동작을 테스트한다.
2. 난수생성에 대한 책임은 언어에 있으므로 난수생성에 대한 부분을 모킹하고, 모킹한 값에 대해서 제대로된 결과가 도출되는지 테스트한다.
요렇게 해당 기능을 보장해볼 수 있을 것 같네요.

그렇다면 나오는 스펙은 `자동차는 생성한 난수값이 4이상일때 전진한다` 정도로 작성해볼 수 있지 않을까요?

2022-08-01 03:04 UTC, jho2301 commented on src/js/selector.js
> +export const $racingCarInner = document.querySelector('#car-racing-inner');
요것도 여러가지 방법이 있을 것 같아요!

말씀해주신 것처럼 필요할 때 요소를 가져오는 방법도 있을테고,
저는 단순하게 객체로 관리를 하고, 프로그램 초기화하는 코드에서 쿼리 하는 모습을 생각했어요.

2022-08-01 03:17 UTC, jho2301 commented on src/js/racing.js
> +  }
Array(number) 로 함수호출을하면 length값을 number로 가지는 empty 배열이 만들어져요. 

empty는 Array.prototype의 순회메서드에서 스킵해요 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/44419181/182065189-42dfbf62-4159-4c26-a6c8-97fc9bd45c07.png">



전개연산을 해주게 되면 empty요소가 undefined로 반환되어요
살짝 트리키한데 간결해서 자주 사용하고있어요. 

`Array(length).fill(null)`  요렇게 작성해볼 수도 있어요
<img width="526" alt="image" src="https://user-images.githubusercontent.com/44419181/182065081-bd3e091a-8734-4cad-aa5b-6f441bf7e13a.png">

2022-08-01 03:31 UTC, jho2301 approved these changes
반영해주신 코드 잘 봤습니다! 
모두 적절하게 반영해주신 것 같아요
남겨주신 질문은 각 질문에 답글로 달았어요

스텝2에서도 함수와 객체의 역할에 집중해주시면서 진행해보시면 무리없이 잘 진행하실 거라 생각합니다

남은 스텝도 화이팅입니다! 감사합니다

2022-08-01 03:32 UTC, merged

2022-08-01 13:45 UTC, jin-2 commented on cypress/e2e/racing_car.cy.js
> +  });
감사합니다! 참고할게용 ☺️

2022-08-01 14:00 UTC, jin-2 commented on src/js/racing.js
> +  }
우와! 예제 코드까지! 감사합니다. 이해가 더 잘되었어요.
제가 callable 하다는 뜻이 잘 이해가 안가는데요.
음... 값을 직접 채워야 한다는 뜻인가요?